### ISSUE TITLE
"Back"-button usage is incosistent

### ISSUE THREAD

**Issue by utack** [arpitkh96/AmazeFileManager#101]
When browsing /storage/emulated/0/ and pressing either the in-browser or softkey "back" Amaze wants to close the app.
When browsing /storage/sdcard1/ and pressing either the in-browser or softkey "back" Amaze goes up to /storage and then to /

It should probablly behave the same way, no matter which folder is browsed.
Either add / as bookmark, so it can be browsed, also on devices without external sdcard, and make the app close when pressing "back", or use the back button to go one folder up.

**Comment by vishal0071** [comment]
One tab is meant to be used by root users, otherwise it leaves you wonder how to move down to root if back button doesn't work.
You can always change this behaviour by changing home for each tab according to your needs.

**Comment by vishal0071** [comment]
Issue resolved I suppose?

**Comment by utack** [comment]
I did not understand, how a user without external sdcard is ever going to browse to "/" in the file system, or why it behaves differently, but since you say it is intentional and by design I suppose it is resolved.

**Comment by ildar** [comment]
Did anyone consider to implement "Back" button behavior to "get to the last view seen"? Just as the "Back" button's normal behavior is. And just like the Back button works in CyanogenMod File Manager?

**Comment by ildar** [comment]
I am sorry to conclude that Amaze FM's navigation still sucks.
