### ISSUE TITLE
can not open text-files in /data except of /data/data

### ISSUE THREAD

**Issue by jensMF** [arpitkh96/AmazeFileManager#103]
I can only open text-files in /data/data* in /data or /data/misc or else, nothing happens…

**Comment by jensMF** [comment]
I just tried to open /data/misc/wifi/* (.conf and .txt files) and it is not working. Loaded and biuld a few minutes ago.

**Comment by arpitkh96** [comment]
try now .with latest commit

**Comment by jensMF** [comment]
This seems to be fixed. Thanks a lot :-)
