### ISSUE TITLE
App crashes if I try to open a Database

### ISSUE THREAD

**Issue by jensMF** [arpitkh96/AmazeFileManager#104]
As described in title. If I try to open a Database Amaze crashes…

**Comment by vishal0071** [comment]
It crashes if you try to open a database with lots of entries. Try opening relatively small database.

**Comment by vishal0071** [comment]
Issue fixed, compile the latest changes.

**Comment by jensMF** [comment]
I tried a database with 4kb for testing is this to big?

**Comment by vishal0071** [comment]
It should work, where is the database? And which database is it? Is it sqlite?

**Comment by jensMF** [comment]
I loaded and compiled new sources the day before yesterday and it doesn't work. I tried a database in /data/data/'app_name'/database.db, in /data/data/'app_name'/databases/database.db and in /storage/sdcard0/database.db. Amaze always crashed. I could open the file in sdcard0 with aSQLite Editor, so I guess it is sqlite.

**Comment by vishal0071** [comment]
Could you give me the logcat?

**Comment by jensMF** [comment]
Here it is:
build.board: smdk4210
build.bootloader: unknown
build.brand: samsung
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: i9100
build.display: omni_i9100-userdebug 4.4.4 KTU84P 515 test-keys
build.fingerprint: samsung/omni_i9100/i9100:4.4.4/KTU84P/515:userdebug/test-keys
build.hardware: smdk4210
build.host: devbox2.omnirom.org
build.id: KTU84P
build.manufacturer: Samsung
build.model: GT-I9100
build.product: omni_i9100
build.radio: unknown
build.serial: 000e786f46ff21
build.tags: test-keys
build.time: 1425523150000
build.type: userdebug
build.user: jenkins
version.codename: REL
version.incremental: 515
version.release: 4.4.4
version.sdk_int: 19

03-27 20:07:28.565 D/FAST App Search(2547): Starting com.amaze.filemanager (and incremented call count to 9)
03-27 20:07:28.565 I/ActivityManager(2242): START u0 {act=android.intent.action.MAIN flg=0x10000000 cmp=com.amaze.filemanager/.activities.MainActivity} from pid 2547
03-27 20:07:28.755 I/ActivityManager(2242): Start proc com.amaze.filemanager for activity com.amaze.filemanager/.activities.MainActivity: pid=8279 uid=10117 gids={50117, 1028, 1015, 1023}
03-27 20:07:28.975 I/dalvikvm(8279): Could not find method android.view.Window.setNavigationBarColor, referenced from method com.amaze.filemanager.activities.MainActivity.onCreate
03-27 20:07:28.985 I/dalvikvm(8279): Could not find method android.support.v7.widget.Toolbar.setElevation, referenced from method com.amaze.filemanager.activities.MainActivity.onPrepareOptionsMenu
03-27 20:07:29.250 I/dalvikvm(8279): Could not find method android.view.Window.setNavigationBarColor, referenced from method com.amaze.filemanager.fragments.Main$4.onCreateActionMode
03-27 20:07:29.250 I/dalvikvm(8279): Could not find method android.view.Window.setNavigationBarColor, referenced from method com.amaze.filemanager.fragments.Main$4.onDestroyActionMode
03-27 20:07:29.710 I/ActivityManager(2242): Displayed com.amaze.filemanager/.activities.MainActivity: +1s26ms
03-27 20:07:29.720 I/dalvikvm(8279): Could not find method android.view.View.setElevation, referenced from method com.amaze.filemanager.adapters.MyAdapter.getView
03-27 20:07:29.720 I/dalvikvm(8279): Could not find method android.view.View.setElevation, referenced from method com.amaze.filemanager.adapters.MyAdapter.getView
03-27 20:07:30.010 W/SQLiteConnectionPool(8279): A SQLiteConnection object for database '/data/data/com.amaze.filemanager/databases/Table1' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
03-27 20:07:30.010 W/SQLiteConnectionPool(8279): A SQLiteConnection object for database '/data/data/com.amaze.filemanager/databases/Table1' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
03-27 20:07:34.690 I/ActivityManager(2242): START u0 {cmp=com.amaze.filemanager/.activities.DbViewer (has extras)} from pid 8279
03-27 20:07:34.735 I/dalvikvm(8279): Could not find method android.view.Window.setStatusBarColor, referenced from method com.amaze.filemanager.activities.DbViewer.onCreate
03-27 20:07:34.805 E/AndroidRuntime(8279): Process: com.amaze.filemanager, PID: 8279
03-27 20:07:34.805 E/AndroidRuntime(8279): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.amaze.filemanager/com.amaze.filemanager.activities.DbViewer}: java.lang.NullPointerException
03-27 20:07:34.805 E/AndroidRuntime(8279): 	at com.amaze.filemanager.activities.DbViewer.onCreate(DbViewer.java:94)
03-27 20:07:34.820 W/ActivityManager(2242):   Force finishing activity com.amaze.filemanager/.activities.DbViewer
03-27 20:07:34.820 W/ActivityManager(2242):   Force finishing activity com.amaze.filemanager/.activities.MainActivity
03-27 20:07:35.330 W/ActivityManager(2242): Activity pause timeout for ActivityRecord{422589f8 u0 com.amaze.filemanager/.activities.DbViewer t14 f}
03-27 20:07:36.330 I/ActivityManager(2242): Process com.amaze.filemanager (pid 8279) has died.
03-27 20:07:36.335 I/WindowState(2242): WIN DEATH: Window{422d4fa8 u0 com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity}
03-27 20:07:37.265 D/FAST App Search(2547): Starting com.amaze.filemanager (and incremented call count to 10)
03-27 20:07:37.265 I/ActivityManager(2242): START u0 {act=android.intent.action.MAIN flg=0x10000000 cmp=com.amaze.filemanager/.activities.MainActivity} from pid 2547
03-27 20:07:37.525 I/ActivityManager(2242): Start proc com.amaze.filemanager for activity com.amaze.filemanager/.activities.MainActivity: pid=8332 uid=10117 gids={50117, 1028, 1015, 1023}
03-27 20:07:37.730 I/dalvikvm(8332): Could not find method android.view.Window.setNavigationBarColor, referenced from method com.amaze.filemanager.activities.MainActivity.onCreate
03-27 20:07:37.735 I/dalvikvm(8332): Could not find method android.support.v7.widget.Toolbar.setElevation, referenced from method com.amaze.filemanager.activities.MainActivity.onPrepareOptionsMenu
03-27 20:07:38.045 I/dalvikvm(8332): Could not find method android.view.Window.setNavigationBarColor, referenced from method com.amaze.filemanager.fragments.Main$4.onCreateActionMode
03-27 20:07:38.045 I/dalvikvm(8332): Could not find method android.view.Window.setNavigationBarColor, referenced from method com.amaze.filemanager.fragments.Main$4.onDestroyActionMode
03-27 20:07:38.465 I/dalvikvm(8332): Could not find method android.view.View.setElevation, referenced from method com.amaze.filemanager.adapters.MyAdapter.getView
03-27 20:07:38.465 I/dalvikvm(8332): Could not find method android.view.View.setElevation, referenced from method com.amaze.filemanager.adapters.MyAdapter.getView
03-27 20:07:38.475 I/ActivityManager(2242): Displayed com.amaze.filemanager/.activities.MainActivity: +1s18ms (total +3s766ms)
03-27 20:07:38.490 W/SQLiteConnectionPool(8332): A SQLiteConnection object for database '/data/data/com.amaze.filemanager/databases/Table1' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
03-27 20:07:43.295 I/ActivityManager(2242): START u0 {cmp=com.amaze.filemanager/.activities.DbViewer (has extras)} from pid 8332
03-27 20:07:43.350 I/dalvikvm(8332): Could not find method android.view.Window.setStatusBarColor, referenced from method com.amaze.filemanager.activities.DbViewer.onCreate
03-27 20:07:43.380 E/AndroidRuntime(8332): Process: com.amaze.filemanager, PID: 8332
03-27 20:07:43.380 E/AndroidRuntime(8332): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.amaze.filemanager/com.amaze.filemanager.activities.DbViewer}: java.lang.NullPointerException
03-27 20:07:43.380 E/AndroidRuntime(8332): 	at com.amaze.filemanager.activities.DbViewer.onCreate(DbViewer.java:94)
03-27 20:07:43.385 W/ActivityManager(2242):   Force finishing activity com.amaze.filemanager/.activities.DbViewer
03-27 20:07:43.390 W/ActivityManager(2242):   Force finishing activity com.amaze.filemanager/.activities.MainActivity
03-27 20:07:43.890 W/ActivityManager(2242): Activity pause timeout for ActivityRecord{4217db48 u0 com.amaze.filemanager/.activities.DbViewer t15 f}
03-27 20:07:45.335 I/ActivityManager(2242): Process com.amaze.filemanager (pid 8332) has died.
03-27 20:07:45.340 I/WindowState(2242): WIN DEATH: Window{42350240 u0 com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity}

**Comment by arpitkh96** [comment]
i hope this is fixed with latest commit

**Comment by jensMF** [comment]
This seems to be fixed. I could load all databases I tried. Even one with 7.1MB. Thanks a lot :-)
