### ISSUE TITLE
Indication of which pane I'm in

### ISSUE THREAD

**Issue by quite** [arpitkh96/AmazeFileManager#105]
Amaze has a left and a right pane, right. I would like to have some kind of visual indication of which one I'm currently in.

It is for example useful to know if I should swipe left or right next, in order to reach the other pane.

One possibility would be to let the path and used/free lines be both justified to the left side if I'm in the left pane, and justified right if I'm in the right.

**Comment by vishal0071** [comment]
Well, I'm thinking on using the fab to indicate the pane.
We're working on putting fab back on app bar and then, animate it's position on left or on right over the app bar as we slide across the pane.
Also, if suitable, making an arrow drawable in fab which denotes which side to slide (of course arrow will animate as we more across pane). Moreover, pressing on fab itself will change the pane. 
What say?
