### ISSUE TITLE
App Manager List is not updated after changing device orientation while LoadListTask is running

### ISSUE THREAD

**Issue by manhnt** [arpitkh96/AmazeFileManager#112]
When selecting App Manager form the drawer and then quickly, you change orientation of device in the middle of loading process, the list view of AppsList fragment will not be update after the async task finished and it shows an empty list screen.
This happens because when the orientation change, the fragment will be destroyed and a new fragment instance will be created. Meanwhile, the LoadListTask instance still holds references to member variables of the old fragment instance.
Calling setRetainInstance(true) for the fragment would work.
I could create a pull request if you want to fix this.

**Comment by vishal0071** [comment]
Nice catch, fixed (:
