### ISSUE TITLE
Add secure storage (enhancement)

### ISSUE THREAD

**Issue by realdmitchell** [arpitkh96/AmazeFileManager#117]
Hi
Apologies to create a new issue. When I meant Secure Storage I meant like "Create a local encfs based file system". Similar to   https://github.com/neurodroid/cryptonite  

I agree "entire android" is becoming encrypted, but it has some impact on performance[1]. Whether or not [1] is solved (by a better hardware, software); it would be _nice_ to have a local encrypted folder mounted via encfs.

Even if one has _fully_ encrypted phone, it would be useful to move confidential photos/PDF to this folder. Then when you show your Gallery/Pics/Docs to others these will not pop up. This applies to for example your CV, resume, or confidential docs.
1. http://arstechnica.com/gadgets/2015/03/google-quietly-backs-away-from-encrypting-new-lollipop-devices-by-default/

**Comment by JasperWeiss** [comment]
I'd like this too. simmilar to cyanogenmod's secure storage.

**Comment by vishal0071** [comment]
Looks like I finally got time and knowledge to implement something like this. Expect this in upcoming update.
Ps. As the saying goes, better late than never (:
