### ISSUE TITLE
Compile Problem in AIDE

### ISSUE THREAD

**Issue by scto** [arpitkh96/AmazeFileManager#125]
Is it possible to compile this project in AIDE? The gradle thing looks strange and ive a lot of errors

**Comment by arpitkh96** [comment]
You can't compile it with aide. It doesn't fully supports maven and gradle. The only way is to add all libraries as external jars.. Which isn't a good idea

**Comment by scto** [comment]
OK i thought AIDE 3.0.3 supports full gradle/maven

**Comment by arpitkh96** [comment]
Better ask it from aide developer team. This problem is not related to this project
