### ISSUE TITLE
Add the code style regulation file into the source control

### ISSUE THREAD

**Issue by amtlib-dot-dll** [arpitkh96/AmazeFileManager#141]
As long as this project is developed via Android Studio, it may be a good idea to share the regulation file out in order to have better uniformity in the code style.

This is the procedure:
Open `File` | `Settings` | `Editor` | `Code Style`
Set `Scheme` to `Project`
Add `.idea/codeStyleSettings.xml` into the source control

Thank you!

**Comment by amtlib-dot-dll** [comment]
And there should be one commit specially for styling those existing code to prevent readers from disturbed by differences between styled and non-styled lines when inspecting differences between commits. Thank you.

**Comment by arpitkh96** [comment]
code styling is just default .whats the need of this?
i am new to this . Shed some light
