### ISSUE TITLE
Create point-releases in github

### ISSUE THREAD

**Issue by utack** [arpitkh96/AmazeFileManager#147]
In Google Play store various 5.0.x releases are listed.
All the code seems to be on github too, but it would be very nice if you could mark the according versions as release on github, so they can be built for F-Droid.

**Comment by vishal0071** [comment]
You mean 2.0.x
F-droid flavour isn't stable right now I'm afraid. We'll make it stable and post another release for it very soon.

**Comment by utack** [comment]
Yes, 2.0.x, my bad.
Thanks for looking into it!

**Comment by vishal0071** [comment]
New build is up on f-droid (:
