### ISSUE TITLE
Unusable on Lollipop

### ISSUE THREAD

**Issue by pejakm** [arpitkh96/AmazeFileManager#161]
I'm using [BlissPop v3.5](http://forum.xda-developers.com/optimus-4x-hd/development/rom-blisspop-p880-t3042583) unofficial for LG Optimus 4x HD. Amaze version 2.0.5 from F-Droid repo.

Problem is that I can't move or copy into system partition, instead it displays some strange dialog to open a root folder (?). Am I missing something? I'll try to pull out some logs.

**Comment by pejakm** [comment]
Here's the screenshot of the dialog, it is Amaze's own dialog: 
http://www.dodaj.rs/f/1f/eJ/28WndlAU/nurkoedggggg.png

**Comment by arpitkh96** [comment]
The fixed was not updated for Fdroid.Sorry for inconvenience. All of these problems will be fixed in next update very soon
