### ISSUE TITLE
Enhancement: Add an easy way to read long file names

### ISSUE THREAD

**Issue by ikrase** [arpitkh96/AmazeFileManager#172]
While you can use the Properties page to view long file names, it's a bit inconvenient, especially if you are sorting through a number of files with the beginnings of the names similar, and it's pretty common for file names to get cut off. 

Would it be possible to add some sort of scrolling or hover or expand or something?

**Comment by arpitkh96** [comment]
The best way to access it for me is ,going to landscape mode,even properties are directly accessible from there

**Comment by vishal0071** [comment]
We will improve the properties tab as we get time.

**Comment by arpitkh96** [comment]
Properties are more easily accessible now
