### ISSUE TITLE
Feedback not working

### ISSUE THREAD

**Issue by felixwiemuth** [arpitkh96/AmazeFileManager#173]
The feature Settings -> Feedback does not work: Clicking causes the App to crash (closes, Android Dialog that it exited).

Version v2.0.5
Android 4.2.1

**Comment by arpitkh96** [comment]
you dont have any email app probably ,do you?

**Comment by felixwiemuth** [comment]
Yes, there was K9-Mail installed.
Anyway, in version 3.0.0 it works.

Am 15. August 2015 06:59:25 MESZ, schrieb arpit khurana <notifications@github.com>:
