### ISSUE TITLE
Home screen shortcut not working

### ISSUE THREAD

**Issue by felixwiemuth** [arpitkh96/AmazeFileManager#174]
One can create a shortcut on the home screen for a folder.
Clicking it starts the filemanager but
- when the filemanager was already running, only the last screen is shown
- when the filemanager was *not* running, it opens like when starting it over the normal app icon

and in both cases the selected directory is not opened.

Version v2.0.5
Android 4.2.1

**Comment by arpitkh96** [comment]
try latest version

**Comment by felixwiemuth** [comment]
Yes it seems to work in v3.0.0.
