### ISSUE TITLE
Files moved to a read only SMB directory are removed anyway!

### ISSUE THREAD

**Issue by airsynth** [arpitkh96/AmazeFileManager#176]

**Comment by airsynth** [comment]
Please fix this problem. I've lost pictures and I'm not willing to use Amaze until it's solved.

**Comment by okungnyo** [comment]
You tried to move files into a read-only directory, i.e. you tried to WRITE to a read-only directory, and you are blaming the app for not WRITING to a READ-ONLY directory?

WTF?

**Comment by arpitkh96** [comment]
Don't be offensive man. Trying to move to a non writable directory was his mistake but making him loose his files without warning is ours. I will try to fix it

**Comment by okungnyo** [comment]
Yea sorry

**Comment by arpitkh96** [comment]
Fixed

**Comment by airsynth** [comment]
Thank you very much!
