### ISSUE TITLE
Add FTP support

### ISSUE THREAD

**Issue by AnderRasoVazquez** [arpitkh96/AmazeFileManager#177]
I think it's a very useful function for a file manager.

Keep up the good work! =D

**Comment by thesuperdavis** [comment]
Support for SFTP would also be great

**Comment by JasperWeiss** [comment]
Yes, SFTP/SSH is something I'd like to see aswell.
It should make you select/generate ssh keys and have a checkbox for use of a password instead of a key. This way it encourages people to use (far more secure) keys.

**Comment by JasperWeiss** [comment]
Is this being worked on?
There is a great app on the play store called turbo ftp but I refuse to use it since it's not open-source and free as in free speech.

**Comment by JasperWeiss** [comment]
I'm having the feeling this project is abandoned..

**Comment by wb9688** [comment]
And SMB? And WebDAV?

**Comment by timofonic** [comment]
And the world?

**Comment by wb9688** [comment]
We can use jCIFS for SMB and JSch for SFTP...

**Comment by Zireael-N** [comment]
> I'm having the feeling this project is abandoned..

@JasperWeiss, well, this is a wrong feeling: [commits @ master](https://github.com/arpitkh96/AmazeFileManager/commits/master).

**Comment by chenzhiwei** [comment]
I think this feature can be delivered as a plugin. Just like Google Hangouts and Hangouts dialer.

**Comment by alanjames1987** [comment]
@Geyup I think the decision to add FTP support should be up to the developers and creating a GitHub issue like this one is a great way to have a discussion around the merits of the feature.

> I'm not trying to be rude, but I know what is needed,

You are not a developer of this project and thus should not think you know best. It's not an application that you control.

I personally like the idea of adding FTP support because I want a single application for managing my files, regardless of the way they are accessed, similar to what I have with Dolphin in Linux.

**Comment by Geyup** [comment]
Yes you are correct, it's up to the developer. I'm only an end-user wishing to keep the file manager light, and not added features that are not needed.

If there was no such thing as an FTP application and someone then wanted such a feature added into a file manager, I could really see the need, but since there are many such apps, I just wanted to share my two cents that I think it's pointless...

**Comment by xmikos** [comment]
@Geyup I wholeheartedly disagree. For me as a Linux user, SFTP support is elemental and much needed feature (similar to SMB network shares for Windows users, which are already supported). Every Linux file manager supports it, even old console-based `mc`. In todays world, network file access is as much needed as local file access and I don't want different apps for it. File manager should support it by itself.

**Comment by vishal0071** [comment]
I want to implement SFTP as I myself use Linux on my machine. But there's a big difference between wanting to, and actually implementing it. I will study about it as the time permits (:

**Comment by JasperWeiss** [comment]
IMHO implementing FTP is a disservice to the user in the end. Because it is so terribly insecure. It sends the username and password in plain text over the internet. Even with TLS I would not recommend it to anyone for any purpose (besides, perhaps, servers on a personal LAN)

SFTP would be great though, support for key files would be nice as well. To make things easier, you may want to look at the source code from ConnectBot.

**Comment by xmikos** [comment]
@JasperWeiss I agree, FTP should stay dead, it's horribly insecure zombie protocol :-) Only SFTP is relevant.

**Comment by Geyup** [comment]
Yes it's up to the developer, BUT there are already FTP/SFTP applications for Android!

A File Manager is NOT a File Transfter Protocol Application!

I'm a Linux/Unix Geek, let's keep things where they belong, and using the right tool for the job!

KISS :)

**Comment by JasperWeiss** [comment]
@Geyup Actually, there isn't a good SFTP client yet. At least not open-source. 

Second, a file manager app can be whatever you want it to be. The majority seems to want it to have built-in in SFTP support, including the developer.

Besides, I don't see your problem. If you want to use a separate app then go ahead. You'll barely notice it's there.

**Comment by xmikos** [comment]
@Geyup Amaze already supports SMB file transfer, adding SFTP therefore would not be against its concept. And I strongly disagree with you, file manager _should_ also support managing files over network. Most Linux file managers supports it (e.g. mc, Dolphin, Krusader, Nautilus, etc.).

**Comment by Geyup** [comment]
@xmikos 

```Dolphin, Krusader, Nautilus```

Not one of those file managers is as small and light weight as Amaze is.

If Amaze wanted to become a bloated File manager, like the above mentioned named, I could see this happening.

Anyhow, enough on the subject... :)

Cheers

**Comment by xmikos** [comment]
@Geyup You have conveniently omitted `mc`, which definitely is lightweight file manager (at least in my definition of "lightweight") and supports many network file transfer protocols. You have also convenietnly skipped part where I am pointing out that _Amaze already supports SMB file transfer_.

Your definition of _bloated_ seems to be really strange and you seems to be overly obsessed with KISS (and this is coming from guy who uses Arch Linux and do most stuff in terminal). You can fork Amaze and strip all features if you want it that way, it's opensource, that's your call. But you shouldn't try to force your opinions on everyone else, most people here seems to disagree with you.

**Comment by Geyup** [comment]
I'm not an Arch user, and sorry, I'm not trying to force my ideas on anyone.

Just simply saying, there are applications specifically designed to do the job is all, and no need to add in more features, when such applications exist.

Hope that's clear now.

**Comment by JasperWeiss** [comment]
@geyup Frankly, I haven't seen any well designed SFTP client on F-Droid.

We know very well what you're saying. We just don't necessarily agree with it.

**Comment by Geyup** [comment]
@JasperWeiss don't get me wrong, if there's nothing good, then that's another story...

**Comment by ka223** [comment]
can I connect to another FTP Server?
This would be very useful!

**Comment by chenzhiwei** [comment]
This feature was implemented in latest release, so I think it's time to close this thread.

**Comment by JavaJens** [comment]
@chenzhiwei @vishal0071 
Can you tell me where this is implemented? I only see that support for serving files via FTP was added, but not accessing remote files.
Or did I just miss understand the request?

**Comment by chenzhiwei** [comment]
@JavaJens Maybe I miss understand, I think this is request for an FTP server.

**Comment by vishal0071** [comment]
@JavaJens ftp client will be implemented sooner than later since we've added server support now.

**Comment by wb9688** [comment]
And SFTP?

**Comment by jahirfiquitiva** [comment]
Hi,

I'm not sure about how your implementation works, or its "purpose".

I really want the FTP and/or SFTP support, but the way Solid Explorer has it, which is being able to explorer files in another server, like for example the files of a website.

In Solid Explorer, you set the url, port, etc and it connects to those files.

I hope to see it in future updates.

**Comment by vishal0071** [comment]
@wb9688 @ghost yes, SFTP is being worked upon, expect a release soon. However ftp client might take a bit more time. Stay tuned.
@jahirfiquitiva as of now, you can't set port/path/username/password. But you gotta wait a bit, it is being worked upon.

**Comment by cirelli94** [comment]
@vishal0071 Hi, updates about SFTP support?

**Comment by flocke** [comment]
If FTP support is being worked on you should probably re-open this issue so people can easily see that it's already planed.
I was about to file a request for SFTP when I found this one ;)

**Comment by vishal0071** [comment]
Consult #498  for Client support

**Comment by ka223** [comment]
I can see SFTP at the cloud settings (beta version), can I connect to FTP as well?

**Comment by UnicornsOnLSD** [comment]
Sorry to revive an old issue, but adding support for regular FTP would be great. Some devices (such as the Nintendo Switch) don't have SFTP/SCP/SMB clients and I have to use another app to get files from my Switch.
