### ISSUE TITLE
Back-button malfunction

### ISSUE THREAD

**Issue by felixwiemuth** [arpitkh96/AmazeFileManager#181]
When opening a document (which opens another app), after hitting the back-butt, not only the document (other app) closes but also the filemanager, returning to the home screen.
Instead one shoudl return to the filemanager, at the same state where it was left.

Version v3.0.0
Android 4.2.1

**Comment by arpitkh96** [comment]
This is not the problem for me. You must check your phone. Probably your ram consumption is too high to handle both apps
