### ISSUE TITLE
Home directory feature: back-button closes instead of moving up in file hierarchy

### ISSUE THREAD

**Issue by felixwiemuth** [arpitkh96/AmazeFileManager#182]
When a home directory is set, regardless whether the filemanager was opened directly or via a different home screen shortcut, the following behaviour can be observed:

- Normally, in all directories, hitting the back-button causes navigation up in the file system hierarchy.
- When the path contains the home directory which was set, whenever reaching this directory, further hitting the back-button causes first the note that the app will close and at a second hit it closes.

I would expect to be able to navigate further up in the file hierarchy.
The option "Back navigation" does not change anything (Another hint: The description for this option is unclear, I don't know what it does).

Version v3.0.0
Android 4.2.1

**Comment by vishal0071** [comment]
We programmed it like this. That's why you set any directory as home, so that it doesn't go back in hierarchy after pressing back button.
If you want to go back from home, you can enable "Back navigation: option. It'll add a new list item on the top of the list for back navigation.

**Comment by felixwiemuth** [comment]
Ok. Is there any advantage with not being able to go further up from the home directory?
As mentioned above, I do not understand "Back navigation" - one still cannot navigate further up.
