### ISSUE TITLE
Can not get write access of external SD card on some device

### ISSUE THREAD

**Issue by wuliou** [arpitkh96/AmazeFileManager#183]
I use Amaze File Manager on my LG G Pro 2 (Android 5.0.1) to replace built-in file manager, when I first time copy files to external SD card, it will pop out an dialog asking for writing permission, so I can manipulate file on external SD card.  

But when I wanna use Amaze File Manger on my Acer A3-A30 tablet (Android 5.0.2, and had no built-in file manager), the dialog didn't pop out, so the file disappeared after copy, just like doing in Android 4.4 phones.  
I was wondering is this cause by the path difference of these two devices?  

LG G Pro 2:   
built-in SD: /storage/sdcard0/  
External SD: /storage/external_SD/  

Acer A3-A30:  
built-in SD: /storage/sdcard0/  
External SD: /storage/sdcard1/﻿

**Comment by arpitkh96** [comment]
I need your help solving this problem.
Try this apk and tell me the messages displayed on the screen(if any)
https://drive.google.com/file/d/0B7y8VGv6MgR5YzMwdTRCQ3pBa3c/view?usp=docslist_api

PS-don't spam the forums. I have seen your posts already at many places. Just be patient. Not always we are free to reply or help you

**Comment by arpitkh96** [comment]
File disappeared even while copying?

**Comment by wuliou** [comment]
Yes. the file even not showed up while copying.

**Comment by arpitkh96** [comment]
Try this. Same thing, tell me the messages
https://drive.google.com/file/d/0B7y8VGv6MgR5UmozdEFkVEhJMVU/view?usp=docslist_api

**Comment by wuliou** [comment]
The app crashed on launch.

**Comment by wuliou** [comment]
Just make a hardcoded fix to make external write access works on my device.
In `FileUtil` :
```Java
    @TargetApi(Build.VERSION_CODES.KITKAT)
    public static String getExtSdCardFolder(final File file,Context context) {
        //String[] extSdPaths = getExtSdCardPaths(context);
        String[] extSdPaths = {"/storage/sdcard1"}; //hardcoded for Acer A3-A30
        try {
            for (int i = 0; i < extSdPaths.length; i++) {
                if (file.getCanonicalPath().startsWith(extSdPaths[i])) {
                    return extSdPaths[i];
                }
            }
        }
        catch (IOException e) {
            return null;
        }
        return null;
    }
```
I will try to get a better to fix it...

**Comment by arpitkh96** [comment]
Thats not a good way to do it.It will mess up with other devices.Still if you can compile ,you can try the latest commit

**Comment by wuliou** [comment]
Yup it's not a good way, that will make the app crash on my phone. So I didn't push it.

**Comment by wuliou** [comment]
I accidentally close the issue, sorry.

**Comment by arpitkh96** [comment]
Try compiling with latest commits

**Comment by wuliou** [comment]
Sorry for late reply. I ran into compiling problem. I'm trying to solve it.

**Comment by arpitkh96** [comment]
Reopen if you still have problem
