### ISSUE TITLE
Failed to transfer files using SMB

### ISSUE THREAD

**Issue by malnvenshorn** [arpitkh96/AmazeFileManager#185]
Hi,

I tried to transfer files from my PC to my phone using SMB, but it doesn't work. Cut and paste the file creates an empty folder(!) on the sd card with the name of the file. If a file is copied an empty file with a size of 0 kb will be created and thats it.

Apart from that its a really nice app :-)

**Comment by malnvenshorn** [comment]
Why did you closed this ticket? Aren't you interested in reports of features that doesn't work=?

**Comment by okungnyo** [comment]
It works fine for me. Maybe stop using knockoff phones that cost $20.
