### ISSUE TITLE
Files not removed from MediaStore

### ISSUE THREAD

**Issue by ultraviolet7** [arpitkh96/AmazeFileManager#188]
When a file is deleted it is not removed from the MediaStore.  This impacts apps that use the MediaStore to obtain file lists.  For example, when deleting a folder of MP3s, Google Play Music will still list the files as though they are still present on the device.  Attempting to play the files will fail, as the files have been deleted.  Rebooting the device forces a re-scan by the MediaStore which will the remove the listing for the deleted files.
Rebooting the device can be mitigated by adding some code to the [FileUtil.java->deleteFile](https://github.com/arpitkh96/AmazeFileManager/blob/master/src/main/java/com/amaze/filemanager/utils/FileUtil.java#L175) method.  Something like the code below combined with re-organizing the existing code in the method to reduce the number of "return" statements should work but I have not tested this.  Maybe the code belongs in [MediaStoreUtil.java](https://github.com/arpitkh96/AmazeFileManager/blob/master/src/main/java/com/amaze/filemanager/utils/MediaStoreUtil.java).
```
context.getContentResolver().delete(MediaStore.Files.getContentUri("external"), MediaStore.MediaColumns.DATA + "=?", new String[] { file });
```

I see that [MediaStoreHack.java](https://github.com/arpitkh96/AmazeFileManager/blob/master/src/main/java/com/amaze/filemanager/utils/MediaStoreHack.java#L56) has something similar in the delete method but this goes to the extra effort of adding the entry to the database if it is missing to immediately delete it.

**Comment by arpitkh96** [comment]
For me file is being removed from mediastore too.What i am doing is scanning the parent directory of the file being deleted.Probably this took longer in your case

**Comment by ultraviolet7** [comment]
I am not sure what is going on in my case then.  I deleted a an album of MP3s from the music directory.  The music directory itself (the parent of the one that I deleted) had around 6 albums in it each with 8-12 MP3s per album.  After 24 hours the deleted files still showed up in Google Play Music.

**Comment by okungnyo** [comment]
I can confirm that after deleting a music file in Amaze, the music still shows up in every music app I have installed.

Only rebooting solved the problem.

It's not a dealbreaker, but it is annoying.

**Comment by okungnyo** [comment]
A quick Google search, maybe a possible solution?:

http://developer.samsung.com/forum/board/thread/view.do?boardName=General&messageId=276165

**Comment by arpitkh96** [comment]
I will see this. Currently busy implementing drive client

**Comment by okungnyo** [comment]
Please, please, please make the Drive component a separate plug-in.

As I said in the Google+ Community:

What I love about Amaze is that it is a no-nonsense, strictly local-only file manager.

I hate how all the other file managers try to do everything (cough Solid Explorer), and are so confusing to use.

It's like the thousand todo apps on the Play Store that make you sign up for an account with their dubious websites to use their app, you know? It's like, no thanks, I'll use another todo app that doesn't plan on selling all my personal information.

Please keep Amaze an offline, local-only app.

I will gladly even pay for such a feature. Amaze is too amazing to be ruined by "cloud" integration.﻿

**Comment by arpitkh96** [comment]
Well I gave this a try earlier but didn't find it worth . actually I didn't understand the concept. What's the use of such plugins when you have to add codes for them in main app too.I tried doing that with(external) service. You can give me a better idea. I am still a learner so happy to accept suggestions.

**Comment by okungnyo** [comment]
Could you maintain two separate branches of the app? Like have Amaze as it is now, and launch Amaze Cloud Edition as a separate Play Store entry or something.

**Comment by arpitkh96** [comment]
I would consider plugin thing better if possible

**Comment by arpitkh96** [comment]
Fixed

**Comment by okungnyo** [comment]
Awesome, is there an estimated release date for the new version?

**Comment by arpitkh96** [comment]
it will take time .As i am working on implementing drive plugin as well as stabilizing app.Moreover i am working alone so it will definitely take longer

**Comment by arpitkh96** [comment]
if you are eager you can compile yourself.

**Comment by okungnyo** [comment]
Thanks, I will wait for the Play Store version!
