### ISSUE TITLE
Root file management in Android 6.0

### ISSUE THREAD

**Issue by mindcombatant** [arpitkh96/AmazeFileManager#192]
with Amaze 3.0.1 installed from f-droid, using root with SuperSU 2.50 and the proper boot.img for my Nexus 6, running android 6.0, unable to delete files and folders within /system directory, it works normally, and asks if i want to delete the files, but when i click yes, it says "deleting" then "done" but the file is still there.

logs:
```
10-09 19:30:13.977 14434 14434 W com.amaze.filemanager: type=1400 audit(0.0:2648): avc: denied { getattr } for comm=4173796E635461736B202333 path="/data/tombstones" dev="dm-0" ino=269281 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:tombstone_data_file:s0 tclass=dir permissive=0
10-09 19:30:13.977 14434 14434 W com.amaze.filemanager: type=1400 audit(0.0:2649): avc: denied { getattr } for comm=4173796E635461736B202333 path="/data/tombstones" dev="dm-0" ino=269281 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:tombstone_data_file:s0 tclass=dir permissive=0
10-09 19:30:14.787 14448 14448 W app_process32_o: type=1400 audit(0.0:2650): avc: denied { write } for name="system@framework@boot.art" dev="dm-0" ino=791524 scontext=u:r:shell:s0 tcontext=u:object_r:dalvikcache_data_file:s0 tclass=file permissive=0
10-09 19:30:14.787 14458 14458 W app_process32_o: type=1400 audit(0.0:2651): avc: denied { write } for name="system@framework@boot.art" dev="dm-0" ino=791524 scontext=u:r:shell:s0 tcontext=u:object_r:dalvikcache_data_file:s0 tclass=file permissive=0
```

**Comment by arpitkh96** [comment]
Are you using SuperSU? If yes you need to change it to MY root. There are no such changes in marshmallow to make this app not working

**Comment by bpeck1101** [comment]
what do you mean by MY root? I am happy to finally have an open source android file manager, but need to be able to delete files under /system.

**Comment by mindcombatant** [comment]
solved, the ultimate issue i discovered was with busybox, couldn't install it to /system as there was no space there, and couldn't delete files in /system without it. perhaps a way to select where busybox binaries are from settings would be nice, though that's a bit outside the scope of this project, i feel.

**Comment by bpeck1101** [comment]
so how do I fix this? or do I have to wait for the next version?
