### ISSUE TITLE
Same apks in amaze's other list

### ISSUE THREAD

**Issue by keesj** [arpitkh96/AmazeFileManager#196]
1.Launch Amaze-> Tap "+">Choose "File"> Input words(eg: test)>Tap create
2.Tap new created file-> Choose other-> Check all apk in list
【Actual Result】
Some Same apks in amaze's other list as 
![10 19_amaze_actual](https://cloud.githubusercontent.com/assets/57112/11114894/34c0a068-8928-11e5-9fbe-4dc6ad993683.png)

**Comment by arpitkh96** [comment]
thats not a bug.Same apks does not mean same task they intend to do.One app can open that file in multiple ways.The type of file you made is not recognised by the file manager thats why all the options possible are shown
