### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by wb9688** [arpitkh96/AmazeFileManager#199]
I tried to compile it, but I got 80 errors. I'm using Gradle 2.2.1 and Java 1.8.0_60 on Windows 10.

**Comment by vishal0071** [comment]
What kind of errors. Post the error log.

**Comment by rameshkru** [comment]
@vishal0071 When I compiled it, I get the following in message box.
Information:Gradle tasks [:assembleFdroidDebug]
signing.properties not found
Warning:Dependency commons-logging:commons-logging:1.1.1 is ignored for playDebug as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages
Warning:Dependency commons-logging:commons-logging:1.1.1 is ignored for playRelease as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages
Warning:Dependency commons-logging:commons-logging:1.1.1 is ignored for fdroidDebug as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages
Warning:Dependency commons-logging:commons-logging:1.1.1 is ignored for fdroidRelease as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages
:preBuild UP-TO-DATE
:preFdroidDebugBuild UP-TO-DATE
:checkFdroidDebugManifest
:preFdroidReleaseBuild UP-TO-DATE
:prePlayDebugBuild UP-TO-DATE
:prePlayReleaseBuild UP-TO-DATE
:libs:StickyHeadersRecyclerView:compileLint
:libs:StickyHeadersRecyclerView:copyReleaseLint UP-TO-DATE
:libs:StickyHeadersRecyclerView:preBuild UP-TO-DATE
:libs:StickyHeadersRecyclerView:preReleaseBuild UP-TO-DATE
:libs:StickyHeadersRecyclerView:checkReleaseManifest
:libs:StickyHeadersRecyclerView:preDebugAndroidTestBuild UP-TO-DATE
:libs:StickyHeadersRecyclerView:preDebugBuild UP-TO-DATE
:libs:StickyHeadersRecyclerView:preDebugUnitTestBuild UP-TO-DATE
:libs:StickyHeadersRecyclerView:preReleaseUnitTestBuild UP-TO-DATE
:libs:StickyHeadersRecyclerView:prepareComAndroidSupportRecyclerviewV72210Library UP-TO-DATE
:libs:StickyHeadersRecyclerView:prepareComAndroidSupportSupportV42210Library UP-TO-DATE
:libs:StickyHeadersRecyclerView:prepareReleaseDependencies
:libs:StickyHeadersRecyclerView:compileReleaseAidl UP-TO-DATE
:libs:StickyHeadersRecyclerView:compileReleaseRenderscript UP-TO-DATE
:libs:StickyHeadersRecyclerView:generateReleaseBuildConfig UP-TO-DATE
:libs:StickyHeadersRecyclerView:generateReleaseAssets UP-TO-DATE
:libs:StickyHeadersRecyclerView:mergeReleaseAssets UP-TO-DATE
:libs:StickyHeadersRecyclerView:generateReleaseResValues UP-TO-DATE
:libs:StickyHeadersRecyclerView:generateReleaseResources UP-TO-DATE
:libs:StickyHeadersRecyclerView:mergeReleaseResources UP-TO-DATE
:libs:StickyHeadersRecyclerView:processReleaseManifest UP-TO-DATE
:libs:StickyHeadersRecyclerView:processReleaseResources UP-TO-DATE
:libs:StickyHeadersRecyclerView:generateReleaseSources UP-TO-DATE
:libs:StickyHeadersRecyclerView:processReleaseJavaRes UP-TO-DATE
:libs:StickyHeadersRecyclerView:compileReleaseJava UP-TO-DATE
:libs:StickyHeadersRecyclerView:extractReleaseAnnotations UP-TO-DATE
:libs:StickyHeadersRecyclerView:mergeReleaseProguardFiles UP-TO-DATE
:libs:StickyHeadersRecyclerView:packageReleaseJar UP-TO-DATE
:libs:StickyHeadersRecyclerView:compileReleaseNdk UP-TO-DATE
:libs:StickyHeadersRecyclerView:packageReleaseJniLibs UP-TO-DATE
:libs:StickyHeadersRecyclerView:packageReleaseLocalJar UP-TO-DATE
:libs:StickyHeadersRecyclerView:packageReleaseRenderscript UP-TO-DATE
:libs:StickyHeadersRecyclerView:packageReleaseResources UP-TO-DATE
:libs:StickyHeadersRecyclerView:bundleRelease UP-TO-DATE
:prepareAmazeFileManagerMasterLibsStickyHeadersRecyclerViewUnspecifiedLibrary UP-TO-DATE
:prepareComAndroidSupportAppcompatV72311Library UP-TO-DATE
:prepareComAndroidSupportCardviewV72310Library UP-TO-DATE
:prepareComAndroidSupportRecyclerviewV72311Library UP-TO-DATE
:prepareComAndroidSupportSupportV42311Library UP-TO-DATE
:prepareComGithubAfollestadMaterialDialogsCore0850Library UP-TO-DATE
:prepareComGithubClansFab161Library UP-TO-DATE
:prepareMeZhanghaiAndroidMaterialprogressbarLibrary114Library UP-TO-DATE
:prepareOrgSufficientlysecureDonations23Library UP-TO-DATE
:prepareFdroidDebugDependencies
:compileFdroidDebugAidl UP-TO-DATE
:compileFdroidDebugRenderscript UP-TO-DATE
:generateFdroidDebugBuildConfig UP-TO-DATE
:generateFdroidDebugAssets UP-TO-DATE
:mergeFdroidDebugAssets UP-TO-DATE
:generateFdroidDebugResValues UP-TO-DATE
:generateFdroidDebugResources UP-TO-DATE
:mergeFdroidDebugResources UP-TO-DATE
:processFdroidDebugManifest UP-TO-DATE
:processFdroidDebugResources UP-TO-DATE
:generateFdroidDebugSources UP-TO-DATE
:processFdroidDebugJavaRes UP-TO-DATE
:compileFdroidDebugJava
C:\Users\ramesh\Downloads\AmazeFileManager-master\src\main\java\com\amaze\filemanager\utils\Futils.java
Error:(486, 32) error: cannot find symbol variable mainActivityHelper
Error:(849, 26) error: cannot find symbol variable mainActivityHelper
Error:(913, 22) error: cannot find symbol variable mainActivityHelper
Error:(1002, 90) error: cannot find symbol variable HISTORY
Error:(1002, 56) error: cannot find symbol variable history
Error:(1013, 62) error: cannot find symbol variable HISTORY
Error:(1013, 32) error: cannot find symbol variable history
Error:(1020, 126) error: cannot find symbol variable history
Error:(1035, 92) error: cannot find symbol variable HIDDEN
Error:(1035, 58) error: cannot find symbol variable history
Error:(1043, 126) error: cannot find symbol variable history
C:\Users\ramesh\Downloads\AmazeFileManager-master\src\fdroid\java\com\amaze\filemanager\activities\MainActivity.java
Error:(113, 35) error: cannot find symbol class Shortcuts
Error:(155, 5) error: cannot find symbol class Shortcuts
Error:(418, 17) error: cannot find symbol class Shortcuts
Error:(419, 23) error: cannot find symbol class Shortcuts
Error:(1052, 30) error: cannot find symbol variable current
Error:(1184, 49) error: cannot find symbol variable islist
Error:(1191, 33) error: cannot find symbol variable current
Error:(1226, 39) error: cannot find symbol variable current
Error:(1256, 40) error: cannot find symbol variable current
Error:(1305, 32) error: cannot find symbol variable current
Error:(1483, 29) error: constructor MoveFiles in class MoveFiles cannot be applied to given types;
required: ArrayList<File>,ArrayList<String>,Main,Context
found: ArrayList<File>,Main,FragmentActivity
reason: actual and formal argument lists differ in length
Error:(1767, 21) error: constructor MoveFiles in class MoveFiles cannot be applied to given types;
required: ArrayList<File>,ArrayList<String>,Main,Context
found: ArrayList<File>,Main,FragmentActivity
reason: actual and formal argument lists differ in length
Error:(1861, 33) error: cannot find symbol variable current
Error:(1901, 56) error: incompatible types: boolean cannot be converted to int
Error:(1917, 67) error: incompatible types: boolean cannot be converted to int
Error:(1936, 66) error: incompatible types: boolean cannot be converted to int
Error:(1937, 66) error: incompatible types: boolean cannot be converted to int
Error:(2266, 72) error: incompatible types: boolean cannot be converted to int
Error:(2268, 40) error: cannot find symbol method loadCustomList(String,boolean)
Error:(2466, 27) error: cannot find symbol method loadCustomList(String,boolean)
C:\Users\ramesh\Downloads\AmazeFileManager-master\src\main\java\com\amaze\filemanager\fragments\Main.java
Error:(441, 34) error: cannot find symbol variable mainActivityHelper
Error:(858, 81) error: cannot find symbol variable HISTORY
Error:(858, 34) error: cannot find symbol variable history
Error:(925, 81) error: cannot find symbol variable HISTORY
Error:(925, 34) error: cannot find symbol variable history
Error:(984, 35) error: cannot find symbol variable gridfiles
Error:(986, 25) error: cannot find symbol variable listfiles
Error:(1023, 71) error: cannot find symbol variable HISTORY
Error:(1023, 34) error: cannot find symbol variable history
Error:(1136, 34) error: cannot find symbol variable mainActivityHelper
Error:(1138, 34) error: cannot find symbol variable mainActivityHelper
Error:(1314, 31) error: cannot find symbol variable hiddenfiles
Error:(1367, 22) error: cannot find symbol variable hiddenfiles
Error:(1367, 82) error: cannot find symbol variable HIDDEN
Error:(1367, 50) error: cannot find symbol variable history
Error:(1371, 62) error: cannot find symbol variable HIDDEN
Error:(1371, 22) error: cannot find symbol variable history
Error:(1372, 22) error: cannot find symbol variable hiddenfiles
Error:(1372, 82) error: cannot find symbol variable HIDDEN
Error:(1372, 50) error: cannot find symbol variable history
Error:(1377, 34) error: cannot find symbol variable mainActivityHelper
C:\Users\ramesh\Downloads\AmazeFileManager-master\src\main\java\com\amaze\filemanager\adapters\DrawerAdapter.java
Error:(120, 22) error: method selectItem in class MainActivity cannot be applied to given types;
required: int,boolean
found: int
reason: actual and formal argument lists differ in length
Error:(133, 30) error: cannot find symbol variable mainActivityHelper
Error:(136, 26) error: cannot find symbol method renameBookmark(String,String)
C:\Users\ramesh\Downloads\AmazeFileManager-master\src\main\java\com\amaze\filemanager\adapters\Recycleradapter.java
Error:(632, 51) error: cannot find symbol variable mainActivityHelper
Error:(636, 124) error: cannot find symbol variable BOOKS
Error:(636, 55) error: cannot find symbol variable grid
C:\Users\ramesh\Downloads\AmazeFileManager-master\src\main\java\com\amaze\filemanager\services\asynctasks\LoadList.java
Error:(284, 92) error: cannot find symbol variable HISTORY
Error:(284, 57) error: cannot find symbol variable history
Error:incompatible types: ArrayList<String> cannot be converted to ArrayList<String[]>
C:\Users\ramesh\Downloads\AmazeFileManager-master\src\main\java\com\amaze\filemanager\utils\MainActivityHelper.java
Error:(65, 37) error: adapter is not public in MainActivity; cannot be accessed from outside package
Error:(65, 128) error: Sp is not public in MainActivity; cannot be accessed from outside package
Error:(66, 74) error: adapter is not public in MainActivity; cannot be accessed from outside package
Error:(111, 29) error: cannot find symbol method bindDrive()
Error:(196, 25) error: oppathe is not public in MainActivity; cannot be accessed from outside package
Error:(197, 25) error: oppathe1 is not public in MainActivity; cannot be accessed from outside package
Error:(198, 25) error: operation is not public in MainActivity; cannot be accessed from outside package
Error:(198, 50) error: RENAME is not public in MainActivity; cannot be accessed from outside package
Error:(243, 25) error: oppathe is not public in MainActivity; cannot be accessed from outside package
Error:(244, 25) error: operation is not public in MainActivity; cannot be accessed from outside package
Error:(244, 50) error: COMPRESS is not public in MainActivity; cannot be accessed from outside package
Error:(245, 25) error: oparrayList is not public in MainActivity; cannot be accessed from outside package
Error:(345, 45) error: no suitable method found for add(String[])
method AbstractCollection.add(String) is not applicable
(argument mismatch; String[] cannot be converted to String)
method AbstractList.add(String) is not applicable
(argument mismatch; String[] cannot be converted to String)
method ArrayList.add(String) is not applicable
(argument mismatch; String[] cannot be converted to String)
Error:(347, 75) error: cannot find symbol variable SMB
Error:(347, 37) error: cannot find symbol variable grid
Error:(355, 76) error: cannot find symbol variable SMB
Error:(355, 41) error: cannot find symbol variable grid
Error:(357, 45) error: no suitable method found for add(String[])
method AbstractCollection.add(String) is not applicable
(argument mismatch; String[] cannot be converted to String)
method AbstractList.add(String) is not applicable
(argument mismatch; String[] cannot be converted to String)
method ArrayList.add(String) is not applicable
(argument mismatch; String[] cannot be converted to String)
Error:(358, 36) error: no suitable method found for sort(ArrayList<String>,BookSorter)
method Collections.<T#1>sort(List<T#1>) is not applicable
(cannot infer type-variable(s) T#1
(actual and formal argument lists differ in length))
method Collections.<T#2>sort(List<T#2>,Comparator<? super T#2>) is not applicable
(inferred type does not conform to upper bound(s)
inferred: String
upper bound(s): String[],Object)
where T#1,T#2 are type-variables:
T#1 extends Comparable<? super T#1> declared in method <T#1>sort(List<T#1>)
T#2 extends Object declared in method <T#2>sort(List<T#2>,Comparator<? super T#2>)
Error:(360, 75) error: cannot find symbol variable SMB
Error:(360, 37) error: cannot find symbol variable grid
Error:(374, 68) error: cannot find symbol variable SMB
Error:(374, 33) error: cannot find symbol variable grid
Error:(408, 29) error: oppathe is not public in MainActivity; cannot be accessed from outside package
Error:(409, 29) error: operation is not public in MainActivity; cannot be accessed from outside package
Error:(409, 54) error: NEW_FILE is not public in MainActivity; cannot be accessed from outside package
Error:(442, 29) error: oppathe is not public in MainActivity; cannot be accessed from outside package
Error:(443, 29) error: operation is not public in MainActivity; cannot be accessed from outside package
Error:(443, 54) error: NEW_FOLDER is not public in MainActivity; cannot be accessed from outside package
Error:(466, 25) error: oparrayList is not public in MainActivity; cannot be accessed from outside package
Error:(467, 25) error: operation is not public in MainActivity; cannot be accessed from outside package
Error:(467, 50) error: DELETE is not public in MainActivity; cannot be accessed from outside package
Error:(475, 25) error: oppathe is not public in MainActivity; cannot be accessed from outside package
Error:(476, 25) error: operation is not public in MainActivity; cannot be accessed from outside package
Error:(476, 50) error: EXTRACT is not public in MainActivity; cannot be accessed from outside package
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
Error:Execution failed for task ':compileFdroidDebugJava'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED
Information:Total time: 5.118 secs
Information:97 errors
Information:4 warnings
Information:See complete output in console

**Comment by arpitkh96** [comment]
Fdroid variant is not yet updated. Just switch to play variant and errors will be gone.

**Comment by rameshkru** [comment]
@arpitkh96 How to switch to play variant? Is it downloading from Google play? But it's not up to date.

**Comment by arpitkh96** [comment]
There's an option to change build variant at lower extreme left side of Android studio. But those options to change build variant will only show up after gradle sync completes

**Comment by rameshkru** [comment]
@arpitkh96 Tried it but now getting the following error.
C:\Users\ramesh\Downloads\AmazeFileManager\src\play\java\com\amaze\filemanager\activities\MainActivity.java
Error:(120, 35) error: cannot find symbol class StorageUtils
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Error:Execution failed for task ':compilePlayDebugJava'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED
Information:Total time: 1.753 secs
Information:2 errors
Information:4 warnings

**Comment by arpitkh96** [comment]
Just remove the import .I just can't explain you everything. You need fix these problems yourself

**Comment by rameshkru** [comment]
@arpitkh96 sorry for that.. New to it.. No more queries.. Thank you so much :)
