### ISSUE TITLE
Errors writing to external SD card are not reported

### ISSUE THREAD

**Issue by strk** [arpitkh96/AmazeFileManager#200]
I'm trying to create a file on the external SD card but it fails silently.
Using a different tool reports an error instead.

Why it fails is still unknown to me, anyway this ticket is to request the failure is  at least signalled.
The bug was found on a Samsung S III neo running Amaze 3.0.1

**Comment by wb9688** [comment]
Which Android version are you using? There is a bug in some Android versions...

**Comment by strk** [comment]
Android version 4.4.2

**Comment by strk** [comment]
In any case, "OI File Manager" does report an error, on the same system:
https://github.com/openintents/filemanager

**Comment by vishal0071** [comment]
KitKat does not allow third party apps to perform write operations on SD Card.

**Comment by vishal0071** [comment]
But I do agree, It should not fail *silently*.... Will see to it.

**Comment by benjaminoakes** [comment]
I've seen the same (or similar) issue when attempting to write to a FAT32 formatted USB stick connected with a USB On The Go cable. However, OI File Manager can write to the USB drive just fine. That's what I'm using as a workaround, but I much prefer Amaze. Using `touch` to create a file in `/storage/usbdisk/` in Termux gave a permission denied error. 

I'm using a Moto G running Android 5.1. Amaze version 3.0.0, OI File Manager version 2.0.5.

**Comment by arpitkh96** [comment]
@benjaminoakes i have tested usb otg on moto g stock 5.1 myself. It works for me.Please try v3.0.1 . If it still doesnt works then help me fix it.
PS -BTW unsuccessful copying operations will be reported now and files wont be lost while moving if unsuccessful.

**Comment by strk** [comment]
3.0.1 is still silent while failing to "create file" on extSdCard
on a Samsung Galaxy S3 Neo (GT-I9301I) with Android 4.4.2.

**Comment by arpitkh96** [comment]
First thing, I said "copy" operations , second I didn't provided any update. Keep calm man.I am working

**Comment by strk** [comment]
why closed ? did you provide the update ? if so, in which commit ?

**Comment by arpitkh96** [comment]
update will take few more days.
recent 5-6 commits changed just whole structure. 
for copy-https://github.com/arpitkh96/AmazeFileManager/commit/7b85ae59fede845c5268bbd2cbc5d7a4deffd724
if you are more interested you can dig deep :P.
Meanwhile you can sign up for beta testing on g+.I will be uploading an apk there very soon

**Comment by benjaminoakes** [comment]
Is version v3.0.1 mislabeled as v3.0.0 in the "about" section of settings?  (Google Play reports v3.0.1 but "about" reports v3.0.0.)  In any case, the up-to-date version I have installed from Google Play still exhibits this problem.
