### ISSUE TITLE
Landscape view has space reserved for sidebar but sidebar is not always open.

### ISSUE THREAD

**Issue by CalcProgrammer1** [arpitkh96/AmazeFileManager#204]
I'm using the latest version from F-droid.  When I rotate to landscape, as I prefer to do for apps involving lots of content on screen at once, it has a large white box at the side the size of the sidebar.  Hitting the menu brings out the sidebar but it goes away once I select something.  I expect either the sidebar to always be out in landscape (like ES file explorer) or for the content view to be full screen as it is in portrait.

**Comment by arpitkh96** [comment]
Will be fixed soon

**Comment by polyzen** [comment]
Shouldn't this be closed after it's resolved (ie. after code is committed or after the solution is verified)?

**Comment by arpitkh96** [comment]
Can you compile? If yes? Then I will consider reopening surely. Otherwise I believe I have made a fix already (not updated on fdroid).

**Comment by polyzen** [comment]
Oh, the fix is already made. I had tried building for android once.. ;p

**Comment by arpitkh96** [comment]
Well that explains .I believe there's no need to keep the issue opened

**Comment by polyzen** [comment]
Right.
