### ISSUE TITLE
status bar area of the screen does not display correctly when the system had no status bar

### ISSUE THREAD

**Issue by DePingus** [arpitkh96/AmazeFileManager#205]
I have an Amazon Fire Phone OS 4.6.5 with the status bar hidden. When I select an item the would-be status bar background appears over the top half of the app icons. 

Here is a screen cap:
http://i.imgur.com/5X6m6fD.jpg

**Comment by arpitkh96** [comment]
Test beta version from here https://plus.google.com/communities/113997576965363268101
