### ISSUE TITLE
sdcard shortcut doesn't work on Marshmallow 6.0.1

### ISSUE THREAD

**Issue by Primokorn** [arpitkh96/AmazeFileManager#206]
Hi,
The Sdcard shortcut in the drawer doesn't seem to work.
Nexus 5 - Android 6.0.1.

The other shortcuts like Download are working fine though.

Thank you.

![unnamed](https://cloud.githubusercontent.com/assets/5938828/12165060/cedd6604-b51a-11e5-9e3e-f7475d5556e8.png)

**Comment by martykan** [comment]
I have the same problem. Also external storage (sd cards, OTG) doesn't work at all.

**Comment by arpitkh96** [comment]
It's fixed. Update will be available soon

**Comment by Primokorn** [comment]
Thanks mate!
