### ISSUE TITLE
Add warning upon deleting non-empty folder

### ISSUE THREAD

**Issue by pejakm** [arpitkh96/AmazeFileManager#207]
Over time empty, unused folders appear, and I tend to delete them every once in a while. Yesterday I've accidentally deleted my Pictures folder (luckily, I had a backup). Please add a warning upon deleting non empty folders.

Thanks.

**Comment by arpitkh96** [comment]
There's already a warning before deletion for every file

**Comment by pejakm** [comment]
Yes, you are right. :( Sorry, closing this.
