### ISSUE TITLE
Moving files to SD card deletes files under KitKat

### ISSUE THREAD

**Issue by bovergaauw** [arpitkh96/AmazeFileManager#208]
I tried to move several files to the external SD card on my Samsung Tab 3, having forgotten that KitKat does not allow me to use the SD card as general storage anymore. Much to my surprise, the one folder I tried to copy got created, but remained empty, while the original files on the device were deleted! I tried the same with just a file, with the same result: The file on the internal storage got deleted, but was not created on the SD card. In both cases the operation did not result in any warning or error message.

**Comment by bovergaauw** [comment]
I just noticed this issue is mentioned in the readme file.

**Comment by CreamyCookie** [comment]
I have no idea how Amaze works, but shouldn't this be easy to fix or at least provide a workaround / warning? Just make a copy and only delete files in the source directory when the files have been successfully copied.
