### ISSUE TITLE
Long Click on File or Folder removes the FAB and it never appears again

### ISSUE THREAD

**Issue by sidaknanda** [arpitkh96/AmazeFileManager#216]
I guess its not the expected behavior so opened an issue. Correct me if I got it wrong.

**Comment by vishal0071** [comment]
You're right. Will be fixed.

**Comment by sidaknanda** [comment]
I have found in the code. Can you tell me what is the expected behavior ?
on long clicking FAB (i.e. selecting any folder) it should disappear and come back when user has deselected the folder
Or it should appear all the time whether user has selected or deselected any folder ?

**Comment by vishal0071** [comment]
It should disappear on item selection and appear once selection is removed.

**Comment by sidaknanda** [comment]
Fixed the issue :+1:

**Comment by sidaknanda** [comment]
Also when I took a clone of your code, it crashed at start every time. Reason was a resource (android.R.interpolator.fast_out_slow_in) not found in getFastOutSlowInInterpolator method of AnimUtils Class. So have to change it to android's anim resource (android.R.anim.overshoot_interpolator). So made this change and fixed this issue.

**Comment by vishal0071** [comment]
Great! Make a pull request so that I can see your changes.
