### ISSUE TITLE
sd Card shortcut in side drawer dont show sdcard content

### ISSUE THREAD

**Issue by Poeschl** [arpitkh96/AmazeFileManager#218]
When I select the top shortcut for the sdcard in the navigation drawer it directs me to '/sdcard'. But there is only one file named sdcard (I guess its a symbolic link).
On the terminal the '/sdcard' path it directs to the sdcard.

I experienced this on a rooted Nexus 5X with API 23.

**Comment by vishal0071** [comment]
The problem is known on some devices on Marshmallow. You can temporarily disable root in amaze settings to access sdcard.
