### ISSUE TITLE
which rooting software you will suggest

### ISSUE THREAD

**Issue by zaxebo1** [arpitkh96/AmazeFileManager#219]
There are many rooting softwares available. Concern is that some of them may contain some kind of trojan or backdoors. So can you suggest 'one or  two or three' rank trust worthy rooting softwares recommended by you, so that this Amaze File Manager can be used in rooted mode.

**Comment by polyzen** [comment]
I really doubt this is the place to ask this question, but this seems to be the best bet: http://forum.xda-developers.com/android/software-hacking/wip-selinux-capable-superuser-t3216394

**Comment by zaxebo1** [comment]
@polyzen:
justification about asking this question here:
 I asked because the Amaze developers have mentioned amaze filemanager as root explorer too. In that case, for a newbie , there are lots and lots and lots of article on internet which recommend one or other rooting software.
 I was just asking the rooting software recommendation of this AmazeFileManager developers, that which one rooting software they would recommend/ or they themselves use; so that I can be rest assured or atleast put more trust  about the genuineness(no malware etc) of that particular rooting software/softwares. 

-----
apart from this, your link is very good  :+1:  :-)   , because that softare is open source. I always prefer FOSS solutions, if available.

---

But I would still again request the amaze developers for their recommendations - for a trusted opensource "rooting software category"

**Comment by vishal0071** [comment]
@zaxebo1
You can either use SuperSU by chainfire or the one implemented by the cyanogemod. They both are reliable source, however you can go for the open source link as suggested by @polyzen.

**Comment by vishal0071** [comment]
@zaxebo1
You can either use SuperSU by chainfire or the one implemented by the cyanogemod. They both are reliable source, however you can go for the open source link as suggested by @polyzen.

**Comment by vishal0071** [comment]
@zaxebo1
You can either use SuperSU by chainfire or the one implemented by the cyanogemod. They both are reliable source, however you can go for the open source link as suggested by @polyzen.

**Comment by vishal0071** [comment]
@zaxebo1
You can either use SuperSU by chainfire or the one implemented by the cyanogemod. They both are reliable source, however you can go for the open source link as suggested by @polyzen.

**Comment by vishal0071** [comment]
@zaxebo1
You can either use SuperSU by chainfire or the one implemented by the cyanogemod. They both are reliable source, however you can go for the open source link as suggested by @polyzen.

**Comment by vishal0071** [comment]
@zaxebo1
You can either use SuperSU by chainfire or the one implemented by the cyanogemod. They both are reliable source, however you can go for the open source link as suggested by @polyzen.

**Comment by vishal0071** [comment]
@zaxebo1
You can either use SuperSU by chainfire or the one implemented by the cyanogemod. They both are reliable source, however you can go for the open source link as suggested by @polyzen.

**Comment by vishal0071** [comment]
@zaxebo1
You can either use SuperSU by chainfire or the one implemented by the cyanogemod. They both are reliable source, however you can go for the open source link as suggested by @polyzen.

**Comment by vishal0071** [comment]
@zaxebo1
You can either use SuperSU by chainfire or the one implemented by the cyanogemod. They both are reliable source, however you can go for the open source link as suggested by @polyzen.

**Comment by vishal0071** [comment]
@zaxebo1
You can either use SuperSU by chainfire or the one implemented by the cyanogemod. They both are reliable source, however you can go for the open source link as suggested by @polyzen.

**Comment by zaxebo1** [comment]
thanks

**Comment by polyzen** [comment]
Looks like either CM currently uses a fork of seSuperuser, or plans to: https://github.com/seSuperuser/Superuser/issues/9

**Comment by lbdroid** [comment]
DON'T use supersu. It is most likely a trojan, and definitely untrustworthy.
CM moved some of their parts around, current code is basically an extension of the linked repo, but in some other locations -- now mixed in in such a way that it is useless outside of CM. They forked from Superuser LONG ago.

We forked from Superuser much more recently and are building it out to be more universal.

**Comment by polyzen** [comment]
@lbdroid, thank you. Your insight is very much appreciated.

**Comment by zaxebo1** [comment]
@lbdroid :  i could not clearly understand your post. Will you kindly elaborate? 

---

**Are you saying that:?**

https://github.com/seSuperuser/Superuser   is untrustworthy and is a trojan?
https://github.com/lbdroid/Superuser  is trustworthy?
https://github.com/CyanogenMod is trustworthy ?
??
----
eagerly waiting for your reply

**Comment by polyzen** [comment]
* https://github.com/seSuperuser/Superuser *is* trustworthy. Chainfire's
SuperSU is untrustworthy as it is closed source.
* https://github.com/lbdroid/Superuser is @ibdroid's own fork.
* CM is trustworthy, but it's superuser is "basically an extension of
[koush's] repo, but in some other locations -- now mixed in in such a way
that it is useless outside of CM."

**Comment by zaxebo1** [comment]
So from the above discussion,it seems "koush family" is  the best option.
BUT there various forks and subforks of the original koush repository "https://github.com/koush/Superuser which is now not being updated".

NOW, Which fork/subfork of koush is better maintained and better featured?

1) https://github.com/phhusson/Superuser

2) https://github.com/seSuperuser/Superuser

3) https://github.com/lbdroid/Superuser

**Comment by vishal0071** [comment]
@zaxebo1 koush is well known for leaving support for his products. Just sayin' 
BTW seems like seSuperuser is the best option if you're using rom other than CM.
But superSU and Chainfire being famous developer all over XDA, I highly doubt it to be untrustworthy.
At the end of the day, it's upto you what seems to be working good for you (:

**Comment by polyzen** [comment]
JuiceSSH is also closed source, and I've use it despite that. Sonelli seems cool, and it's a great tool. ..connectbot/connectbot is lively again, though, and I feel the need to see if I can switch back.

Tools like su and ssh, you want/need to know they're safe, but with closed source options, you can't know for sure.

**Comment by polyzen** [comment]
As for which repo to use, just read [this](http://forum.xda-developers.com/android/software-hacking/wip-selinux-capable-superuser-t3216394) :p

**Comment by lbdroid** [comment]
@zaxebo1 those three "forks" of superuser are NOT DISTINCT.
The main fork is the organizational fork. Our "organization" is called "seSuperuser", for Security Enhanced Superuser. phhusson and I, and everybody else who wants to contribute to any of the projects for seSuperuser need to create their OWN fork of the main seSuperuser repository that they want to contribute to, and make the changes to their fork, then create a pull request back to seSuperuser. If we deem the pull request to be meaningful, understandable, correct, and secure, then we will accept the pull request.

**Comment by lbdroid** [comment]
@polyzenn : you might want to take a look at my SSH repository here;
https://github.com/lbdroid/Android_SSH

That project is a wrapper around OpenSSH. It gives you client and server side of it. The server side of it has a fairly simple GUI wrapper, the client side is the proper suite of ssh commands (use in terminal via Android Terminal Emulator)... ssh, sftp, scp, ssh-keygen, etc.

**Comment by lbdroid** [comment]
@vishal0071 : I wouldn't say that it is so much that he is "well known" for leaving support... rather my understanding was that a lot of his projects were strongly tied to cyanogenmod, which had an ideological split from the kind of projects that he is interested in supporting. I don't blame him for that, CM is... I'd like to throw in some family unfriendly words here, but I will restrain myself. Suffice it to say, I don't see eye to eye with them either, for various reasons, in particular over their inclusion of SPYWARE in their code. Not even particularly well hidden, since its open source spyware. While I was weaning myself off their code, I got into the habit of stripping all the spyware (or at least as much of it as I could find) out of the source, before building.

**Comment by polyzen** [comment]
@lbdroid, thank you, I am taking a look. There wouldn't happen to be build instructions, would there? :p 

You may be interested in [CopperheadOS](https://copperhead.co/android): "A hardened open-source operating system based on Android".

**Comment by zaxebo1** [comment]
@lbdroid: yes, simple instructions in https://github.com/lbdroid/Android_SSH and putting it on google play will be great . 
Then this project may get a potential collaborator too. :)

**Comment by lbdroid** [comment]
To be frank, I built it up for my own use, so sharing it to lots of people is really not of any interest to me. I won't be publishing it to play store. Feel free to publish it yourself, as long as you deal with the "public". And I'd appreciate, if you do publish it, if you'd keep a link to my source repo.

If anybody finds it useful, great! If anyone wants to make reasonable contributions (I'm not interested in bloat or anything that causes *me* any inconvenience), even better.

As far as building it goes, its an NDK application, so import it, make sure NDK is available and configured correctly, and hit the build button.

**Comment by lbdroid** [comment]
Regarding copperhead... I can see a lot of problems coming out of their changes. Not necessarily flaws, but, lets say incompatibilities. Its a neat project, and I'd like to see a lot of their work get upstreamed.

**Comment by polyzen** [comment]
@lbdroid, thank you.

Incompatibilities.. yes. There is so far no intention to maintain the ability to use GApps (which they mention inevitably will probably stop working). Anything that's caused by CopperheadOS itself -- that is otherwise functional in AOSP -- they fix. There has been a fair amount upstreamed already :)
