### ISSUE TITLE
Feature Request : Browser Access

### ISSUE THREAD

**Issue by homersimpsons** [arpitkh96/AmazeFileManager#220]
Hello, thanks for this app, 
I have an idea to enhance this file manger : add a feature to connect from a Web browser and easily manage files from a HTML5 view. 

Thanks for reading 
(It will complete #177)

**Comment by homersimpsons** [comment]
In fact, of AmazeFileManager guideline is to be lightweight and simple then maybe it's better to not implement this. Or maybe it could be provide as an add-on. 
Compare to USB plug there is a better interface and, have a look to FX file Explorer to try it. With that feature I can find my music easily from computer and listen it, manage my photos from computer, have an overall view on my folders/files. And that is not so hard for the en user :
- activate  FX web access
- open a new tab in browser
- fill the correct url
- enter the code 
And that's all

But FX is not open source compare to AmazeFileManager then I would prefer to have this feature Open Source

**Comment by Geyup** [comment]
Again, I'm assuming this is Wifi capability?

What difference does it make if you use a browser or an mtp application?

I've accessed iPhones and Android devices through browser and various mtp devices, and there is no real differences, when it comes to looking at and accessing.

But an mtp device will have various nice options and features a browser will not.

Using a browser is pointless, you are better off using an application better suited to the purpose.

For all systems, Windows, OSX, Linux, there are different kinds of MTP apps to accomplish all of this.
