### ISSUE TITLE
UI is huge on phone

### ISSUE THREAD

**Issue by Matteomt** [arpitkh96/AmazeFileManager#221]
The height of the list items is such that I can only see 7 files per screen on my phone (6/screen with 3-column grid view, 4-columns are too narrow).
It would be very appreciated if a "compact view" option could be added.

Anyway, thanks for this beautiful open source app. I've just suggested it to my friends.

**Comment by vishal0071** [comment]
The height of items is as per the material design guidelines. I don't think it will be a good idea to not follow them.

**Comment by Matteomt** [comment]
_Guidelines_, not _rules_, you said right.
Let me ask if these design guidelines imply that bad design is good if it follows the guidelines.

Also, I didn't mention changing the height, but adding an new view option.
For example, Google Drive on my phone has a view option that allows me to see 14 directories per screen using 2 columns and small icons. That's two times the density of Amaze in usable configuration.

Anyway, as far as I know, material design doesn't talk about file managers. For a good app like this one I expect a design that is specifically crafted ;)

**Comment by vishal0071** [comment]
Google drive shows the directories in compact view. So, you're implying that we use a similar approach?
