### ISSUE TITLE
Lost file when moving file with invalid chars.

### ISSUE THREAD

**Issue by denilsonsa** [arpitkh96/AmazeFileManager#222]
System:
- Moto G (2nd gen) with Android 5.0, with an external SD card installed.
- `/storage/sdcard0/` is the internal memory.
- `/storage/sdcard1/` is the actual external SD card.

How to reproduce:
1. Create a file at `/storage/sdcard0/` containing a colon `:` in the name. The [Echo: Time Travelling Recorder](https://play.google.com/store/apps/details?id=eu.mrogalski.saidit) saves files like that.
2. Go to Amaze, select that file in `/storage/sdcard0/`.
3. Click _copy_ (safe) or _move_ (unsafe!).
4. Navigate to `/storage/sdcard1/`.
5. Click _paste_. The screen will redraw, as if the operation has finished, but the file will not be found at the destination. If you selected _move_, the file will have been removed from the origin as well.

Reason: a colon `:` is an invalid char for filenames in FAT systems. If I rename the original file to remove the colon, then I can copy/move it correctly with Amaze.

Reason 2: Amaze does not seem to detect failure when copying/moving a file in such case. Which leads to confusion to the user (bad UX due to lack of feedback) or lost files.

**Comment by vishal0071** [comment]
Worked fine for me. You sure problem was not related to writing to sdcard1? Try pasting the file with colon in any directory in sdcard0 itself.

**Comment by denilsonsa** [comment]
I've formatted the SD card on my phone to "internal storage", so now it is not FAT32 anymore. I can, however, reproduce the bug in on my tablet (Nook Tablet running Android 4.4.4 Cyanogenmod 11).

To reproduce it, I created a directory in the internal storage with the same permissions as the SD card (`/data/testing/`, `chmod 770`, `chgrp sdcard_r`). I had to do that because my tablet does not have any user-writable non-FAT partition. I also created two empty files named `test.period.txt` and `test:colon.txt`.

Then I used Amaze to copy those files to the SD card (which is formatted as FAT. Only one of them was copied, and no error message was shown.

Then I tried moving those files, only one was moved, the other was lost, and no error message.

I've also recorded a video showing this bug: https://youtu.be/ODSFO8y8ZnA

**Comment by vishal0071** [comment]
Will work on it's fix.

**Comment by vishal0071** [comment]
I restricted creation of any new file/folder or renaming of existing with any of these reserved chars in the name. But what do you suggest should be done, if any existing file already contains these symbols and the user tries to perform cut/copy operation on it?
\*sry for being late to address this issue*\

**Comment by denilsonsa** [comment]
> I restricted creation of any new file/folder or renaming of existing with any of these reserved chars in the name.

Remember that some filesystems have different restrictions than others. So, a blacklist like you described might not be the best solution.

I suppose you call a system API to copy/move/open/write/whatever a file. That system call can fail with an error. Couldn't Amaze File Manager just show this error to the user?

Case 1: User tries to copy/move/rename a file within ext4 (or similar) file system. It should just work.

Case 2: User tries to copy/move/rename a file within FAT file system. I believe the system call will fail, and will either return an error code, or raise an exception. (I've never done any Android coding, I'm not sure how the actual API works.) Then, Amaze will detect the returned error code, or the thrown exception, and will display the actual error to the user. (After all, it may fail for other reasons, such as disk full, read-only…)

What do you think?

P.S.: Another possible solution would be to add an option: "Auto-replace invalid filename characters in operations". That would be a nice convenience option, but might not be worth the trouble of implementing it.

**Comment by vishal0071** [comment]
OK I'll look into it.

**Comment by vishal0071** [comment]
Apart from filesystem check (which involves running various commands into the environment, and other implementation troubles), I implemented these reserved char checks for copy and moving too. So, for now, it blocks every such operation independent of the filesystem. So I'll maybe, inform user to rename the file instead, before performing such operation, what say?

**Comment by vishal0071** [comment]
Test latest beta (v3.1.2 Beta 3+) and report.
