### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by 1234faris** [arpitkh96/AmazeFileManager#223]
How can i turn this source code into google drive app, like it play videos and audios from google drive cloud instead of SDcard,  plz help me seriously waiting for replies. I want all features to be same but it shows drive data into the fragments instead of SD card. plz help

**Comment by vishal0071** [comment]
That cannot be done. Amaze support only local storage and smb as of now.

**Comment by 1234faris** [comment]
Is there any other app that can play that  ?

**Comment by 1234faris** [comment]
Can you make one for me i will pay for that.... 

here is my fb id 
https://www.facebook.com/faris.farley

**Comment by polyzen** [comment]
Can Google Drive not do it?

**Comment by 1234faris** [comment]
No i have searched a lot iam not expert in making apps, but i find Amaze with good qualities and options so i need help to convert it ito google drive app, if anyone can do for me i will pay him :)

**Comment by 1234faris** [comment]
Bro i have emailed you, please reply....

**Comment by vishal0071** [comment]
@1234faris Currently I'm working on making the app itself stable. There is already some code for Google Drive integration in the app. But it is not working. I will surely work on that once I get enough time. So, you don't need to pay me, just be patient.

**Comment by 1234faris** [comment]
Thanks @vishal0071, I will be definitely grateful to you. :) Stay blessed and waiting for good news from you...

Peace
