### ISSUE TITLE
android 4.2 system crash

### ISSUE THREAD

**Issue by zhangdp2008** [arpitkh96/AmazeFileManager#224]
02-25 13:21:33.340 18762-18762/com.amaze.filemanager I/dalvikvm: Could not find method android.view.Window.setStatusBarColor, referenced from method com.amaze.filemanager.activities.MainActivity.initialiseViews
02-25 13:21:33.340 18762-18762/com.amaze.filemanager W/dalvikvm: VFY: unable to resolve virtual method 18459: Landroid/view/Window;.setStatusBarColor (I)V
02-25 13:21:33.340 18762-18762/com.amaze.filemanager I/dalvikvm: Could not find method android.view.Window.setNavigationBarColor, referenced from method com.amaze.filemanager.activities.MainActivity.initialiseViews
02-25 13:21:33.340 18762-18762/com.amaze.filemanager W/dalvikvm: VFY: unable to resolve virtual method 18458: Landroid/view/Window;.setNavigationBarColor (I)V
02-25 13:21:33.350 18762-18762/com.amaze.filemanager E/dalvikvm: Could not find class 'android.app.ActivityManager$TaskDescription', referenced from method com.amaze.filemanager.activities.MainActivity.onCreate

**Comment by vishal0071** [comment]
Try compiling the play-debug flavour now
