### ISSUE TITLE
Amaze texte editor : edited text lost when screen rotates 

### ISSUE THREAD

**Issue by Siltaar** [arpitkh96/AmazeFileManager#229]
If you edit a text file from Amaze, change its content and rotates the screen (for instance to use the wide keyboard) the text you'll be editing in wide mode will be the original text, and you'll have lost your portrait-mode made modifications.

I would have expected to continue to edit the text, with no need to save before tilting the device (or even automatically). Just being continuoulsy editing my text, with no regard for the current orientation of the phone.

Seen on Fairphone 2, Android 5.1.
Amaze 3.0.1.

**Comment by qpoi9762** [comment]
I have also had this error. I am using Amaze (3.0.0) in Android (5.1) on a Moto G.

**Comment by vishal0071** [comment]
fixed in feb343af3199712a0b44f229bc1a1efff679458c
