### ISSUE TITLE
Amaze File Manager : if display files on top, sort won't work

### ISSUE THREAD

**Issue by Siltaar** [arpitkh96/AmazeFileManager#230]
It is possible to set:
- Folders or Files on top;
- Alphabetical, or Chronological or […] sorts.

But sorts are only effectives if folders are on top.
I would have been happy to have this working setting:
- Files on top;
- Alphabetical order.

Show files in alphabetical order, on top of folders.

Seen on Fairphone 2, Android 5.1.
Amaze 3.0.1.

**Comment by vishal0071** [comment]
Does the issue still exist?

**Comment by Siltaar** [comment]
I downloaded Amaze v3.1.1 from f-droid and yes, the issue is still here.

And to add something, changing the « Folder sort » is only taken into account when I also change the general sorting.

**Comment by EmmanuelMess** [comment]
This:
Files on top;
Alphabetical order.
Works in v3.1.2 Beta 9.
