### ISSUE TITLE
Error Report: Text Editor: Position Lost When Switching Between Portrait and Landscape Orientations

### ISSUE THREAD

**Issue by qpoi9762** [arpitkh96/AmazeFileManager#232]
In the text editor, the viewing position is lost when switching between portrait and landscape orientations. This occurs whether or not the cursor has been placed within the current viewing position. The viewing position is returned to the beginning of the text.

This may be related to issue #229.

I am using Amaze (3.0.0) in Android (5.1) on a Moto G.

**Comment by vishal0071** [comment]
implemented in feb343af3199712a0b44f229bc1a1efff679458c
