### ISSUE TITLE
Dropbox

### ISSUE THREAD

**Issue by UnderFact** [arpitkh96/AmazeFileManager#240]
Dropbox support would be awesome!
I don't care if there isn't Google drive for non-free reasons.

**Comment by Geyup** [comment]
Sorry to butt in, don't mean to be rude, but Dropbox is lame!

If you want dropbox, then get the app. :)

I really hope the developer(s) keep this as a simple file manager with no bloat at all!

**Comment by vishal0071** [comment]
This is not an issue. And I'm already aware of this, but I need lots of free time to actually understand their API. So, this is gonna take time to get implemented. Closing issue for now.

**Comment by Geyup** [comment]
I will make a post later, as a Request explaining adding features into Amaze, it's not needed.

thanks

**Comment by UnderFact** [comment]
Thank-you for replying! Sorry for not posting it as a feature, I'm new to
github and I couldn't seem to find that option. But I don't care how long
it will take, or if you have to make it an extension, just some cloud
support would be nice, because I have a Kindle with only 5 GB of internal
storage, and I need to share things with my brother, if you can't, maybe I
could learn how!

**Comment by Geyup** [comment]
@UnderFact why don't you just install Dropbox on your device instead?

**Comment by UnderFact** [comment]
Because it isn't as good a file manager as amaze, and if you mean
mirroring, I have 59 gigabytes of important data on my dropbox.

**Comment by Geyup** [comment]
@UnderFact 

If you're trying to compare Amaze to Dropbox, Dropbox is not a file manager, it's a hosting company.

So what are you trying to explain, and what are you trying to do?

You don't need to have Dropbox support built into a file manager to have it work with a file manager.

Have you installed the Android Dropbox app and tried it?

**Comment by UnderFact** [comment]
I have, and I do sort of get what you're saying, but I would like the
ability to hit copy in amaze and then go to the other page, and open the
Dropbox category, and paste.

**Comment by Geyup** [comment]
Just try dropbox, you might find it does all you need it to.

Try and see! :)

Here's my problem with adding in Dropbox, there are already many file managers with Dropbox built in.

But there aren't any small nice light weight file managers out there, that just do the ```Basics```, and this is what we really need.

**Comment by UnderFact** [comment]
OK, thank-you for the cooperation, I do get what you mean! It is nice to
have such a snappy file manager! I would like if the share button wasn't in
the other category! If you could move the share button to just the top of
the screen when you select something, I would be very happy! BTW, AMAZEing
file manager!

**Comment by polyzen** [comment]
@UnderFact, please open another issue for share button request.
