### ISSUE TITLE
Request: To Remove Drop Down?

### ISSUE THREAD

**Issue by Geyup** [arpitkh96/AmazeFileManager#242]
Hello,

I noticed at the top of the screen a drop down, I'm assuming is like moving back and forth from the last present locations?

Personally I don't have a use for this, makes the app looked cluttered and seems odd, and doesn't seem to work correctly at times. It will sometimes just show the location twice...

I'm attaching a screen shot you can see ```acct``` was added twice.

![amaze-dropdown](https://cloud.githubusercontent.com/assets/13072581/14133340/bb061c70-f63d-11e5-9d66-deb15cc7c6a0.jpg)

Whatever the purpose of this drop down is, if others like it, can you at lease please include an option in the settings for those that don't want it, and can disable it?

Thanks

**Comment by vishal0071** [comment]
The dropdown was to show the current directory name of the specific tab (remember we have two tabs?). 
Anyways, the dropdown has already been removed. You shall see the changes in the latest beta versions.

**Comment by Geyup** [comment]
Great, glad to see this gone...

Keep up the great work!
