### ISSUE TITLE
Inconsistent result of appbar click

### ISSUE THREAD

**Issue by Geyup** [arpitkh96/AmazeFileManager#243]
Hello,

Sorry if I'm being ignorant here, but I don't see anything that describes what I'm seeing.

In this screen show below, if I click on the word /cache where the red arrow is pointing to.

![what_1](https://cloud.githubusercontent.com/assets/13072581/14133938/d39b0016-f642-11e5-8dab-860fbdf6e55c.jpg)

I end up with a window like this below;

![what_2](https://cloud.githubusercontent.com/assets/13072581/14133978/1058f06c-f643-11e5-8e08-b94e954e1d8e.jpg)

What is this second window for?

Thanks

**Comment by vishal0071** [comment]
That's the current path of the directory opened.
The second screenshot is strange, though. Tell me the details of your device.

**Comment by Geyup** [comment]
Samsung Galaxy S3

**Comment by vishal0071** [comment]
Does the issue still exist?

**Comment by Geyup** [comment]
Sorry I'm no longer using the app...
