### ISSUE TITLE
Request: To Increase Icons & Font Size?

### ISSUE THREAD

**Issue by Geyup** [arpitkh96/AmazeFileManager#244]
Hello,

Can you please make an option to change the icon and fonts sizes?

On a phone for me the icons and fonts are small, it would be nice if they could be made larger.

thank you

**Comment by vishal0071** [comment]
That is not an option for now. It sort of makes the UI inconsistent, to provide this level of dynamic options to the user.

**Comment by Geyup** [comment]
Ok, maybe in the future this can be figured out...

thanks
