### ISSUE TITLE
Request: Please Keep Amaze Simple & Small!

### ISSUE THREAD

**Issue by Geyup** [arpitkh96/AmazeFileManager#245]
First I want to say sorry, if you or anyone is getting upset at me jumping in posts, over users wanting to add in features.

I'm really tired of seeing all the bloat, when end-users can get stand alone apps for all these needs.

IMHO it's pointless, makes me feel like end-users are either to lazy, or don't realize they can just grab a stand alone app for all their needs, or they just want simplicity from their stand point of a ``All in One``` app. But these end-users don't realize more code, more bugs and more headaches for the developer.

I like what I see, and I know what I see is needed! Simple, Light Weight, No Frills File Manager, that does the basics and does them good!

The world of Android already has a heap of Full Featured, and more featured file managers! But what the world of Android does not have is a nice light weight file manager like this!

Amaze is a really great Light Weight & Simple File Manager and I hope it remains that way!

Here are my thoughts!

I've tried almost every file manager out there, if the end-user wants more features, then please use another file manager.

There are Full Featured file mangers that will fill the wishes of those asking for more features.

The biggest problem right now is, there are no great simple and light weight file managers, if there are, then I'd like to see some names to prove it, at the level and quality of this file manager!

I don't mean to be rude to anyone, but do the end-users that are using Amaze asking for more features, not even realize there are no good light weight file managers?

For all the bloated so called full featured file managers that offer all the features people are asking, don't you realize these are available as stand alone apps?

I see Amaze as a simple light weight file manager, and nothing more, and this is what we need in the world of Android!

**Comment by polyzen** [comment]
A solution for this would be modules, [as Termux does](https://termux.com/add-ons.html).

**Comment by Geyup** [comment]
Or as Plugins, either way, we already have a world of bloat floating around, but not one decent light weight file manager.

**Comment by alanjames1987** [comment]
@Geyup you could always fork Amaze and maintain it as simplistically as you want it to be. Alternatively, because Amaze uses [SemVer](http://semver.org/) so you can checkout any version number you like and compile it to your devices if the Play Store version updates and adds new features that you don't want. That is the advantage of Amaze being open source.

Additionally, htop is a terminal based program, Termux is a terminal emulator. Termux not only looks like htop but is a program that would run htop. As a terminal emulator Termux looks like any program it runs.

**Comment by Geyup** [comment]
Got it for the fork and compile...

Btw I know what htop is, I use it, wasn't paying attention about Termux...

**Comment by alanjames1987** [comment]
> wasn't paying attention about Termux...

That's why I wanted to bring it to your attention. I figure education is always a good thing :)

**Comment by Geyup** [comment]
:)
