### ISSUE TITLE
Request: Please Remove SMB

### ISSUE THREAD

**Issue by Geyup** [arpitkh96/AmazeFileManager#246]
Hi,

Can you please remove SMB, and keep this File Manager simple and basic? Please let the end-users get a SMB app if they are so desperate for needing sharing with Windows.

These people need to learn the KISS philosophy!

Thanks for all you do! Keep it Light Weight for the Love of God! LOL

**Comment by holocronweaver** [comment]
Network shares are well within the scope of a file manager and their inclusion makes Amaze much more practically useful. Without SMB support, I would likely seek another file manager. There are already plenty of primitive open source file managers available for Android, but virtually no reasonably featured ones.

**Comment by polyzen** [comment]
Imo would be even nicer to just extract the smb feature into a separate app/plugin.

**Comment by RazrFalcon** [comment]
Is smb support still present? Can't find it in latest version.

**Comment by vishal0071** [comment]
@RazrFalcon '+' fab button in bottom right.

**Comment by RazrFalcon** [comment]
Thanks!
