### ISSUE TITLE
Question: Compiling Amaze?

### ISSUE THREAD

**Issue by Geyup** [arpitkh96/AmazeFileManager#247]
Hi,

Sorry if there is info here on GitHub, I am not seeing it.

I'd like to compile Amaze, that is, if you allow for the removal of features? I'd like to compile and remove SMB support.

If possible, is this all I need to do in Linux?

Install Android SDK and ant, then generate a build.xml; ```android update project -p . -n $PROJECT_NAME -s``` Then build the project with ``` ant debug```?

Does this cover it?

thank you

**Comment by vishal0071** [comment]
No the project uses gradle build system, and hence you would need to install android studio and import the project in it. Then you can compile and modify it from there.

**Comment by Geyup** [comment]
Ahh so need this IDE...

ok thanks

**Comment by vishal0071** [comment]
You can just Google android studio, and follow it's installation guide. It's very easy to import project in it. However, you might need to spend some time removing those extra classes and references to actually remove smb from the app.

**Comment by Geyup** [comment]
@vishal0071 how many lines of code do you think there are?

Basically all I need to do is search for the words ```smb``` or ```samba```?

thanks

**Comment by vishal0071** [comment]
As a matter of fact, I did not program the whole smb thing, @arpitkh96 did.
And afaik, the smb is closely embedded in the app, for ex. in back press action, in copy/paste and whole lot of another things. So, you gotta work some logic too, instead of just removing lines with "smb" phrases in it.

**Comment by Geyup** [comment]
ok no worries I'l lleave it alone...

By chance any ideas on when the next release is coming?

thanks

**Comment by pejakm** [comment]
@Geyup I left a link to the apk file I've compiled, in this issue: https://github.com/arpitkh96/AmazeFileManager/issues/239
Version is 8be57e9f6524e17d3d1a53a37452aefb164225c0 (3.0.2 beta 4)

**Comment by Geyup** [comment]
@pejakm thanks

**Comment by alanjames1987** [comment]
@Geyup you can also opt in to using the testing version in the Play Store.
https://play.google.com/apps/testing/com.amaze.filemanager

**Comment by Geyup** [comment]
thanks
