### ISSUE TITLE
[feature-request] draggable scrollbar (for fast scrolling in folders with many files)

### ISSUE THREAD

**Issue by revuwa** [arpitkh96/AmazeFileManager#249]
Thanks again for that awesome app and your great work!

Just one thing. I'm bloody missing the possibility to scroll fast through folder with many files.
If I have a folder with hundreds or thousands of files and want to scroll to the end of the file list, I nearly break my 	thumb by hectically scrolling to the bottom.

I saw a feature, for example in the regular Android contacts app, where you could grab the scrollbar and move it simply and lightning fast to the bottom.

I'm not hundred percent sure, but I think this feature is named "draggable scrollbar", and (hopefully) shouldn't be that hard to enable it: https://stackoverflow.com/questions/18254370/how-to-add-draggable-scrollbar-to-scrollview-listview-in-android

I would love to see that kind of feature sometime in the future in this wonderful app.
Thanks in advance for any support in that case.

**Comment by vishal0071** [comment]
You might wanna try beta versions on g+ community. It has the scrollbar implemented.

**Comment by revuwa** [comment]
Thanks for your response.
(Sadly I don't have a Google account - and don't want to create one). 
So I'm hoping and waiting for the next version release...

**Comment by vishal0071** [comment]
In that case, you might wanna stay updated on xda thread. I'll be posting direct download links there
http://forum.xda-developers.com/showpost.php?p=66018114&postcount=420
