### ISSUE TITLE
Unable to refresh empty folder

### ISSUE THREAD

**Issue by guillermogf** [arpitkh96/AmazeFileManager#250]
When I'm on an empty folder I'm unable to refresh its content by swiping down, as I would normally do on any other folder.

Device info:
- Amaze 3.0.1, last version available on F-Droid
- Android version: 5.1.1 LMY47V
- Device: Xiaomi Mi-4c

**Comment by revuwa** [comment]
Do you really mean, that the refresh isn't working, or can't you just see the files you put in the (previous empty) folder after a working refresh?
If he last one, try a tool like SD Scanner (https://f-droid.org/repository/browse/?fdid=com.gmail.jerickson314.sdscanner) for making the new files visible.

I don't know if this behavior has changed in newer Amaze versions. I would vote for that functionality inside of Amaze. Probably the SD Scanner project (https://github.com/jerickson314/sdscanner) could provide some code for that(?)

(I used that Amaze / SD Scanner combo successfully on AOSP 4.2.2 and 6.0.1).

**Comment by guillermogf** [comment]
It doesn't even show the refreshing animation, so I suppose that it's simply not working. Furthermore, if I leave the folder and click on it again the new content appears, so I guess it isn't related to your suggestion. But thanks anyway.

I don't know what further info I can provide to help debugging this issue.

**Comment by wb9688** [comment]
Same problem here on latest gplay beta

**Comment by vishal0071** [comment]
The empty list is actually not a list, it is a custom view. So, it can't be refreshed. But I'll try to fix it.

**Comment by vishal0071** [comment]
No need to refresh it. Perform any operation and it'll refresh automatically.
