### ISSUE TITLE
Switching Views in SMB Path Changes Path to Home

### ISSUE THREAD

**Issue by alanjames1987** [arpitkh96/AmazeFileManager#251]
When the view is changed between Grid View and List View in an SMB path the path will change back to the home directory.

I'm currently using version 3.0.0.

**Comment by vishal0071** [comment]
Could you try and report this with latest beta from G+ community?

**Comment by alanjames1987** [comment]
Using 3.0.4 beta_4 works. 

Thank you for telling me about the community version. I wasn't aware I could run the next version without having to compile.
