### ISSUE TITLE
Release schedule?

### ISSUE THREAD

**Issue by mhyqwvcu** [arpitkh96/AmazeFileManager#252]
Do you plan to release updates more often? I see this project is actively developed but users have yet to see the fruits of nearly a year of labor.

**Comment by vishal0071** [comment]
I'm releasing beta updates to make it more stable before a major update for all users. Sadly, I'm not able to spare enough time from University assignments and stuff to devote much time here, so the pace is little slow. But as the saying goes, better late than never ;)

**Comment by mhyqwvcu** [comment]
Understood, thanks!
