### ISSUE TITLE
Use Transifex (or equivalent) for easy translations

### ISSUE THREAD

**Issue by keunes** [arpitkh96/AmazeFileManager#255]
It would be nice if a simple system (simple from my noob-perspective) could be used to add translations. I'm translating for AntennaPod already an find Transifex rather convenient to use (as a translator, as a dev I don't know).
Transifex is proprietary but free for open source projects I believe.

**Comment by vishal0071** [comment]
I'll look into it.

**Comment by pejakm** [comment]
I suggest Weblate: https://hosted.weblate.org. Fast and easy, and has good integration with github.

**Comment by vishal0071** [comment]
Alright guys, thanks for your recommendations, we are using transifex now (:
https://www.transifex.com/amaze/amaze-file-manager-1/

**Comment by keunes** [comment]
@vishal0071 Why the "-1" :P

**Comment by vishal0071** [comment]
@keunes don't know. That's the URL they generated to this project.
