### ISSUE TITLE
[Request] Support for markdown

### ISSUE THREAD

**Issue by Hund** [arpitkh96/AmazeFileManager#256]
It would be nice if Amaze could recognize markdown files (.MD) so you can open and edit them without changing the fileending to something like .txt first.

**Comment by vishal0071** [comment]
You can choose 'text' from open as dialog instead of manually renaming it to .txt

**Comment by Hund** [comment]
Where do I find the "open as" dialog? When I click on the file it asks me if I want to open the file with apps like Podcast addict and the web browser. And longpressing only selects the file.

**Comment by vishal0071** [comment]
Very well, I'll be looking into it.

**Comment by gsantner** [comment]
Works for me (latest release) as described - Open With pops up
