### ISSUE TITLE
On sdcard: Renaming does not work, and file moves extremely slow﻿

### ISSUE THREAD

**Issue by EnviousElitist** [arpitkh96/AmazeFileManager#259]
Renaming does not work, and file moves are extremely slow (progress
bar speed indicates that it is copying then deleting).

I'm on Amaze 3.0.0 on Android 6.0.1, US Galaxy S7 edge. Not rooted, SD
card permissions granted.﻿

**Comment by Yowlen** [comment]
I've run into this issue, myself, but I don't think it's an issue with Amaze. It seems to be an issue with the way the kernel handles the "mv" command. Using a "cp && rm" command combo is lightning-fast compared to the "mv" command when I tested in a terminal.

I'm running Amaze 3.0.1 (last version on F-Droid) on an LG Leon running a custom 5.1.1 ROM, in case it makes a difference. On the stock ROM, I didn't have this issue, so this further evidences my conclusion.

**Comment by vishal0071** [comment]
Test latest beta (v3.1.2 Beta 3+) and report.

**Comment by Yowlen** [comment]
I've since found my own solution to the "slow moving files" thing. A few tweaks via Kernel Aduitor, and updating Busybox. (I'm not sure which one ended up doing it, but likely one of the tweaks since the cp/mv/rm commands are built-in to the system & therefore not necessary to call from Busybox.)
