### ISSUE TITLE
Tabs are not up to date when moving files around

### ISSUE THREAD

**Issue by vicentedealencar** [arpitkh96/AmazeFileManager#262]
Hi, I really liked the shape of this project and it has lots of great features, but using it I ended up losing 10gb of data.

I wanted to use https://getsync.com/ to share 20gb, but I found out that it actually copy the files to its folder to host them, and I don`t have that much free space. So, I found about amaze and started to move the files around.

My first attempt was to move the whole folder at once, but Amaze popped out a modal saying that it couldn't be done because of not enough free space.

Then I tried moving files 5 at a time and got myself busted. I did it by using one tab at the source and one at the destination to speed up the process, but the source tab wasn't keeping it self up to date and I accidentally repeatedly moved the same file more than once and some got corrupted, as I chose to substitute file on destination.

Now I see there is a pull to refresh feature that I should have used in my process. I was thinking Amaze would be watching the file system and displaying me actual information.

Is it possible to implement fs-watch on android? If so maybe the pull to refresh feature becomes unnecessary.

Or as a workaround, maybe there is a way to force refresh on both tabs after a operation (move, maybe others)

Thank you for that awesome project, and I hope I can help improve it. Sad thing I lost so much data.

**Comment by vishal0071** [comment]
Hi, I apologize for your data loss. Thanks for reporting this, I'll do force refresh on both tabs once any operation has been performed.

**Comment by diesl** [comment]
You also have to check for file/folder existence before starting a move or copy operation. I also tried to move some files to another destination, but checked the source file again that was not existent anymore. So the file at the destination was overwritten and resulted in a 0 byte file. 

Please fix this ASAP because of the possible data loss.

**Comment by vishal0071** [comment]
Fixed! Sry, for late followup. I didn't have the knowledge of this API at that time, but now when I came to know about this, made this my first priority.
