### ISSUE TITLE
When moving a file to a SMB connection fails during transmission, source file is removed anyway

### ISSUE THREAD

**Issue by diesl** [arpitkh96/AmazeFileManager#263]
When I move a file to SMB directory and the transmission fails (e.g. wireless connection drops) before it is competed successfully, the source file is removed anyway.

Unfortunately I lost data because of this bug :cry: This is kind of a showstopper for me...

It seems similar to https://github.com/arpitkh96/AmazeFileManager/issues/176, maybe it is the same. There, the source file is also removed although the transmission failed.

I wonder if the other bug is already fixed in the current version? If not, why there is no bugfix release? Losing files is the worst case scenario in my opinion.

Installed version: 3.0.1

**Comment by vishal0071** [comment]
Hi, I agree and apoligize for your file loss. Could you please try and report this problem with the beta version. 
https://plus.google.com/communities/113997576965363268101
You need to join our G+ community to opt in for the beta version.
Ofcourse, you'll also get lots of other bug fixes and features along in beta ;)

**Comment by diesl** [comment]
I use the F-Droid repository. Is it possible to add the beta version there too?

**Comment by vishal0071** [comment]
Nope. But I recently updated the XDA thread with the app link. Here
http://forum.xda-developers.com/showpost.php?p=66018114&postcount=420

**Comment by diesl** [comment]
I checked again with v3.0.2 beta 4:
The file does not get removed in case of a transmission failure. 

However, I experienced it the other way round: Sometimes, when the file was transferred correctly (checked md5 hashes), it did not get removed from the source. Maybe somebody can confirm this

**Comment by vishal0071** [comment]
I suppose it's fixed.
