### ISSUE TITLE
Cannot detect video

### ISSUE THREAD

**Issue by lino10** [arpitkh96/AmazeFileManager#273]
Hi, I have videos in Whatsapp folder.

I can see the videos fine in 'Video' category in VLC.

But in Amaze 'Video' category, there's no file there.

I'm using Nexus 5x with latest update.

**Comment by pradyukrish** [comment]
Hi @lino10 ,
Could you please check and let us know if you have a file named ".nomedia" in the WhatsApp videos directory? You should turn on the "Show hidden files and folders" option in Amaze's settings to look for the file. Amaze uses MediaStore to list videos. So, by default directories containing .nomedia file are not scanned by the media scanner and hence not displayed in the list. VLC works differently. It scans through all the files in storage and then checks for file extensions to detect video files.

**Comment by lino10** [comment]
Yes, that file exists in the directory.
Is it possible to override it?

**Comment by pradyukrish** [comment]
You could just delete the ".nomedia" file from that directory. Then you'll be able to see those videos in Amaze and the Gallery application too. It's just an empty file with that name. You can create it anytime you want and the media scanner will ignore that  directory from then on.

**Comment by lino10** [comment]
I meant, is there's no setting in Amaze to override "nomedia"?
Though it's not really a problem for me. I can still see the videos in VLC.
Thank you :)
