### ISSUE TITLE
Does not detect path to external sd card

### ISSUE THREAD

**Issue by Gotolei** [arpitkh96/AmazeFileManager#275]
When I plug in an sd card on my phone (Moto G '15, unrooted 6.0) , it's mounted as /storage/[deviceID] instead of /storage/sdcard1 or whatever the standard is.
https://i.imgur.com/rj4A3Nl.png

Trying to open "External Storage" through the sidebar brings up an "open as..." dialog, and when pointed back to Amaze brings it to a blank screen labeled sdcard1.
https://i.imgur.com/qRozR6V.png

**Comment by Neverest** [comment]
Same here. Get the Open As prompt when I choose my external sd card.

Tablet: Asus Transformer Prime Infinity(TF700) running android version 6.0.1 via custom ROM.

**Comment by floriangosse** [comment]
I have the same problem on a Moto G 2nd gen. As an workaround I created a bookmark for the correct path. But this needs be fixed because it took me days to find out why I can access the sd card anymore.

**Comment by jroldroyd** [comment]
I also came to report this. I am surprised to read above that some folk see an "External Storage" option in the sidebar. I do not see that.

It'd be great if Amaze could keep shortcuts to all three of: /sdcard, /storage/ABCD-1234 (as adjusted for the device) and to / permanently in either the sidebar of the drop-down menu.

Thanks.

**Comment by armaccloud** [comment]
This issue made me switch between amaze and the stock file manager for a while until I found out its possible to make a bookmark to the sdcard. It should be shown by default under the internal sdcard I would think.

I'm on cyanogenmod 13.0-20160409-NIGHTLY-klte on Samsung Galaxy S5.

Keep up the the good work!
