### ISSUE TITLE
Header bar not refreshed after automatic folder refresh

### ISSUE THREAD

**Issue by diesl** [arpitkh96/AmazeFileManager#279]
Situation:
1. Move files out of folder _foo_ to _bar_
2. Go back to folder _foo_ and select a file while move operation still in progress. The header bar will change to the "1 file selected" mode with a back arrow etc.
3. When the move operation is completed, the folder will be reloaded automatically after a while
4. File selection in the main window is gone because of the refresh, but the header bar still shows "1 file selected"

Version: 3.0.2 beta 4

**Comment by vishal0071** [comment]
Does the issue still exist?
