### ISSUE TITLE
Source code are not compilabile "out of the box"

### ISSUE THREAD

**Issue by RrOoSsSsOo** [arpitkh96/AmazeFileManager#284]
After make a clear "git clone" and open project folder with Android Studio it reports these errors during a Make project (source code isn't compilabile _out of the box_):

- AmazeFileManager\src\fdroid\java\com\amaze\filemanager\activities\MainActivity.java
    - error: cannot find symbol variable fabskin
- AmazeFileManager\src\main\java\com\amaze\filemanager\fragments\Main.java
    - error: cannot find symbol variable currentTab
    - error: cannot find symbol method updateViews(ColorDrawable)
- AmazeFileManager\src\main\java\com\amaze\filemanager\fragments\TabFragment.java
    - error: cannot find symbol variable currentTab
    - error: cannot find symbol method updateViews(ColorDrawable)
- AmazeFileManager\src\main\java\com\amaze\filemanager\activities\DbViewer.java
    - error: cannot find symbol variable currentTab
- AmazeFileManager\src\main\java\com\amaze\filemanager\activities\Preferences.java
    - error: cannot find symbol variable currentTab
- AmazeFileManager\src\main\java\com\amaze\filemanager\activities\TextReader.java
    - error: cannot find symbol variable currentTab
- AmazeFileManager\src\main\java\com\amaze\filemanager\fragments\ZipViewer.java
    - error: cannot find symbol method updateViews(ColorDrawable)
    - error: cannot find symbol variable currentTab

**Comment by vishal0071** [comment]
Select the build flavour to playDebug from lower left of Android Studio

**Comment by RrOoSsSsOo** [comment]
Yeah, _playDebug_ works

**Comment by vishal0071** [comment]
I've updated fdroid too, in case you wanna build that.
