### ISSUE TITLE
Unable to translate "Use custom IP" string

### ISSUE THREAD

**Issue by amalvarenga** [arpitkh96/AmazeFileManager#294]
File: src/main/java/com/amaze/filemanager/ui/dialogs/SmbSearchDialog.java

This string is not present in values/strings.xml file.

See screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/5130776/17008368/053e21b6-4ec7-11e6-95db-459d16c2e64c.png)

**Comment by vishal0071** [comment]
Fixed in #307
