### ISSUE TITLE
Unable to translate "How to access shared windows folder on android (smb)" instructions

### ISSUE THREAD

**Issue by amalvarenga** [arpitkh96/AmazeFileManager#295]
File: src/main/java/com/amaze/filemanager/utils/Futils.java

This dialog open when I touch on "Need help?" link. (SMB connection dialog)

**Comment by vishal0071** [comment]
Thanks for pointing this out, I'll reference the strings in xml so you can translate them. Wait for my commit.

**Comment by vishal0071** [comment]
Bump. Forgot about this ):

**Comment by vishal0071** [comment]
Fixed
