### ISSUE TITLE
Unsecured file move: files deleted on origin folder even if not successfuly moved

### ISSUE THREAD

**Issue by motofix** [arpitkh96/AmazeFileManager#299]
Today, I lose 10G. of data. How to reproduce:
- Configure your Android to mount your SD card when plugged to PC (and forget you've configured it that way)
- Select gigs of photo and video on your internal storage to move them on SDCard
- After few minutes, consider this operation would drain your battery, and connect your Android to your PC to charge your battery
- Android dismount the SDCard to make it available to be mounted on your PC
- Move operation interrupted: all file from origin directory are deleted, untransfered data is lost
- Have a sad day.

Expected behavior: only successful file transfer should trigger file deletion in origin folder.

**Comment by diesl** [comment]
Which version did you use?
I had the same problem here: https://github.com/arpitkh96/AmazeFileManager/issues/263

**Comment by motofix** [comment]
Version 3.0.1

**Comment by diesl** [comment]
As noted in the other issue, it seems to be fixed in subsequent versions.
It would suggest to close it as a duplicate and/or fixed in version 3.0.2

**Comment by vishal0071** [comment]
I think it's been fixed. Test latest beta versions and report back.
