### ISSUE TITLE
New version in F-Droid

### ISSUE THREAD

**Issue by proninyaroslav** [arpitkh96/AmazeFileManager#300]
Why the new versions Amaze File Manager in F-Droid doesn't come for almost a year?

**Comment by vishal0071** [comment]
https://www.androidfilehost.com/?w=files&flid=73985
You can find fdroid standards compatible builds (Play Services-less build) on above link.

As for the reason, as it states on their app webpage
https://f-droid.org/wiki/page/com.amaze.filemanager
'We can't build this version: The build for this version was manually disabled. Reason: cluttered with jars'
