### ISSUE TITLE
App Manager sort by size not working

### ISSUE THREAD

**Issue by UziTech** [arpitkh96/AmazeFileManager#304]
When trying to sort apps by size ascending or descending it sorts them by name ascending

**Comment by altintorr** [comment]
Hi,

In AppsList.java, line 199 to 203 : 
```
                    a.add(new Layoutelements(new BitmapDrawable(getActivity().getResources(),
                            BitmapFactory.decodeResource(getActivity().getResources(), R.drawable.ic_doc_apk_grid)),
                            object.applicationInfo.loadLabel(p).toString(), object.applicationInfo.publicSourceDir,
                            object.packageName, object.versionName, Futils.readableFileSize(f.length()),f.length(), false,
                            f.lastModified()+"", false));
```

object.versionName is put as LayoutElement.symlink. Any reason of that?
I think it will be better to put the apk path stored in 'f', like this, applications will be sort as files (FileListStorer.java line 74).

Modif tested on 3.1.2 b6 and worked : 
![phone](https://cloud.githubusercontent.com/assets/17279264/20858785/5ceb0758-b94d-11e6-8ecc-752e59de3863.jpg)

**Comment by vishal0071** [comment]
@altintorr please create a pull request if you fixed it! Will be appreciated (:
