### ISSUE TITLE
FTP server cannot access external SD card

### ISSUE THREAD

**Issue by pegelanomalie** [arpitkh96/AmazeFileManager#312]
I use your file manager on a Sony Xperia Z2 under Marshmallow, and simply love it. However, for (probably not only) me the built-in ftp server feature is both highly interesting and frustrating in it's current form, as it seems to be confined to serving the internal SD card (i guess via /storage/simulated/0). Can you change it so it serves either the chosen home directory or the root directory instead, so we can serve our external SD cards with it? :)

**Comment by vishal0071** [comment]
Yep, not a problem.
