### ISSUE TITLE
Leave out types when sorting by name

### ISSUE THREAD

**Issue by jroldroyd** [arpitkh96/AmazeFileManager#314]
When the Sort By Name option is in use, please do not keep interspersing the file type titles "Files" and "Directories" repeatedly every time the type changes from the previous. It wastes a lot of space. Just leave them out when Sort By Name is in use.

Thanks.

**Comment by ssixty** [comment]
I would also like this change, I find it makes it harder to skim scroll through a long list.

**Comment by ugurtufekci** [comment]
I am really interested with this project especially with sort problems. Can you explain this problem ? I did not catch what you mean.  @jroldroyd

**Comment by vishal0071** [comment]
I didn't notice this issue. My apologies. But if I understand correctly, then what you mean is to omit out files and directories titles in list when sorting as name. If that's what you mean, then I'm sorry can't do that, as titles as part of UX, and making this change will make the UX inconsistent. You can always use Directory sort mode from action mode menu and choose either files/folders on top.
@ugurtufekci what do you mean by "sort problems"? The only one that I'm aware of is app manager unable to sort as size, that too has already been fixed.

**Comment by ugurtufekci** [comment]
#304 you mean this issue already fixed ? @vishal0071

**Comment by vishal0071** [comment]
Well, I did today. Only lost my usb cable to test the changes. But it's most likely fixed.

**Comment by mericbalgamis** [comment]
Thank you for info
