### ISSUE TITLE
GET_CONTENT with type image/* not working on Samsung Galaxy Nexus (Android 4.3)

### ISSUE THREAD

**Issue by nkuznetsow** [arpitkh96/AmazeFileManager#317]
On Samsung Galaxy Nexus (Android 4.3) when Amaze starts by Intent with action GET_CONTENT and type image/*, after selecting image file the caller receive resultCode == RESULT_CANCELED and null data in onActivityResult.

Example video https://drive.google.com/open?id=0B7dIyUwl_dKJX2toNHcwRXJuUDA

It may affect other devices and others os versions.

**Comment by phoenix26** [comment]
try change singleinstance to singletop in androidmanifest file it may fix your problem. Good luck
