### ISSUE TITLE
Request: New shortcut icon

### ISSUE THREAD

**Issue by tribakzero** [arpitkh96/AmazeFileManager#321]
Please, when you create a new home shortcut, let the button get it's own icon, don't brand it with amaze icon, you can even add a little icon like Uninstall Shortcut does ( https://play.google.com/store/apps/details?id=net.nanabit.uninstallshortcut ). Then I know what's that icon about and where it came from.

**Comment by vishal0071** [comment]
You can edit icons from launcher, see Nova
