### ISSUE TITLE
Crash in landscape mode (beta 2)

### ISSUE THREAD

**Issue by hawkeye116477** [arpitkh96/AmazeFileManager#324]
Welcome! Newest beta shuts down after running.
Nvidia Shield Tablet
Android 6.0.1

**Comment by phoenix26** [comment]
any log? if you installed app from play,just report when app crashed so they can check logs else you have to share your crash logs

**Comment by hawkeye116477** [comment]
Ok, I reported

**Comment by vishal0071** [comment]
Did you try wiping the app data from system settings?

**Comment by hawkeye116477** [comment]
Yes. On Nexus 7 2012 with Android 6.01 - crash too. While on my phone with the Android 5.1 working properly. While beta 1 worked properly everywhere.

**Comment by vishal0071** [comment]
Fixed in #4b
