### ISSUE TITLE
Where is SMB?

### ISSUE THREAD

**Issue by nazar-pc** [arpitkh96/AmazeFileManager#325]
I'm looking for Open Source file manager to replace ES.
This project declares SMB support (which I need and which is missing in some other projects).
But I can't find it in UI.
I have version 3.1.0 from Google Play on Nexus 6P with Cyanogen Mod 13 (Android 6.0.1).

**Comment by phoenix26** [comment]
use "+"(plus) button in main screen click SMB Connection and use custom ip if you are lookin for this :D

**Comment by nazar-pc** [comment]
Wow, it didn't seem obvious for me at all. I was looking for it in side menu. Anyway, I found it now and it works, thanks!
