### ISSUE TITLE
"File Manager" stole source code (commercial use)

### ISSUE THREAD

**Issue by brainscript** [arpitkh96/AmazeFileManager#326]
I don't know if you already know about the [File Manager](https://play.google.com/store/apps/details?id=com.filemanager.free) app on Google Play. The "developer" of it (["RAT"](https://play.google.com/store/apps/dev?id=5543014516084274398)) **stole your source code**, renamed the app, added ads and "republished" to on Google Play.

![...](https://cloud.githubusercontent.com/assets/8706734/18875993/3ffad808-84c8-11e6-80f9-fd37a9e976f6.png)

["RAT"](https://play.google.com/store/apps/dev?id=5543014516084274398) also stole the source of @mikepenz 's awesome [wallsplash](https://play.google.com/store/apps/details?id=com.mikepenz.unsplash) app. Please report him.
I really hate seeing people do stuff like this and even earn money this way.

**Comment by phoenix26** [comment]
i can't check this app on google play (not allowed to my country) but if this app is free,they can republish/distrubute it under the GNU license.(ads means not commercial) if he sells that app by usd in google play, yes you can report him. i do not have much information about license violation.(btw i hate them as well)

**Comment by vishal0071** [comment]
Item not found, perhaps he removed it.

**Comment by brainscript** [comment]
@vishal0071 Still there.

**Comment by brainscript** [comment]
@phoenix26 The app also has in-app payments as you can see on the screenshot.

**Comment by brainscript** [comment]
@phoenix26 It's quite obvious, right? :cat: 

![screenshot_2016-09-27-20-54-22](https://cloud.githubusercontent.com/assets/8706734/18887537/c84774ba-84f4-11e6-9b03-28ea3d983a73.png)

**Comment by vishal0071** [comment]
Maybe it shows just because of cache... Wipe cache n data of play store and try again.

**Comment by vishal0071** [comment]
What a cheap ass banner XD

**Comment by brainscript** [comment]
Yep, and I can still view the app in the browser.

**Comment by vishal0071** [comment]
I tried on several vpns' too.. Not visible in my country it says. Anyways, you can just report it if it does not have its source code published anywhere. If he has published his source code, he's not violating the license. Simple as that.

**Comment by brainscript** [comment]
@vishal0071 Makes sense. When you search for File Manager or take a look at the developer's page on the Google Play website it's no longer listed, so I guess Google must have done something ... jay! :smile_cat:

**Comment by vishal0071** [comment]
Great!

**Comment by phoenix26** [comment]
i'll check and report it too (when i reached,now it does not appear in google play)

**Comment by Poussinou** [comment]
Hi @VishalNehra 

I found [this app](https://play.google.com/store/apps/details?id=com.awesome.filemanager) on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GNU GPL v3 license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide some screenshots of your own app.

**Comment by VishalNehra** [comment]
@Poussinou thanks for reporting. I've sent in a formal mail to the developer to remove the app. In case he doesn't, I'll go ahead for the removal process myself.

**Comment by Poussinou** [comment]
OK :)

**Comment by Poussinou** [comment]
@VishalNehra I also found [this one](https://play.google.com/store/apps/details?id=com.exfileexplorer.filemanagerpro) and [this one](https://play.google.com/store/apps/details?id=com.exfileexplorer.filemanager). Please report them :) I hate so much these copiers...

(+ [this one](https://play.google.com/store/apps/details?id=com.awesome.filemanager) and [this one](https://play.google.com/store/apps/details?id=com.alc.filemanager) are still alive...)
