### ISSUE TITLE
[Interface improvements] Smaller (height) list elements, "by-columns" properties

### ISSUE THREAD

**Issue by Salamandar** [arpitkh96/AmazeFileManager#327]
You can see here screenshots from ES and Amaze : we can see way much content in ES. And we can see the folder content count.
That's the main reason why I don't use Amaze daily (with the SD space analyzer feater from ES).
Would it be possible to have multiple display options ?
![amazevsesexplorer](https://cloud.githubusercontent.com/assets/6552989/18968584/e111a376-8689-11e6-8c29-67c1179f9965.png)

**Comment by vishal0071** [comment]
What do you mean by multiple display options?

**Comment by XiNFINiTY242** [comment]
Maybe He means multiple tabs... But already Amaze has multiple tabs... :/

**Comment by ascuccaro** [comment]
I think he means something like having a compact option and "comfortable" option. I agree in that it feels like too much space wasted having two bars at the top and haveing name separators between directories and files and that we have too few elements displayed. See instead MiXplorer: 

Default theme: 

![screenshot_20160930-114953](https://cloud.githubusercontent.com/assets/20978858/18996233/ea191720-8705-11e6-98e4-31f3234e2c0f.png)

Custom theme: 

![screenshot_20160930-115522](https://cloud.githubusercontent.com/assets/20978858/18996232/ea182cac-8705-11e6-9de4-3d48764aed1e.png)

Amaze: 

![screenshot_20160930-115715](https://cloud.githubusercontent.com/assets/20978858/18996234/ea1b1552-8705-11e6-80ba-e0d19a9dabc4.png)

![screenshot_20160930-115959](https://cloud.githubusercontent.com/assets/20978858/18996235/ea1cf4b2-8705-11e6-9f3e-e046097e53fc.png)

![screenshot_20160930-120031](https://cloud.githubusercontent.com/assets/20978858/18996236/ea1d97fa-8705-11e6-945f-2a173a5a8181.png)

**Comment by vishal0071** [comment]
Well, if you want a small display you can probably scale down the dpi. I always do that and I have about 8 items visible at one time. 
Each item's positioning and size is according to design guidelines. Changing anything to our own will, will ruin the UX.

**Comment by ascuccaro** [comment]
Is it possible to scale own the dpi for a single app?

**Comment by vishal0071** [comment]
Yes, there are various per-app dpi xposed modules.

**Comment by ascuccaro** [comment]
Oh, I see. I don't have Xposed installed.

**Comment by vishal0071** [comment]
Some custom roms have this feature built in too, like DU, Omni, Cataclysm etc.

**Comment by Salamandar** [comment]
Yeah, that's exactly it. And in Amaze the modification dates are "merged" with the file names whereas in ES or MiX they are in a separate column. It's cleaner. 
And you cant asx everyone to change dpi, no everyone has xposed. Not everyone has the knowledge to.

**Comment by Salamandar** [comment]
By the way, which design guidelines ?

**Comment by vishal0071** [comment]
@Salamandar 
https://material.google.com/layout/metrics-keylines.html#metrics-keylines-keylines-spacing

**Comment by Salamandar** [comment]
So you're an Amaze dev and you change the DPIs for your own app ? And you don't think this should be possible in-app ?
And BTW it's not because Google wrote Design guidelines that they are perfect. Yes they are good in a majority of cases, but not all. Not this one.

**Comment by vishal0071** [comment]
You can always switch to grid view to see more elements on a single screen. And as for the DPI change, that's just my personal taste. I change the DPI of whole UI, that's just how I like the system. I'm not changing the DPI of app only. Now, suppose for a sec I do make items small, now the whole UI is large while items on Amaze will be small and out of sync with the system. For eg. switching from System settings to Amaze, the user will feel Amaze as bloated UI. I hope you understand now.

**Comment by Salamandar** [comment]
That's why ES Explorer is leaving the choice to the user : The app is just like the user likes.
> the user will feel Amaze as bloated UI
And in the real world, ES is the most used explorer app :)
