### ISSUE TITLE
Do you import translations from Transifex?

### ISSUE THREAD

**Issue by nazar-pc** [arpitkh96/AmazeFileManager#332]
I've greatly updated translations for Ukrainian language, but it didn't make into latest beta update (on Google Play).
I've also seen #329 with direct merge of translation update. I'd forbid these to avoid data loss when uploading translations from Transifex.

**Comment by vishal0071** [comment]
You're absolutely right! I guess I got lazy and didn't check up on how to merge transifex changes. Could you be kind enough and guide me? I am using it for first time.

**Comment by nazar-pc** [comment]
Absolutely the same here (just added to one of my projects).
The only way I've seen is to click on language, click on resource and then download file, completely manual process.
I haven't explored the ways to integrate it nicely.

**Comment by vishal0071** [comment]
Very well then, thanks for informing (:

**Comment by nazar-pc** [comment]
I found this: http://docs.transifex.com/integrations/github/
Will try to add for my project and see if it works.

**Comment by vishal0071** [comment]
Great!

**Comment by vishal0071** [comment]
Got anything? I ended up updating manually. Figured from your link above that I would need to deploy certain classes on my own server to act as middleman to handle sync from both websites. I have worked on Apache Tomcat locally before but have no experience in deploying on real servers online. Guide me if possible?

**Comment by nazar-pc** [comment]
They also have Docker container. I've prepared config for it, but didn't deploy it just yet. I'm wondering why they don't have direct integration with GitHub out of the box.

**Comment by vishal0071** [comment]
Yea! ):
Do update me when you get it working.

**Comment by nazar-pc** [comment]
Sure, I will
