### ISSUE TITLE
New file/folder is created in wrong directory

### ISSUE THREAD

**Issue by dkbz** [arpitkh96/AmazeFileManager#333]
There is a bug when you try to create new file/folder which already exists. Steps to reproduce:

1. Go to a directory which you have write permission to (eg. "/storage/emulated/0").
2. Try to create directory "testdir1".
3. Directory "testdir1" is created in "/storage/emulated/0"
4. Try to create directory with the same name "testdir1".
5. You get an error "file already exists" and a chance to provide another name.
6. Type "testdir2".

Observed behaviour:
7. Directory "testdir2" is created in "/storage/emulated/0/testdir1".

Expected behaviour:
7. Directory "testdir2" is created in "/storage/emulated/0".

Similar problem occurs when you try to create file with the same name, but in this case you get "operation failed" and second file is not created at all.

I think that this bug may stem from the fact that in `mkDir` method from `MainActivityHelper` class you call `mkdir` function with parameter `file.getPath()`, which points to the wrong path. You should probably use something like `ma.CURRENT_PATH` instead. The same goes for `mkFile` method.

**Comment by vishal0071** [comment]
Nice catch!
