### ISSUE TITLE
Request: Share a folder and recursively save files to Drive / Dropbox / other

### ISSUE THREAD

**Issue by aidenlangley** [arpitkh96/AmazeFileManager#335]
Can't currently select a folder and "Share". Would love to be able to share a folder and have the contents saved to Drive or Dropbox.

**Comment by Yowlen** [comment]
This service would definitely be appreciated.
While I'm at it, I'd like to add a request for a specific cloud service that's severely lacking in pretty much every file manager I've tried: Mega.nz

**Comment by techwebpd** [comment]
can it be like in es file explorere where you can connect many cloud drives google, one drive, yandex drive, box, dropbox and many others

**Comment by TLuigi003** [comment]
I second what @techwebpd said
If you don't want to overload the app you could make installable modules/plug-ins/add-ons so people who want a basic manager can have it
Just an idea
Regards~

**Comment by vishal0071** [comment]
I am already working on the plugin in a private repo, so it you gotta wait until I finish up.

**Comment by vishal0071** [comment]
Alright guys, cloud plug-in is out for Amaze and you can perform this share like a simple copy/paste of the folder to any of the services supported. Cheers.

https://play.google.com/store/apps/details?id=com.filemanager.amazecloud
