### ISSUE TITLE
[Theme] Colors and naming

### ISSUE THREAD

**Issue by rpiotaix** [arpitkh96/AmazeFileManager#338]
I'm trying to organize a little the code about theming.

Curently, colors are represented as an array of hex values and are mainly referred to as the index of their position in this array.
Few questions about them:
1) How have they been chosen? I didn't manage to find any 'named' color for them, only approximates.

2) Using http://chir.ag/projects/name-that-color i was able to 'almost' name all of them:
#F44336     Pomegranate
#e91e63     Amaranth
#9c27b0     Seance
#673ab7     Purple Heart
#3f51b5     San Marino
#2196F3     Dodger Blue
#03A9F4     Cerulean
#00BCD4     Robin's Egg Blue
#009688     Persian Green
#4CAF50     Fruit Salad
#8bc34a     Sushi
#FFC107     Amber
#FF9800     Orange Peel
#FF5722     Orange
#795548     Roman Coffee
#212121     Mine Shaft
#607d8b     Lynch
#004d40     Aqua deep

Even if the colors are not exactly the ones behind these names, i'm going to name them this way in an Enum and see where it leads me. Do you think it is possible to use the 'correct' color for each name (for consistency's sake)?

**Comment by vishal0071** [comment]
https://material.google.com/style/color.html#color-color-palette
Seems like a nice idea!

**Comment by rpiotaix** [comment]
Oh! Perfect!
I'm going to use these names, then.
