### ISSUE TITLE
Directory loop

### ISSUE THREAD

**Issue by wilco375** [arpitkh96/AmazeFileManager#339]
I was trying to paste a copy of a folder inside that folder, but it got into an endless loop copying and pasting folders into each other. Now I can't seem to remove this folder with the I-dont-know-how-many subfolders... (Not even with rm -rf using a terminal emulator)﻿

**Comment by phoenix26** [comment]
haha lol yes you are right i just tested it and copy feature does not work under api <19 getting this error:
 java.lang.NoSuchMethodError: android.content.Context.getExternalFilesDirs

**Comment by vishal0071** [comment]
Test latest beta (v3.1.2 Beta 3+) and report.

**Comment by ildar** [comment]
I experience crashes with getExternalFilesDirs too (ICS).
And I don't see any commits fixing it. Right?
I use F-Droid version and can't check the Beta3. When the fix would be available?
BTW: F-Droid can also build betas. But you at least should mark the beta releases with tags (as usual). Thanks.
