### ISSUE TITLE
Amaze crashes when moving a file to external sd card, also when deleting file on external sd card.

### ISSUE THREAD

**Issue by travisfw** [arpitkh96/AmazeFileManager#342]
I suspect that it's a permissions issue that's new in Marshmallow. I'm using an LG G3 running Android 6.0.

**Comment by vishal0071** [comment]
Press on report button at the fc and I'll look into it.

**Comment by travisfw** [comment]
I don't get a "report" button, just "ok". http://imgur.com/a/KnBfx

**Comment by phoenix26** [comment]
whats ur android version? im sure you are using < 19 kitkat. it happens cos of context.getExternalFileDirs it came with api 19 means kitkat.Does not work under 19.

**Comment by vishal0071** [comment]
You're using fdroid version it seems. But I would need logcat, is there any way you can manually provide it to me?

**Comment by phoenix26** [comment]
btw you have to block folder copy to inside of same folder.if you don't,it copies recursively it means 
if you copy A/ to inside of A/ again : A/A/A/A/A/...... till error :p

**Comment by vishal0071** [comment]
Provide logcat and get back (or press report button on fc dialog).
