### ISSUE TITLE
how to use google+ api and conecct drive?

### ISSUE THREAD

**Issue by erginduran** [arpitkh96/AmazeFileManager#343]
i checked code it uses a plugin.

*i.setClassName("com.amaze.filemanager.driveplugin", "com.amaze.filemanager.driveplugin.MainService");*

there is no plugin in project.how can we import that plugin? and we have to use this as a plugin or can we import it as a class?

**Comment by vishal0071** [comment]
That one is deprecated. I'm working on a new one, which will include other's too (dropbox, one driver, box etc). You'll see it soon.
