### ISSUE TITLE
Dark theme has some problems.Date,permission are still dark in dark theme

### ISSUE THREAD

**Issue by erginduran** [arpitkh96/AmazeFileManager#349]
hey date,permission texts are still dark in dark theme so hard to see them.And settings background has no change (still white) after dark theme.

**Comment by vishal0071** [comment]
Are you on any beta or compiling from source?

**Comment by erginduran** [comment]
i just cloned a day ago through github git

**Comment by vishal0071** [comment]
Yea, stick with beta if this annoys you. It's gonna take a while to fix this. Blame Google's support repo, it always break something in theme after I update it.

**Comment by erginduran** [comment]
okey man i'm following this issue.Also i wait your other updates (on drive,dropbox etc.).Have a nice Sunday!

**Comment by phoenix26** [comment]
+1
same bug here.if you choose dark theme,it does not set theme properly like before.hope that you solve this problem..
