### ISSUE TITLE
After moving the data to the external SD card, these files are not deleted on the phone memory.

### ISSUE THREAD

**Issue by celentanos** [arpitkh96/AmazeFileManager#355]
After moving the data to the external SD card, these files are not deleted on the phone memory. I would then have to select the files separately and delete all manually.

Tested on Android 5.1 (Moto G)

**Comment by erginduran** [comment]
you mean /yourFolder (in root) TO /storage/emulated/0 or /sdcard ? cos its about android rules.I checked many file managers but can not perform cut operation root to sdcard

**Comment by vishal0071** [comment]
I've fixed this, will push changes soon.

**Comment by celentanos** [comment]
@erginduran 
I mean, for example:  some files cut from **/starage/emulated/0/** and paste to **/storage/sdcard1/**

**Comment by vishal0071** [comment]
Test latest beta (v3.1.2 Beta 3+) and report.
