### ISSUE TITLE
Possible Kitkat External SD Workaround

### ISSUE THREAD

**Issue by Yowlen** [arpitkh96/AmazeFileManager#357]
First off, I realize the age of this issue, so forgive me, but I happened to notice something the other day that poses a rather interesting challenge, imo.

So, I noticed that QuickPic actually allows copying/moving pictures on my non-rooted Kitkat tablet's external SD card, despite the apparent restriction forced upon third-party apps. It's worth noting this isn't the "sandbox mode" using the app's "Android/data" or "Android/obb" folders, either. This is full read/write access for the entire card. After doing some digging, it seems that while the crackdown for the "android.permission.WRITE_EXTERNAL_STORAGE" permission was in full force - only working for system and manufacturer apps, some (admittedly rare) ROMs have a workaround that isn't noticed as much. Namely, that either the "android.permission.WRITE_MEDIA_STORAGE" or "android.permission.ACCESS_ALL_EXTERNAL_STORAGE" permission seems to be allowed for non-system/non-certified apps. I've found practically no information on it, but this seems to be my best guess as to how QuickPic is bypassing the issue.

tbh, I never figured Acer for the clever type given they can't keep the majority of their devices updated properly, but there's definitely something that was done from their end here. XD

Edit: Did a bit more searching & thought of the "ACCESS_ALL_EXTERNAL_STORAGE" permission. It seems to be a developer permission from my initial research (I could be wrong, though), and I did make Developer Options visible in the tablet's settings. If that's all it takes, I think such a workaround would be easy to implement and instruct the average user to activate (Settings > About phone > Tap Build Number 6 times). It may not require Developer Options to be activated, either.

**Comment by vishal0071** [comment]
We're already using the [KitKat hack](https://github.com/arpitkh96/AmazeFileManager/blob/master/src/main/java/com/amaze/filemanager/filesystem/MediaStoreHack.java) but haven't had chances to test it, without being the device with ourselves. 
We're already using those permissions, it's not a permission thing. Anyways, let's not dig into this again, shall we?

**Comment by Yowlen** [comment]
Sorry, I wasn't aware on all the particulars, nor that you already did it. The latter probably because Amaze doesn't work w/ the external SD card on my aforementioned tablet, so unless this is a specific build option that isn't enabled by default, I can only conclude there's a bug in its activation or it's not the method QuickPic uses.

**Comment by vishal0071** [comment]
There's not a bug anywhere, hacks sometimes work sometimes don't. And QuickPic guys probably use different workaround. I might contact them about this though.

**Comment by Yowlen** [comment]
The CM guys took over the project a while back, adding advertisements & their own proprietary cloud storage. I'm using the last version released by the original developer (4.5.2, available on their site here: http://alensw.com/en/ ), so this is the person you'll probably wanna contact.

**Comment by vishal0071** [comment]
Alright! Thanks for the information (:

**Comment by Yowlen** [comment]
I did some more experimenting, and it seems your workaround actually does work. I had only tried deleting before, but I tried copying and it seems to work. The problem was that my tablet suffers from issue #355, so it wouldn't delete properly when I tried earlier. Sorry for the trouble. XD

**Comment by vishal0071** [comment]
Gald to know!

**Comment by georgiev-ilian** [comment]
I'm using it on Android 4.4.2 and when I try to copy a file to external storage it says Operation unsuccessful.

**Comment by vishal0071** [comment]
@georgiev-ilian a logcat would really help if possible?

**Comment by georgiev-ilian** [comment]
https://gist.github.com/georgiev-ilian/22a11c9c46f9479828b7f5490c2eb910

**Comment by georgiev-ilian** [comment]
I will try to debug it later but it seems it's not working properly on every device.
