### ISSUE TITLE
files or folders not deleted in /data/misc/wifi

### ISSUE THREAD

**Issue by murkom** [arpitkh96/AmazeFileManager#359]
Make new file or folder in /data/misc/wifi.
Try to delete. It says "deleting" then "done", but nothing is really deleted.

It used to happen in usb otg flash drive also. Don't have one to try again to see if it continues do happen.

**Comment by vishal0071** [comment]
I'll look into it.

**Comment by murkom** [comment]
Forgot to say. Version 3.1.1 from f-droid.
Phone is LG G2, cm13 without gapps.

**Comment by vishal0071** [comment]
Should be fixed with latest beta v3.1.2 beta 7
