### ISSUE TITLE
request: change ownership

### ISSUE THREAD

**Issue by murkom** [arpitkh96/AmazeFileManager#360]
Amaze lacks hability to change ownership of files and folders. It would be nice to have that.

**Comment by vishal0071** [comment]
You can do that from properties dialog.

**Comment by murkom** [comment]
I can change permissions, but can't see nothing about ownership. What am i missing?
Here's a screenshot. Thanks.
http://imgur.com/REzCx2V

PS: i also can't see anywhere the owner of files/folders. The file in screenshot should show "wifi" as owner and group.

**Comment by vishal0071** [comment]
My bad, I didn't read your issue clearly. Yes, you can't change the owner of a file from Amaze. I think this feature is out of the bounds of a file manager. You can just simple type the command in terminal instead. What say?

**Comment by murkom** [comment]
Don't think the terminal is practical in phone. In computer it's my best friend, but typing in touchscreen is a lot slower.
In my opinion this option should be there, but it's your call.
Amaze is great, anyway ;)

**Comment by vishal0071** [comment]
Great! Not now, but I've planned to implement a separate activity for properties screen, so maybe this feature can be added there. But that's a future enhancement, so it's gonna take time. Till then use any terminal emulator app (:
