### ISSUE TITLE
[Request] Manage files stored in external USB OTG storage

### ISSUE THREAD

**Issue by mattpalermo** [arpitkh96/AmazeFileManager#362]
It is not possible to manage the files stored in an external USB OTG storage device connected to an android device using AmazeFileManage. This is possible with the new in-built android file manager but this do not provide the same user experience as Amaze does. It would be very useful and fairly imperative to Amaze's goal of being a file manager that Amaze be able to handle this connected file system.

The problem appear to be that Android handles USB OTG storage in a very non-unix-ie way as suggested by this stack exchange thread: https://stackoverflow.com/questions/32201169/how-app-can-access-files-on-usb-otg-storages-in-android-6-0-api-level-23-witho. This thread suggests that the Storage Access Framework would have to be used to interact with the external file system.

Unfortunately I cannot find an open source file manager which can achieve this yet.

**Comment by murkom** [comment]
You can manage usb otg. Check /mnt/media_rw/
Sometimes before it shows up i must enter /mnt/runtime/ and go back. Then it shows usb otg drive inside media_rw. I have no ideia why this happens, but it works.
I also get errors saying copy unsuccessful and amaze reports size and free space wrong on flash drive.

**Comment by vishal0071** [comment]
Starting KitKat, we must use SAF to access volatile mounts (as OP pointed). Your approach works on prior versions. I'm working on it's implementation, so please be patient.

**Comment by vishal0071** [comment]
It's working now. You should be on v3.1.2 beta 6+

**Comment by mattpalermo** [comment]
Thanks, I'll give it a try this weekend.

**Comment by mattpalermo** [comment]
@vishal0071 I gave it a try today and it seemed to work. I was able to see the files in my external drive and create new folders. However I wasn't able to copy files from my internal storage to my external storage. For example, it would be really helpful to copy some of my photos to easily share with family. When browsing under the "OTG" section, the interface was different. It didn't even seem like Amaze. I didn't have functionality like copy and paste. Am I using it incorrectly?

Note I tested this using v3.1.2 beta 7,

Thanks

**Comment by vishal0071** [comment]
You need to press on select in bottom right from the screen.

**Comment by mattpalermo** [comment]
Ah I see now. 😄 It's working! Sorry, I should have read the prompt more carefully.

**Comment by jrajujayaraman** [comment]
redmi note 10 pro reads the ntfs supported external hard disk of 1 tb.But moto g32, and tecno camon 20 pro do not.
The android version is 13 on both the phones. As the thread is related to this query. i post here and would like to have your view vishalnehra
