### ISSUE TITLE
Copy & paste resulted in a file with lots of extra stuff at the end

### ISSUE THREAD

**Issue by shane-kerr** [arpitkh96/AmazeFileManager#364]
I use copy of a 439-byte file in one directory, then paste it into another directory and end up with a 60 kilobyte file with lots of crap (non-ASCII characters) at the end. The Amaze text browser hides this, so you can't see it there, but other programs can see the contents.

**Comment by vishal0071** [comment]
Test latest beta (v3.1.2 Beta 3+) and report.

**Comment by shane-kerr** [comment]
Where can I find that? (I don't see 3.1.2 beta in the releases tab.)  Do I need to build the APK myself? (That would suck, because I have never done that and it would turn a few minutes of testing into hours of learning how to compile an Android application.)

**Comment by vishal0071** [comment]
Opt in to beta testing from play store or download apk from (AFH)[https://www.androidfilehost.com/?w=files&flid=73967]

**Comment by shane-kerr** [comment]
Okay, v3.1.2 Beta 3 from androidfilehost.com seems to work fine.

Looking at the change history, commit 2aac9c2928af4a589621ee5635d6d2ed387a725b seems like a plausible reason that this is now fixed. Nice. :)
