### ISSUE TITLE
can't open pdf with another app

### ISSUE THREAD

**Issue by SynapseScribe** [arpitkh96/AmazeFileManager#3674]
amaze 3.8.4

clicking on a pdf show a popup to download some amaze extension

i already have a pdf reader, but for some reason list of capable apps is not shown

i remember this to be working before, something must have been changed on last update

i tried clearing amaze defaults but the button is greyed out in android settings

android11

i also have another file manager that is properly opening it with the pdf viewer

**Comment by VishnuSanal** [comment]
@fusionneur strange! please try turning `Disable player intent filters` on from `Settings -> Behavior`

(ping @VishalNehra)

**Comment by VishalNehra** [comment]
I'll check, but a screen recording would help a lot. You should ideally see all apps capable of opening pdf file.
