### ISSUE TITLE
copy changes md5

### ISSUE THREAD

**Issue by ka223** [arpitkh96/AmazeFileManager#369]
Hi,

I moved some files at the SD card to another folder.

The md5sum is changed by copying or moving files.
And the moved files are not deleted from the source folder.

Play Store Version 3.1.1
OS: CM 13.1

Regards

**Comment by vishal0071** [comment]
Thanks for taking time to writing here. It's been fixed already try latest beta (opt in on beta at play store or download from afh).

**Comment by ka223** [comment]
Same problem at the 3.1.2 beta4 Version.

**Comment by vishal0071** [comment]
Are they not getting deleted while moving?

**Comment by ka223** [comment]
Moving is working. But the md5sum changes when I copy a file.

**Comment by pejakm** [comment]
Most probably this is a duplicate of #330. @ka223 Try with text files larger than 60 kiB.

**Comment by vishal0071** [comment]
Fixed in latest beta v3.1.2 beta 5, test and report.

**Comment by pejakm** [comment]
> Fixed in latest beta v3.1.2 beta 5, test and report.

Confirmed, it's fixed. Thanks!

**Comment by ka223** [comment]
@pejakm
md5 was changed by larger files than 60kib

@vishal0071 
I can confirm that it is fixed. 
Thanks!
