### ISSUE TITLE
ftp server and system app

### ISSUE THREAD

**Issue by oztan** [arpitkh96/AmazeFileManager#374]
i should choose which files want to show.
And when i try delete system apps, amaze crash.

**Comment by vishal0071** [comment]
Kindly leave a logcat, or press on report button in fc dialog, and let me know here. 
If you are pointing towards ftp, then we'll add the custom path feature later, for now it shows internal memory only.h

**Comment by oztan** [comment]
Yes ftp, thank you for reply, that is my searching answer.
