### ISSUE TITLE
cast error

### ISSUE THREAD

**Issue by RuijiePan** [arpitkh96/AmazeFileManager#379]
Information:Gradle tasks [:clean, :generateFdroidDebugSources, :generateFdroidDebugAndroidTestSources, :mockableAndroidJar, :prepareFdroidDebugUnitTestDependencies, :assembleFdroidDebug]
Warning:WARNING: Dependency commons-logging:commons-logging:1.1.1 is ignored for fdroidDebug as it may be conflicting with the internal version provided by Android.
/Users/JiePier/AndroidStudioProjects/AmazeFileManager2/src/fdroid/java/com/amaze/filemanager/activities/MainActivity.java
Error:(342, 49) 错误: 找不到符号
符号:   变量 UNKNOWN
位置: 类 HFile
Error:(811, 59) 错误: 不兼容的类型: OpenMode无法转换为int
Error:(932, 35) 错误: 不可比较的类型: OpenMode和int
Error:(932, 57) 错误: 不可比较的类型: OpenMode和int
Error:(1452, 129) 错误: 不兼容的类型: int无法转换为OpenMode
Error:(1459, 52) 错误: 找不到符号
符号:   变量 LOCAL_MODE
位置: 类 HFile
Error:(1465, 62) 错误: 找不到符号
符号:   变量 LOCAL_MODE
位置: 类 HFile
Error:(2185, 32) 错误: 不可比较的类型: OpenMode和int
Error:(2197, 32) 错误: 不可比较的类型: OpenMode和int
Error:(2250, 46) 错误: 找不到符号
符号:   变量 UNKNOWN
位置: 类 HFile
Error:(2264, 56) 错误: 不兼容的类型: int无法转换为OpenMode
Error:(2284, 45) 错误: 不兼容的类型: int无法转换为OpenMode
Error:(2488, 54) 错误: 不兼容的类型: int无法转换为OpenMode
/Users/JiePier/AndroidStudioProjects/AmazeFileManager2/src/main/java/com/amaze/filemanager/fragments/Main.java
Error:(435, 61) 错误: 不兼容的类型: OpenMode无法转换为int
/Users/JiePier/AndroidStudioProjects/AmazeFileManager2/src/main/java/com/amaze/filemanager/fragments/TabFragment.java
Error:(231, 71) 错误: 不兼容的类型: OpenMode无法转换为int
Error:(318, 80) 错误: 不兼容的类型: OpenMode无法转换为int
/Users/JiePier/AndroidStudioProjects/AmazeFileManager2/src/main/java/com/amaze/filemanager/fragments/ZipViewer.java
Error:(561, 68) 错误: 不兼容的类型: OpenMode无法转换为int
Error:(562, 61) 错误: 不兼容的类型: OpenMode无法转换为int
Error:Execution failed for task ':compileFdroidDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED
Information:Total time: 11.352 secs
Information:19 errors
Information:1 warning
Information:See complete output in console

**Comment by vishal0071** [comment]
Compile playDebug instead of fdroidDebug (select flavours from lower left menu on Android Studio)
