### ISSUE TITLE
Unable rename "folder" to ".folder"

### ISSUE THREAD

**Issue by armitageone** [arpitkh96/AmazeFileManager#381]
I try to rename folder "folder" to ".folder" and got fail message, but it renamed to "upfolder.folder" where "upfolder" is upper level folder.

Was: \sdcard1\folder
Want: \sdcard1\\.folder
Got: \sdcard1\sdcard1.folder

**Comment by altintorr** [comment]
hello,

in 3.1.2 beta 6, it seems rename process is not working...
I made this modification in Main.java lines 1115 to 1122 on my local code : 

From
```
if (!MainActivityHelper.isNewDirectoryRecursive(new HFile(openMode, CURRENT_PATH + "/" + name)) &&
                        Operations.isFileNameValid(name)) {
                    if (openMode == OpenMode.FILE)
                        MAIN_ACTIVITY.mainActivityHelper.rename(openMode, f.getPath(), CURRENT_PATH + "/" + name, getActivity(), BaseActivity.rootMode);
                    else
                        MAIN_ACTIVITY.mainActivityHelper.rename(openMode, (f).getPath(), (CURRENT_PATH + "/" + name), getActivity(), BaseActivity.rootMode);

                }
```

To

```
                if (!MainActivityHelper.isNewDirectoryRecursive(new HFile(openMode, CURRENT_PATH + "/" + name)) &&
                        Operations.isFileNameValid(name)) {
                        MAIN_ACTIVITY.mainActivityHelper.rename(openMode, (f).getPath(), (CURRENT_PATH + "/" + name), getActivity(), BaseActivity.rootMode);

                }
```
The new code willh force the slash at the end of CURRENT_PATH in all cases. From my understanding, problem was linked to the slash missing between CURRENT_PATH & 'name'
I didn't find any bug on rename process with this modification.

**Comment by vishal0071** [comment]
Fixed!
