### ISSUE TITLE
Dialogs disappear on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [arpitkh96/AmazeFileManager#383]
When I perform these sequences of events, the dialog on screen disappears:

Sequence 1:
1. Click on "..." (More Options)
2. Click on Sort
3. Click on Sort By
4. Orientation Change

Sequence 2:
1. Click on "..." (More Options)
2. Click on Sort
3. Click on History
4. Orientation Change

Sequence 3: 
1. Open Side Drawer
2.  Click on Settings
3 Click on:
a. Theme
b. Hide Mode
c. Number of columns in grid view
d. Directory Sort Mode
e. Sort By
f. Archive Extract Folder
g. Zip Create Folder"
4. Orientation Change

Sequence 4:
1. Open Side Drawer
2.  Click on Settings
3 Click on Color
4. Click on:
a. Primary Color
b. Accent Color
c. Icon Color
5. Orientation Change

**Comment by vishal0071** [comment]
Seems like you did quite some work listing these (:
Android framework doesn't provide any implementation to preserve dialog on rotatiin change. So, I'm afraid this is never gonna be solved. I'm not saying it's not possible, but preserving a dialog isn't that much usable thing to do for the hardwork it requires, also it doesn't effect the UX that much (given only limited interaction with them). 
Hope this answers

**Comment by reverse-unina** [comment]
Hi, 

I attach you an excerpt from Android guidelines for dialogs. 
Source: https://developer.android.com/guide/topics/ui/dialogs.html

The Dialog class is the base class for dialogs, but you should avoid instantiating Dialog directly[...] 
[AlertDialog et al.] classes define the style and structure for your dialog, but you should use a **DialogFragment** as a container for your dialog. The DialogFragment class provides all the controls you need to create your dialog and manage its appearance, instead of calling methods on the Dialog object.

Using DialogFragment to manage the dialog ensures that it correctly handles **lifecycle events such as when the user presses the Back button or rotates the screen.**

**Comment by reverse-unina** [comment]
I am a researcher exploring the Android failures and i am finding this kind of failure very common. 
I am contacting you and other developers to know if it is an expected behaviour of the app or it is due to  the limitations of the Android framework, as you noticed.

I would appreciate to receive your feedbacks

Sincerely,
Reverse-VinRiccio
