### ISSUE TITLE
Scrollable View changes position on Device Rotation

### ISSUE THREAD

**Issue by reverse-unina** [arpitkh96/AmazeFileManager#385]
When I perform this sequence of events, the scrollable view on screen goes back to the top:

1. Open Side Drawer
2. Click on Settings
3. Scroll Down
4. Orientation Change

**Comment by reverse-unina** [comment]
I am a researcher exploring the Android failures and i am finding this kind of failure very common.
I am contacting you and other developers to know if it is an expected behaviour of the app or it is due to the limitations of the Android framework, as you noticed.

I would appreciate to receive your feedbacks

Sincerely,
Reverse-VinRiccio

**Comment by vishal0071** [comment]
Yes, basic UX elements are not generally preserved in the apps (dialogs/preference screen), as they have limited amount of interaction with user, and hence don't need all the complexity in programming to actually preserve them at screen rotation.
