### ISSUE TITLE
Files renaming is somewhat broken

### ISSUE THREAD

**Issue by nazar-pc** [arpitkh96/AmazeFileManager#390]
Renaming file to any name, let's say `txt.txt` says operation was unsuccessful, but file is actually renamed to `0txt.txt`, zero is prepended to whatever target name I specify for the file.

v3.1.2 Beta 6

**Comment by vishal0071** [comment]
Strange! Works fine for me. Where does your file exist? I mean, locally or smb or otg?

**Comment by nazar-pc** [comment]
Well, just checked in another directory (internal SD card on Nexus), looks like the same as #381.
Was it published already?

**Comment by vishal0071** [comment]
I suppose, yes. Try this apk and report (this is having different signature so you won't be able to update this version).

**Comment by nazar-pc** [comment]
Works fine, thanks!

**Comment by vishal0071** [comment]
Use this one until I announce next beta. After that uninstall this one and manually update.

**Comment by pejakm** [comment]
I can confirm the new apk fixed this.
