### ISSUE TITLE
Cannot copy any file to SD card

### ISSUE THREAD

**Issue by pejakm** [arpitkh96/AmazeFileManager#391]
v3.1.2 Beta 6

This bug wasn't present in previous build. Also, copying from SD card to SD card is not working.

Android 6.0.1.

Build from #390 is affected too.

**Comment by germanfr** [comment]
I can't copy to my SD card also. Amaze shows I have no write permissions and it won't copy any files but it doesn't show any error. I can create/delete files from the FAB, though.

<img src="https://cloud.githubusercontent.com/assets/10391266/21081109/33341098-bfc0-11e6-9b12-965a59c8ced6.png" height="480" />

I'm running version v3.12 Beta 6 on Android 6.0.1 (CM 13).

**Comment by vishal0071** [comment]
I finally got my hands on a device to test! Expect fix in next beta (:

**Comment by vishal0071** [comment]
Try latest beta (v3.1.2 beta 7+) and report

**Comment by germanfr** [comment]
I updated it but it still doesn't work for me. It now shows an error dialog. And still showing I have no write permissions.
<img src="https://cloud.githubusercontent.com/assets/10391266/22288997/a994f23c-e2f9-11e6-9528-82b9c78d94bd.png" height="200"/>

**Comment by vishal0071** [comment]
Alright, I can confirm its finally fixed with [aff66649d10921563e43edf13c3acf3a4a21ed2d](https://github.com/arpitkh96/AmazeFileManager/commit/aff66649d10921563e43edf13c3acf3a4a21ed2d)
Expect new beta in a day or two, with the fix.
