### ISSUE TITLE
OTG_USB on android 6.0.1

### ISSUE THREAD

**Issue by VEMTK** [arpitkh96/AmazeFileManager#392]
otg usb on android 6.0.1 can not read file

**Comment by vishal0071** [comment]
File opening is not working as of yet as there is no defined path for the files's existence in the system. I'll try to implement a workaround to it. Keep up to date with latest beta updates.

**Comment by mattpalermo** [comment]
Does this relate to my feature request at issue #362 that was already implemented?

**Comment by vishal0071** [comment]
Working on v3.1.2 beta 7+
