### ISSUE TITLE
Crashes on several actions

### ISSUE THREAD

**Issue by maverick74** [arpitkh96/AmazeFileManager#393]
Steps to reproduce:

1.Open Amaze
2.Enter Downloads folder
3.Create a New Folder (or any other option)

Behavior: Crashes (always!)

System: Android 4.2.2 (Jelly Bean)
Amaze: 3.1.2 Beta 6

Additional info: No matter what version i have, stable or beta, both crash! Actually, i never had a version of amaze that didn't crash on this functions

**Comment by vishal0071** [comment]
Thanks for writing back. This is really strange. Press on report button (send feedback on Nougat) in fc dialog so that I can view the logs.

**Comment by maverick74** [comment]
Hi.
I think I've done it all right, but don't know where the report went. Hope you got it...

**Comment by vishal0071** [comment]
Alright found the problem. I'm really sorry you had to face the problem for so much time. Seems like the method getExternalFilesDirs is not supported on Android 4.3- by some OEMs. Actually we don't have all the devices, so we can't test everything. I hope you understand. 
Anyways, lemme work on fix. I assure you it'll be fixed in upcoming beta's. I might contact you personally for some alpha testing too, if you won't mind.

**Comment by maverick74** [comment]
No. Not at all. Be my guest.

It was becoming a bit frustrating not being able to use it. All other FM were not an alternative for just because I'm a kind of gpl-license-lover and amaze it's the only decent FM that shares this philosophy.

**Comment by vishal0071** [comment]
Alright! Send over your email id then (you can type it in the report dialog message of the fc).

**Comment by maverick74** [comment]
Not getting where that it exactly... But I'm already enrolled in beta testing... I can also keep a eye on github for any releases and manually update...

**Comment by vishal0071** [comment]
Before sending the report from fc dialog there is a message box to write into.

**Comment by maverick74** [comment]
Done. I'll receive news from you by mail, right?!

**Comment by maverick74** [comment]
It's working great on beta 7. THANKS!!! 😁. I don't know if I should close the bug or not, but it's fixed!!!
