### ISSUE TITLE
Doesn't attach files when used with Gmail. 

### ISSUE THREAD

**Issue by pwhart** [arpitkh96/AmazeFileManager#394]
When starting in Amaze I can successfully select a file, share it via Gmail and it attaches fine. However, when starting in Gmail (eg replying to a message) and I try to use Amaze to attach a file, it doesn't attach. No problem navigating through folders, I see the dialog box saying "Pick a file" but when I select a file and then it returns me to Gmail, the file has not been attached.

**Comment by vishal0071** [comment]
Issue related to Gmail instead
