### ISSUE TITLE
Feature : folder picker 

### ISSUE THREAD

**Issue by davidbilly** [arpitkh96/AmazeFileManager#395]
hi @vishal0071, as continue previous  topic for folder picker feature. 

I hopefully amaze file manager can consider implement folder picker feature, so that external app can get the folder path.

Thanks for the great open source project 👍 

#212

**Comment by vishal0071** [comment]
Yes, we'll work on it.

**Comment by vishal0071** [comment]
Implemented in v3.1.2 Beta 12
