### ISSUE TITLE
[3.1.2/Beta 6] Renaming files and folders is buggy.

### ISSUE THREAD

**Issue by JORGETECH** [arpitkh96/AmazeFileManager#396]
When I rename a file or a folder in Amaze 3.1.2 Beta 6 at first it fails but the second time I try it actually renames it but not with the name it was given in the dialog but with a quite random name which is often the original name with the name of the folder where the file or folder is located. This happened renaming files in the external SD card but I did not try with internal storage (and I won't make the risk).

My device:
Huawei Ascend G6-U10
Android 4.4.2 (EMUI 3.0)

**Comment by vishal0071** [comment]
Try with internal storage

**Comment by JORGETECH** [comment]
Same behaviour is present with the internal storage.

**Comment by vishal0071** [comment]
Wait for another beta

**Comment by vishal0071** [comment]
Should work fine with v3.1.2 beta 7+
