### ISSUE TITLE
Root not being used on Nougat

### ISSUE THREAD

**Issue by Nama** [arpitkh96/AmazeFileManager#399]
Hi,
I use Amaze since lollipop, stock and several custom ROMs on a Nexus 5.

Since then removing systemapps doesn't works.
Root features worked on lollipop and marshmallow but they don't since I use a custom nougat ROM.
I tried with these two ROMs.
https://forum.xda-developers.com/google-nexus-5/development/rom-cm12-unofficial-hammerhead-gapps-t2969820
https://forum.xda-developers.com/google-nexus-5/development/rom-pure-nexus-substratum-t3477787

SuperSu notices me about Amaze that it is requesting root permission, but Amaze fails with "copy unsuccessful" and such. 
I have currently no other device for testing, but it seems for me that this is a global error since every other app can use root. 
But I couldn't find any other issues regarding this problem, which means that it is not a global problem...

**Comment by vishal0071** [comment]
Opt in to beta testing. We've made some major changes to root implementation, and it's release is yet to come. So expect new v3.1.2 beta 7 very soon. Test and report if that new version also has these problems.

**Comment by Nama** [comment]
I'm since months on beta, forgot to mention, sorry. 
Very nice, I'm excited for beta 7!

**Comment by vishal0071** [comment]
Lol, looking towards the participants column on right side XD

**Comment by vishal0071** [comment]
Test latest beta and report

**Comment by Nama** [comment]
I did yesterday.
Gave permission again to use root, no errors, but nothing happens. No renaming, no new copied files, no deleting.
I deleted App-Data and tried again. But Everything root is not working (ya, I enabled it in setting).
I tried to copy files from internal storage to /system/etc/ and renaming and deleting files in /system/etc/ (ya, I know what I was about to do).
Uninstalling System-Apps in the App Manager tells with a toast "Done", but the app is still on the system.
Can I provide you some logs or something?
Am I the only one experiencing this?

**Comment by vishal0071** [comment]
No, actually I never read your issue completely. I just saw supersu and skipped to conclusion that new implementation of su would fix this. 
Expect fix in a day or two with another beta.

**Comment by Nama** [comment]
Newest Beta.
I deleted /system/etc/hosts.
I copied hosts from the internal storage to /system/etc/ and even removed some system apps.
Root works again :D
Thanks dood

**Comment by vishal0071** [comment]
You're welcome (:
