### ISSUE TITLE
Amaze Text Editor - Cannot open root files

### ISSUE THREAD

**Issue by gsantner** [arpitkh96/AmazeFileManager#405]
Hi there,
I am currently on Amaze v3.1.1 on Android 7.1.

I enabled the Root option in app settings and I can browse through all directories (using Amaze File Manager), so not just `/sdcard/`. Also the root popup appeared, so I think root works in general with the app.
But if I click on any file which is owned by root, and select "Amaze Text Editor" it says error. And I cannot view or edit the content.
Please allow the Editor to also load the `Root` setting/preference, and load it with the right permissions/user.

Editing/Opening user owned files does work as expected.

**Comment by vishal0071** [comment]
Been fixed in upcoming beta, opt in to beta testing from play store.

**Comment by gsantner** [comment]
thx!
