### ISSUE TITLE
Question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [arpitkh96/AmazeFileManager#4084]
My scanner just got some additional checks in January, and on today's update of Amaze reported:

```
! repo/com.amaze.filemanager_121.apk declares flag(s): usesCleartextTraffic
! repo/com.amaze.filemanager_121.apk declares sensitive permission(s):
  android.permission.READ_EXTERNAL_STORAGE android.permission.REQUEST_INSTALL_PACKAGES
  android.permission.REQUEST_DELETE_PACKAGES android.permission.MANAGE_EXTERNAL_STORAGE
  android.permission.QUERY_ALL_PACKAGES
! repo/com.amaze.filemanager_121.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

Now, the storage permissions are clear, and so I already added them to the "allow-list" with a proper explanation. I'll add the app manager permissions as well (just noticed there's an app manager integrated – was already about to ask if you'd have any self-updater included, I hope you don't?) `usesCleartextTraffic` I could not figure. Where are unencrypted connections established to?

![image](https://github.com/TeamAmaze/AmazeFileManager/assets/6781438/8efb300c-47a7-448b-baef-c52a94fdec1e)

Ah, and then there's that `DEPENDENCY_INFO_BLOCK`, which is easy to get rid of:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

**Comment by TranceLove** [comment]
@IzzySoft One example of the use of clear text http traffic, is the stream from remote server feature. Under the hood we are fetching the remote stream and launches a tiny http server local to the Android device, and let the corresponding app stream from this local HTTP stream.

**Comment by IzzySoft** [comment]
Ah, so it's only "for connections to the http server locally on the device"? Set that explanation then, thanks!

Will you deal with the `DEPENDENCY_INFO_BLOCK` in future releases?

**Comment by TranceLove** [comment]
@IzzySoft Sure. Will work on them. Stay tuned.

**Comment by IzzySoft** [comment]
Thanks a lot!
