### ISSUE TITLE
Unable to save photo from gallery app,  but can save multiple

### ISSUE THREAD

**Issue by mdavis-xyz** [arpitkh96/AmazeFileManager#4093]
**Describe the bug**
I have taken photos with my camera app. I want to move/copy them to another folder on my phone besides the default one. When I "share" a photo from my gallery app, I get an error. 
When I share multiple photos in one go, it works fine.

**To Reproduce**

1. Take a few photo with a camera app
2. Open up the gallery app (I'm using the Samsung default photo gallery app
3. Select two photos
4. Click the share icon
5. Select Amaze
6. select a folder to save them in
7. click save
8. go back to gallery app
9. select only one photo
10. click the share icon
11. select Amazon

**Expected behavior**

For both single and multiple photos, Amaze asks me where to save the file(s). Once I select a location, files get saved there.

**Actual behavior**

I am able to save multiple photos as expected.
But when sharing a single photo, as soon as the first app opens up Amaze, I see an error:

> Invalid, unsupported, or no URI was provided

This is prior to me being able to select the folder.

Note that I'm just trying to copy a jpeg from one folder on my phone to another. I expect that jpeg files are supported.

**Screenshots**

<img src="https://github.com/TeamAmaze/AmazeFileManager/assets/7035647/8b55e506-e165-409e-8d58-3b77fcefae0f" height=500 width=250/>
<img src="https://github.com/TeamAmaze/AmazeFileManager/assets/7035647/cad8734f-efe2-406a-8671-bb1a41bc6961" height=500 width=250/>
<img src="https://github.com/TeamAmaze/AmazeFileManager/assets/7035647/eff8a188-c823-4084-989e-f1408cc09af3" height=500 width=250/>
<img src="https://github.com/TeamAmaze/AmazeFileManager/assets/7035647/1408487a-f665-4a09-a81f-1e63f81942ca" height=500 width=250/>
<img src="https://github.com/TeamAmaze/AmazeFileManager/assets/7035647/57e42f0c-24ef-4c76-b4e0-c95b72aef69c" height=500 width=250/>
<img src="https://github.com/TeamAmaze/AmazeFileManager/assets/7035647/a7ca157f-693d-4c4f-a690-6a0ee59beaa5" height=500 width=250/>

**Smartphone (please complete the following information):**
 - Device: Samsung S20 SM-G981B
 - OS: Android 13
 - Rooted:No
 - Version: 3.10 (this bug has been occurring for at least a few weeks)

**Additional context**

I'm not sure if this is a duplicate of issue #1242, #1623 or #2651, because I don't know the terminology to use for this type of file sharing.

**Comment by pastk** [comment]
On my custom Android 9 the "Save as..." function (when some file is shared from some app) stopped working with the same message as above on a screenshot in a 3.10 (F-Droid) version.

I have downgraded to 3.8.4 and it works again! 
So seems like a regression.
