### ISSUE TITLE
Errors located in F-Droid MainActivity

### ISSUE THREAD

**Issue by Technologx** [arpitkh96/AmazeFileManager#410]
I changed every java file that had com.amaze.filemanager to my own package id but in this file I get a error with these 2 imports and I'm not sure how to fix it. I'm new to Android coding and I've been using open source projects like this to try & learn any help I get is greatly appreciated.

```
import com.amaze.filemanager.IMyAidlInterface;
import com.amaze.filemanager.Loadlistener;
import com.stericson.RootTools.RootTools;
```

**Comment by vishal0071** [comment]
Refer to MainActivity in play. Fdroid is currently out of date and due to be updated.
Build play debug from lower left button in android studio.

**Comment by Technologx** [comment]
So would it be safe for me just to remove the FDroid stuff since I don't use it?

**Comment by vishal0071** [comment]
Yes, but I wouldn't recommend it. Just built the play version for now and keep up to date with upstream here as we'll be fixing fdroid very soon.
Just think if fdroid as a subset of play's main activity. So, you wouldn't miss much without it.

**Comment by Technologx** [comment]
Alright so the app will still be functional after removing that? Like I said I don't use F-Droid not really sure what F-Droid is.

**Comment by vishal0071** [comment]
Yes, it's safe to remove.

**Comment by Technologx** [comment]
Alright I ended up deleting the fdroid folder and I'm getting errors dealing with MainActivity.

**Comment by vishal0071** [comment]
Change build flavour from bottom left in Android studio to play debug

**Comment by Technologx** [comment]
Where exactly I'm using a Mac here's a screen on how my Android Studio looks.

[](http://upicme.technologx.com/images/ScreenShot2017-01-15at10.37.45PMf4634.png)

**Comment by vishal0071** [comment]
Build variants

**Comment by Technologx** [comment]
So what file is this associated with?

`drawerHeaderView.setBackgroundResource(R.drawable.amaze_header_2);`

**Comment by vishal0071** [comment]
Sets background to header in drawer. Is there any problem with that?

**Comment by Technologx** [comment]
Yea I changed it to `drawerHeaderView.setBackgroundResource(R.drawable.andromanager_header_2);` which is telling me `Error:(2536, 78) error: cannot find symbol variable andromanager_header_2` and I changed the image name.

**Comment by Technologx** [comment]
So do you know how I can fix that error?

**Comment by vishal0071** [comment]
See if you renamed the drawable or not.

**Comment by Technologx** [comment]
I did I double checked all the folders I made a new vector.xml and changed it in the code so hopefully it'll work.

**Comment by vishal0071** [comment]
It's not an xml it's a drawable resource. Find it in drawable-dpi folders.

**Comment by Technologx** [comment]
I did it still showed a error so I'm making a drawable vector to fix the issue

**Comment by Technologx** [comment]
Alright the vector drawable threw errors so I fixed the issue with a simpl copy and paste but I run across the following when building the apk.

Warning:WARNING: Dependency commons-logging:commons-logging:1.1.1 is ignored for playDebug as it may be conflicting with the internal version provided by Android.
Warning:WARNING: Dependency commons-logging:commons-logging:1.1.1 is ignored for playRelease as it may be conflicting with the internal version provided by Android.
Warning:WARNING: Dependency commons-logging:commons-logging:1.1.1 is ignored for fdroidDebug as it may be conflicting with the internal version provided by Android.
Warning:WARNING: Dependency commons-logging:commons-logging:1.1.1 is ignored for fdroidRelease as it may be conflicting with the internal version provided by Android.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.codehaus.plexus.util.FastMap$1) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.codehaus.plexus.util.FastMap$2) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.codehaus.plexus.util.FastMap$3) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.codehaus.plexus.util.cli.CommandLineUtils$1) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.apache.maven.scm.util.ThreadSafeDateFormat$1) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.apache.regexp.REDemo$1) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.apache.commons.logging.LogFactory$1) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.apache.commons.logging.LogFactory$2) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.apache.commons.logging.LogFactory$3) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.apache.commons.logging.LogFactory$4) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.apache.commons.logging.LogFactory$5) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.apache.commons.logging.impl.SimpleLog$1) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.apache.commons.logging.impl.WeakHashtable$1) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.apache.commons.logging.impl.WeakHashtable$2) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Information:BUILD SUCCESSFUL
Information:Total time: 2 mins 41.181 secs
Information:112 errors
Information:4 warnings
Information:See complete output in console

**Comment by Technologx** [comment]
I'd just like to get these issues fixed so I could use the app and try to make money to keep from losing my forum & I'm running outta time.

**Comment by rpiotaix** [comment]
The most important part of what you've pasted is the 5th line starting from the end.

**Comment by vishal0071** [comment]
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.amaze.filemanager.ui.views.Indicator" on path: DexPathList[[zip file "/data/app/com.technologx.andromanager-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)

Seems like there is not indicator class in your source

**Comment by Technologx** [comment]
@rpiotaix Which line you've got me confused?

**Comment by Technologx** [comment]
See @vishal0071 that's where I'm confused here's my indicator.java file.
https://ghostbin.com/paste/v4mw5

**Comment by vishal0071** [comment]
Like I said.. you forgot to modify xmls. Problem isn't with Indicator.java but with xmls. Android studio will assist you, if you would open the ones having problem with.

**Comment by rpiotaix** [comment]
Sorty, i was with the mobile and i didn't see the stacktrace you pasted :s

**Comment by Technologx** [comment]
So I think I may have finally got it all figured out there was a line in the mainactivity.xml I forgot to change. I'm fixing to test it to see if it still crashes on me.

**Comment by Technologx** [comment]
Do any of you know how I can go about adding admob ads to this app?

**Comment by Technologx** [comment]
Alright now I'm running into this:
````
Warning:WARNING: Dependency commons-logging:commons-logging:1.1.1 is ignored for playDebug as it may be conflicting with the internal version provided by Android.
Warning:WARNING: Dependency commons-logging:commons-logging:1.1.1 is ignored for playRelease as it may be conflicting with the internal version provided by Android.
Warning:WARNING: Dependency commons-logging:commons-logging:1.1.1 is ignored for fdroidDebug as it may be conflicting with the internal version provided by Android.
Warning:WARNING: Dependency commons-logging:commons-logging:1.1.1 is ignored for fdroidRelease as it may be conflicting with the internal version provided by Android.
Warning:string 'ftp_preference_port_auto_chkbx' has no default translation.
Warning:string 'ftp_preference_port_auto_chkbx_summary' has no default translation.
Warning:string 'ftp_preference_port_edit' has no default translation.
Warning:string 'ftp_preference_port_edit_summary' has no default translation.
/Users/Technologx/Desktop/Android Projects/New/AndroManager/src/main/res/values-ast-rES/strings.xml
Error:(414) Error: "ftp_preference_port_auto_chkbx" is translated here but not found in default locale [ExtraTranslation]
Error:(415) Error: "ftp_preference_port_auto_chkbx_summary" is translated here but not found in default locale [ExtraTranslation]
Error:(416) Error: "ftp_preference_port_edit" is translated here but not found in default locale [ExtraTranslation]
Error:(417) Error: "ftp_preference_port_edit_summary" is translated here but not found in default locale [ExtraTranslation]
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.codehaus.plexus.util.FastMap$1) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.codehaus.plexus.util.FastMap$2) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.codehaus.plexus.util.FastMap$3) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.codehaus.plexus.util.cli.CommandLineUtils$1) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.apache.maven.scm.util.ThreadSafeDateFormat$1) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.apache.regexp.REDemo$1) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.apache.commons.logging.LogFactory$1) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.apache.commons.logging.LogFactory$2) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.apache.commons.logging.impl.SimpleLog$1) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.apache.commons.logging.LogFactory$3) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.apache.commons.logging.LogFactory$4) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.apache.commons.logging.LogFactory$5) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.apache.commons.logging.impl.WeakHashtable$1) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.apache.commons.logging.impl.WeakHashtable$2) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Information:BUILD SUCCESSFUL
Information:Total time: 4 mins 37.97 secs
Information:116 errors
Information:8 warnings
````
& I can't open the app because it keeps crashing. Could I just delete the translations since I have my own translations project setup?

**Comment by Technologx** [comment]
Anyone know how to fix this?

**Comment by Technologx** [comment]
Dang still no help on this
