### ISSUE TITLE
Return subfolder search in version 3.10

### ISSUE THREAD

**Issue by eddieofny** [arpitkh96/AmazeFileManager#4104]
On Amaze 3.8.4, whenever I would use the search bar, the app would search all subfolders. This was especially useful for finding things in the root file system. I just tried this in Amaze 3.10 and that functionality was gone. I had to return to 3.8.4 to find what I needed. Please bring this feature back.

**Comment by VishnuSanal** [comment]
@eddieofny thanks for reaching out! I am sorry to hear you bumped into problems. you can expand where the search gets performed by pressing on "not finding what you are looking for?" button. the third search mode (deep search) is exactly the same as the one in previous versions of amaze. you can see this discussion page for more details on the search behavior.
