### ISSUE TITLE
Unable to save files via content:// uris

### ISSUE THREAD

**Issue by Alexander--** [arpitkh96/AmazeFileManager#411]
I have a content provider that exports a file via `content://` uri. When I start an editor with `ACTION_VIEW`, your editor correctly loads my file. But when I press "save", it attempts to write a file called "/filename", where "filename" is a string, contained in "_display_name" column of my provider. That is — your editor is trying to save a file in *filesystem root* instead of actual file I am giving you. In addition, your editor is requesting root access, but I have already allowed to write the file in my ContentPvider! This is not how this should be done!

If you insist on dealing with `File` objects, you should handle `content://` Uris like this: 1) retrieve a ParcelFileDescriptor, corresponding to Uri 2) Open a file, called "/proc/self/fd/" + decriptor integer:

    ParcelFileDescriptor pfd = getContentResolver().openFileDescriptor(uri, "rw");
    int integerDescriptor = pfd.getFd();
    File theFile = new File("/proc/self/fd/" + integerDescriptor); // e.g. '/proc/self/fd/14'

You should be able to write data to that file, and even memory-map it, change it's permissions etc.

That way you won't rely on having file path in  "_display_name" column. In addition, your code will work with non-filesystem-based ContentProviders (such as Google Drive etc.).

**Comment by vishal0071** [comment]
Alright! Thanks for recommending the fix. Will fix it soon.

**Comment by Alexander--** [comment]
@vishal0071 Note, that my suggestion is a bit inflexible: it will only work that way if you have been given full read-write access. If you have been given only read access, this line will fail:

    ParcelFileDescriptor pfd = getContentResolver().openFileDescriptor(uri, "rw");

If you want your code to be failure-proof, it may be a good idea to fall back to read-only descriptor if opening for write fails:

    try {
      ParcelFileDescriptor pfd = getContentResolver().openFileDescriptor(uri, "rw");
    } catch (Exception e) {
      ParcelFileDescriptor pfd = getContentResolver().openFileDescriptor(uri, "r");
    }

e.g. use "r" instead of "rw" for file access flags.

In that case you might not be able to write to the '/proc/self/fd/14' (because it was not open for wring).

If you want to check if the file is a proper filesystem file (e.g. not a pipe or socket), you can do it like this:

    new File("/proc/self/fd/" + pfd.getFd()).isFile(); // will return false for files not in filesystem, e.g. pipes or sockets

Once you have closed a `ParcelFileDescriptor`, the corresponding `/proc/self/fd/number` will vanish.

Also note, that some ContentProviders might not be able to give you "rw" file. E.g. Google Drive is storing files on servers… So they might give you either a read-only `ParcelFileDescriptor` (download socket) or write-only `ParcelFileDescriptor` (upload socket).

Also if you *really* want the real path (for example, the provider is not giving you write access, but you would like to try with root), you can try to resolve the name like this:

    final String realPath = new File("/proc/self/fd/" + pfd.getFd()).getCanonicalPath();

This may work because `/proc/self/fd/number` is a symlink and `getCanonicalPath` tries to resolve all symlinks under the hood. This will not work in all cases, because to resolve a Linux symlink you need a read access (actually "execute" access…) to all directories in the path. So if file is in a tricky directory (such as internal directories of apps in post-Nougat Android), you might receive a permission error from `getCanonicalPath`.

**Comment by vishal0071** [comment]
Thanks for your detailed explanation. But as you said earlier, since file opening is working, that means we're successfully getting InputStream from the uri already using 
    getContentResolver#openInputStream(uri)
But while saving the file, the author probably forgot implementing this, and is simply using 
    uri#getPath
So, I think simply opening an OutputStream and writing to it will do the things just fine
    getContentResolver#openOutputStream(uri)
Plus, the method you defined is not documented anywhere (or atleast I didn't read about it anytime before). Could you site the source of it, it sounds like really useful. Just not really sure to depend on it, as I doubt Google will likely change these provider paths without any notice (clearly the didn't provide any standard API to access the paths of ContentProviders and they don't want us to do the same). 
So according to me, this solution is probably not convenient even if it does work.

**Comment by Alexander--** [comment]
> Thanks for your detailed explanation. But as you said earlier, since file opening is working, that means we're successfully getting InputStream

@vishal0071 correct

> So, I think simply opening an OutputStream and writing to it will do the things just fine

But getting InputStream does not mean, that you are guaranteed to get OutputStream. I mean, your editor is behind `ACTION_VIEW` intent filter, and unlike `ACTION_EDIT`, `ACTION_VIEW` does not imply write access. E.g. most apps, using `content://`, will start file viewers like this:

    // just and example, exact way to build Uri may wary
    final Uri uri = DocumentsContract.buildDocumentUri(FileProvider.AUTHORITY, resolved);

    final Intent view = new Intent(Intent.ACTION_VIEW, uri)
       .addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);

    startActivity(view);

Note, that code above does not set `FLAG_GRANT_READ_URI_PERMISSION` — so trying to call `getOutputStream` on that uri is going to fail unless the ContentProvider is totally public (is not protected by any permissions). Also there is nothing, stopping the ContentProvider from hardcoding access-mode into the Uri (e.g. something like `content://authority/path/to/file?mode=readonly`). In general, you can not just assume availability of specific access mode on the Uri.

> the method you defined is not documented anywhere

Which part of it is not documented?

[ParcelFileDescriptor#getFd](https://developer.android.com/reference/android/os/ParcelFileDescriptor.html#getFd%28%29) is a documented method in Android standard library.

The fact that `getInputStream`/`getOutputStream` are implemented on top of `openFileDescriptor` is supposed to be a "common knowledge": Google does not exactly communicates it well, but the only mandatory way to implement getting files from ContentProviders is implementing `openFileDescriptor` — only descriptor-based streams can be passed around by Binder (so only pipes, sockets and memory-backed or filesystem-backed files). You would know this if you spent any amount of time studying ContentProviders.

The existence of integer file descriptors is not some implementation details, it is a cornerstone of Unix. All C library calls: `open()`, `close()`, `read()`, `write()`, `mmap()` etc. are operating on integer file descriptors, provided by Linux kernel. Binder can be used to get files from ContentProviders because of the way file descriptors work.

[`procfs`](http://tldp.org/LDP/Linux-Filesystem-Hierarchy/html/proc.html) is a documented Linux filesystem, [part of Linux kernel API](https://www.kernel.org/doc/Documentation/filesystems/proc.txt). Unlike `sysfs` or `devfs` (filesystems behind /sys/ and /dev/) it is considered a public API: it is stable and used in countless Linux programs. Linux programs like `top` and `ps` are using it exclusively and usual Linux compatibility guarantees  apply to it — Linux kernel devs won't just suddenly change paths or something.

>  I doubt Google will likely change these provider paths without any notice (clearly the didn't provide any standard API to access the paths of ContentProviders and they don't want us to do the same).

Google does not own Linux kernel nor does it control the kernel development. They are famous for breaking their own API, but they have never broken Linux APIs. Saying that something might not be stable because Google does not document it is silly — for example, they don't document C library calls, but they still support them and they are *a lot more stable* than most Android APIs because every single C program in the world (including native parts of Android) is depending on them. In case you need absolute confirmation, Android Compatibility Test Suite is [using `/proc/`](https://android.googlesource.com/platform/cts/+/fef5e2c/tools/device-setup/TestDeviceSetup/src/android/tests/getinfo/RootProcessScanner.java) and in Android N Google they have taken special care to keep `/proc/self/` accessible to user apps (accessing `/proc/number` files of other apps requires root since then).

**Comment by Alexander--** [comment]
A few useful notes from developer in charge of Storage Access Framework: https://commonsware.com/blog/2016/11/21/consuming-content-be-flexible.html

**Comment by vishal0071** [comment]
Can't thank you enough for your valuable response. I'll be sure to implement it in our text editor. This will also be helpful in solving various bugs with our otg and sd card handlers.

**Comment by vishal0071** [comment]
@Alexander-- I'm getting FileNotFoundException when trying to get the FileOutputStream at 
```/proc/self/fd/[otg content provider uri fd]```
with the rw mode for ```ParcelFileDescriptor```
And I don't have any other content provider to test this with. What do you recommend.

Ps. getting```getContentResolver#openOutputStream(uri)```is working just fine.

Pps. I tried opening a RandomAccessFile with rw mode and it gives ChannelNotWritable exception.

**Comment by Alexander--** [comment]
@vishal0071 As I mentioned above, each ContentProvider is free to do things their way. This includes being buggy and messing with your assumptions. I am not sure, which provider you are speaking about (the authority string or some pointers, how to get the apk, would not hurt), but the provider in question probably does not support getting seekable file descriptors at all.

getOutputStream internally just asks for write-only descriptor:

    public final @Nullable OutputStream openOutputStream(@NonNull Uri uri, @NonNull String mode)
            throws FileNotFoundException {
        AssetFileDescriptor fd = openAssetFileDescriptor(uri, mode, null);
        try {
            return fd != null ? fd.createOutputStream() : null;
        } catch (IOException e) {
            throw new FileNotFoundException("Unable to create stream");
        }
    }

You can use the trick I described above to learn a bit more about received descriptor. Pause the app in debugger while the descriptor is open. Log into device with root shell and run some shell commands:

    # get pid of your process, for example 20005
    ps | grep amaze 

    # look at the descriptor in question
    ls -al /proc/20005/fd/* | grep <descriptor integer>

It will most likely resolve to something like `pipe:[878353]`. `File#canWrite` might be of some use to detect such case.

**Comment by vishal0071** [comment]
Alright, I've possibly fixed this issue. Thanks to you again for all your help. Wait for another beta coming out very soon to test this (:

**Comment by Alexander--** [comment]
@vishal0071 Thanks.

One last note: you probably do not want to use `ContentResolver#.query(...)` — if remote ContentProvider process crashes, all it's client processes, connected via that method, will be killed (the OS basically assumed, that users of that method can not recover, such as e.g. an address book not being able to recover from crash of system ContactsProvider). `ContentResolver#acquireUnstableContentProviderClient` allows you to obtain weak reference to provider and handle it's crashes without being killed yourself.
