### ISSUE TITLE
[KitKat][3.1.2/Beta 6] Copying operation hangs when trying to copy files from SD card to /data

### ISSUE THREAD

**Issue by JORGETECH** [arpitkh96/AmazeFileManager#412]
As the title says when I try to copy some files and/or folders from the SD card to to /data (For example an application folder) it is continuously stuck on the copying operation and I have to force close the app to stop it. Before commenting please take into consideration that I have already tried to do the same task with another file manager (In my case CyanogenMod File Manager) and there are no issues with that app. I also applied the SD card fix for KitKat.

Another interesting thing is that it only happens inside a subdirectory of an app's data folder (instead of "/data/data/com.name/" it happens inside "/data/data/com.name/folder/".

System Information:
-Android 4.4.2 (Huawei EMUI 3.0) [SD Fix applied].
-Device: Huawei Ascend G6-U10.
-Amaze version: 3.1.2 Beta 6 (Google Play)

Edit: I also discovered that Amaze crashes if I try to delete the app's data folder where I tried to copy the files in (it does not crash in CyanogenMod File Manager when doing the same thing).

**Comment by vishal0071** [comment]
Copy SD Card file into internal file system first, before copying it into root.

**Comment by JORGETECH** [comment]
Thanks for the answer, any hopes this is fixed for latest beta?

**Comment by vishal0071** [comment]
No actually. Copying from sd card  to root will involve writing lot more complex algorithms. So, I guess implementing it  isn't worth when you can simply copy to internal memory first.
