### ISSUE TITLE
crash mails get confused response linking to a wrong issue

### ISSUE THREAD

**Issue by matkoniecz** [arpitkh96/AmazeFileManager#4120]
I reported few crashes yesterday via email and got response linking to https://github.com/TeamAmaze/AmazeFileManager/issues/4014 which is unrelated issue reported long time ago

![screen](https://github.com/TeamAmaze/AmazeFileManager/assets/899988/59be8e63-2271-4f4a-ac45-1835d20475f3)

**Comment by VishnuSanal** [comment]
I checked the email & you are indeed using the official version of Amaze. please ignore the false alarms from the bot.
