### ISSUE TITLE
"you're using an un-official or outdated version of Amaze" for latest F-droid version

### ISSUE THREAD

**Issue by matkoniecz** [arpitkh96/AmazeFileManager#4121]
I got email response

> We couldn't help but notice you're using an un-official or outdated version of Amaze. Please allow us to introduce, while we're at it. Amaze is a non-profit, open source file manager for Android. No ads and all features any modern file manager would have, all this absolutely free of cost. 

(another one got #4120 response with more clear problem)

I am using latest F-droid and you link F-droid at https://github.com/TeamAmaze/AmazeFileManager?tab=readme-ov-file#downloads 

Is F-droid version unofficial after all and I should not report bugs in it?

**Comment by VishnuSanal** [comment]
https://github.com/TeamAmaze/AmazeFileManager/issues/4120#issuecomment-1991836197 :)
