### ISSUE TITLE
FAB Display Issue

### ISSUE THREAD

**Issue by XYIheng** [arpitkh96/AmazeFileManager#4134]
**Describe the bug**
Enter recent files, then click home button on amaze. FAB not display.

**To Reproduce**
see the video:

https://github.com/TeamAmaze/AmazeFileManager/assets/31406320/151cdf75-8b1c-4e27-b7e7-7540b48f5224

**Expected behavior**
The FAB should display on the home directory

**Screenshots**
![image](https://github.com/TeamAmaze/AmazeFileManager/assets/31406320/c328e374-53c6-416d-aa06-36244e61c90e)

**Smartphone (please complete the following information):**
Device: [Google Pixel 2]
OS: [Android 10]
Rooted: [No]
Version: [3.10]

**Additional context**

**Comment by VishnuSanal** [comment]
dupe #4130
