### ISSUE TITLE
android folder on sd card

### ISSUE THREAD

**Issue by pego123** [arpitkh96/AmazeFileManager#4172]
I cannot open the subfolders of the android folder on the sd card. The internal android folder works fine. All other sd card folders work also fine. But in the sd card android folder I cannot go to the end of a folder. 

The rest is very fine, thank you. 

Best regards, Peter

**Comment by VishnuSanal** [comment]
this is a known limitation, it is due to security enforcement from google, we can't do anything about it, sadly. :(
