### ISSUE TITLE
Dark theme crashes on startup with newest beta (3.1.2 Beta 7)

### ISSUE THREAD

**Issue by Yowlen** [arpitkh96/AmazeFileManager#418]
Just got the Beta 7 update from the Play Store & went to try it out, only to have it crash immediately. After reinstalling, I saw it worked fine, so I went to the settings to set things up & it crashed as I exited the settings. I then cleared the data & went one by one and found it's the dark theme that causes it. Interestingly, the dark theme works fine in the settings area, so I have to assume it's an issue specific to the main window.

**Comment by vishal0071** [comment]
Press on report button so that I can receive the logcat.

**Comment by Yowlen** [comment]
I already did during the first crash. The comment I put was generic along the lines of "I just updated & now it crashes on startup." since I wasn't aware of what the specific issue was at the time.

**Comment by JORGETECH** [comment]
I can confirm this too. I reported it using Google Play.

In the logcat I can see this interesting line:
01-24 00:43:07.684 E/AndroidRuntime(15921): java.lang.NoSuchMethodError: com.amaze.filemanager.activities.MainActivity.getColor

So yeah it is the dark theme.

**Comment by rpiotaix** [comment]
Which version of Android are you using? I can be a call to a function that is only available to recent versions.

**Comment by JORGETECH** [comment]
I am using 4.4.2 Kit Kat.

**Comment by Yowlen** [comment]
@rpiotaix Android 5.1.1 here. And unless this function you speak of is exclusive to the MainActivity, I think it's more likely a typo. As I explained in my first post, it works fine in the settings, but crashes when it goes back to the main screen and only when Dark Theme is enabled.

**Comment by rpiotaix** [comment]
https://developer.android.com/reference/android/content/Context.html#getColor(int)

Context#getColor(int) has been added in Android 6.0

I think i'm the culprit.
