### ISSUE TITLE
Cannot search or rename files within Documents

### ISSUE THREAD

**Issue by liushuqi-2022** [arpitkh96/AmazeFileManager#4180]
**Describe the bug**
In the Documents module, file search and renaming operations do not work

**To Reproduce**
1. Go to Documents module through the navigation bar
3. Execute search operation
4. Renaming files
5. See error

**Expected behavior**
The file that was just modified or searched should be displayed

**Screenshots**
<img src="https://github.com/TeamAmaze/AmazeFileManager/assets/111285450/575cf80f-5c9f-4319-a9b4-4abf28014dfd" height=600 /> <img src="https://github.com/TeamAmaze/AmazeFileManager/assets/111285450/4c7db337-41a2-4ec4-98d4-80b36e7a0d3c" height=600 /> <img src="https://github.com/TeamAmaze/AmazeFileManager/assets/111285450/bf764897-56d7-4060-8761-365f7e206c78" height=600 /> <img src="https://github.com/TeamAmaze/AmazeFileManager/assets/111285450/9ff55502-43a2-482b-8668-fef585a771c2" height=600 /> <img src="https://github.com/TeamAmaze/AmazeFileManager/assets/111285450/3d44fa92-3713-480d-b51d-211e6e2dc2d0" height=600 />

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel XL]
 - OS: [e.g. Android 8]
 - Rooted: [e.g. No]
 - Version: [e.g. 3.10]

**Additional context**

**Comment by VishnuSanal** [comment]
can't reproduce, please share the crash report with us for further debugging.
