### ISSUE TITLE
Failed to connect by SMB

### ISSUE THREAD

**Issue by ErshoffPeter** [arpitkh96/AmazeFileManager#4181]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 2]
 - OS: [e.g. Android 9]
 - Rooted: [e.g. No]
 - Version: [e.g. 3.3.4]

**Additional context**

**Comment by VishnuSanal** [comment]
Thanks for reporting. Please share the crash report for further debugging.
