### ISSUE TITLE
Amaze v3.1.2 B7 Save App unsuccessful

### ISSUE THREAD

**Issue by ka223** [arpitkh96/AmazeFileManager#420]
Hi, 

after the today's beta upgrade to v3.1.2 B7, creating app backups is not possible anymore.

Android: CM13

**Comment by vishal0071** [comment]
Well, do you get some dialog stating that copy was unsuccessful?

**Comment by ka223** [comment]
Yes
"Operation Unsuccessful"
"Following files were not copied successfully" ...

**Comment by vishal0071** [comment]
Alright, it's been already fix. Expect another beta in a day or two.
