### ISSUE TITLE
Permissions not granted warning despite actually working 

### ISSUE THREAD

**Issue by edwardbackstrom** [arpitkh96/AmazeFileManager#4207]
When opening Amaze, presented with Permission not granted. When selecting Grant, permission is already granted. Banner stays at bottom of screen indicating permissions not granted but seem to be able to access all files regardless.

<img src="https://github.com/TeamAmaze/AmazeFileManager/assets/16754060/21b8bf23-0c30-4466-9ed3-d750810e5e8c" height=600 /> <img src="https://github.com/TeamAmaze/AmazeFileManager/assets/16754060/f78dbf0f-a390-4747-a65c-07c9abc4e298" height=600 />

**Comment by VishnuSanal** [comment]
hi @edwardbackstrom, thansk for reaching out. have you granted the storage permission? (the one that we give access from a dialog box)

**Comment by edwardbackstrom** [comment]
Yes, selecting Grant from the first screenshot brings up the second. Grant is already active. Disabling and re-enabling does nothing and when returning to main app, the banner continues to stay at the bottom on the screen.

**Comment by VishalNehra** [comment]
> Yes, selecting Grant from the first screenshot brings up the second. Grant is already active. Disabling and re-enabling does nothing and when returning to main app, the banner continues to stay at the bottom on the screen.

Does the banner stay even after apo restart? If so, please mention your device details. We'll look into it

**Comment by edwardbackstrom** [comment]
I reboot my phone, problem persisted. Reboot a second time with same results. 

I have a Samsung Ultra 23 SM-S918U1
Android 14 pl Jun-01-24

**Comment by edwardbackstrom** [comment]
After the newest Android update, issue is resolved. The error was apparently caused by the OS and not the software. Thank you.
