### ISSUE TITLE
Crash - Amaze v3.1.2 Beta 7

### ISSUE THREAD

**Issue by OgreTheHorrible** [arpitkh96/AmazeFileManager#422]
Crash after update from Google Play Store. Crash was reported via 'send report' option of Android / Google. Cleared cache & data, still crashes. I have been able to replicate the crash 2 different ways:

1) Change theme from 'Material Light' to 'Material Dark'
2) Attempt to add an SMB share

As long as I do not attempt to make those changes, everything seems to work fine.

Also the 'open source licenses' screen is a blank white screen, with an iOS logo showing in front of it (screenshot attached)

RCA Maven Pro, Android 5.0, Kernel 3.10.

![screenshot_2017-01-26-20-08-54](https://cloud.githubusercontent.com/assets/25379930/22360358/bdb1954e-e403-11e6-9143-28f3f2edcd37.png)
54

**Comment by vishal0071** [comment]
See #431 for reference
