### ISSUE TITLE
ERROR: Invalid, unsupported, or no URI was provided when sending files.

### ISSUE THREAD

**Issue by fraxxio** [arpitkh96/AmazeFileManager#4223]
**Describe the bug**
When trying to send a file copy from Google cloud to Amaze I get error `Invalid, unsupported, or no URI was provided` This didn't happen before the latest update.

**To Reproduce**
1. Go to Google Cloud
2. Select any file. (I tried with JPEG and PDF)
3. Then click send copy
4. Select Amaze
5. When redirected to Amaze app error is displayed at the bottom

**Expected behavior**
A file copy should be sent to Amaze app.

**Screenshots**
<img src="https://github.com/user-attachments/assets/68f3e910-acf1-4a4b-8ea8-086f6e5c6ada" alt="image" width="400" height="auto">
<img src="https://github.com/user-attachments/assets/30586d05-ca7a-4892-8ba5-1372e210b471" alt="image" width="400" height="auto">

**Smartphone (please complete the following information):**
 - Device: Lenovo Tab P11
 - OS: Android 11 

**Additional context**
I saw on app reviews, someone is also experiencing same issue.

**Comment by ZweDen051228** [comment]
File:/storage/emulated/0/Download/GitHubDesktopSetup-x64 (1).exe MD5: 13580b276d0062f79476f38023d997e6 SHA-1: 5b7731c20822d3f99deaa610f8f76b9b997bb95c
