### ISSUE TITLE
Trying to open my files anywhere without Google

### ISSUE THREAD

**Issue by lokissonanthony** [arpitkh96/AmazeFileManager#4239]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 2]
 - OS: [e.g. Android 9]
 - Rooted: [e.g. No]
 - Version: [e.g. 3.3.4]

**Additional context**

**Comment by VishnuSanal** [comment]
issue not clear. please give us a specific issue description!
