### ISSUE TITLE
Add language selector

### ISSUE THREAD

**Issue by verdulo** [arpitkh96/AmazeFileManager#424]
Please consider adding to the application option to change language, instead on relying on system language. If such an option will be added, I will be able to contribute Esperanto translation (which is not selectable by default on Android).

**Comment by vishal0071** [comment]
It's difficult to support languages which are not supported by system.

**Comment by verdulo** [comment]
Ekde versio 4.1 Android oferas bazan subtenon por Esperanto - nomoj, de monatoj, semajntagoj estas tradukitaj; multe da aliaj androidaj programoj ebligas al uzanto ŝanĝi lingvon de fasado. Kial vi ne volas aldoni tian eblon al via programo?
