### ISSUE TITLE
rare behaviour, unknown folders . and .. leading to crash

### ISSUE THREAD

**Issue by paulle** [arpitkh96/AmazeFileManager#425]
![screenshot_20170127-191154](https://cloud.githubusercontent.com/assets/4852079/22382601/a032cad8-e4c6-11e6-880d-13a6df537b49.png)
![screenshot_20170127-191115](https://cloud.githubusercontent.com/assets/4852079/22382602/a0385282-e4c6-11e6-99af-a637a06f7ee8.png)

I don't know what is this. See screenhots: Amaze is showing 2 folders named . and ..
If I try to delete these folders Amaze is crashing (f.c.).
I tried various others file managers (solid explorer and root eplorer) but none of them is showing
the . and .. folders. I also tried in terminal as su with ls -a, but folders don't show.
I'm using android 7.0 (rooted) on a sony xperia xz. Amaze is v3.1.1 from f-droid.

**Comment by vishal0071** [comment]
Try the beta version

**Comment by paulle** [comment]
Thank you for your advice (and Amaze), installed v3.1.2beta6 and all seems ok. The . and .. folders don't show up and no crash (only did little testing in this short time)

**Comment by paulle** [comment]
Please excuse, the beta has the same behaviour as I described before. It's my error reporting everything ok, but it was only because I didn't check the show hidden files option. Excuse me.

**Comment by vishal0071** [comment]
. And .. are not files but symlinks. 
. refers to the directory itself and .. refers to the parent directory. 
For more info, see [this](http://unix.stackexchange.com/questions/63081/what-are-and-directories)

**Comment by paulle** [comment]
Thank you for pointing this out.
