### ISSUE TITLE
Shared data wrongly saved or fails to be saved

### ISSUE THREAD

**Issue by chept** [arpitkh96/AmazeFileManager#4250]
**Describe the bug**
Shared data from apps, saved via the "Save as" option either fails with `Invalid, unsupported, or no URI was provided` message or creating a *.txt file containing a description of what have been shared.
Maybe related: https://github.com/TeamAmaze/AmazeFileManager/issues/4223, https://github.com/TeamAmaze/AmazeFileManager/issues/4093

**To Reproduce**
1. Open an app that propose to export data via sharing (https://f-droid.org/fr/packages/org.zephyrsoft.trackworktime/ in my example)
2. Share data using the "Save as" Amaze option
3. Select directory where to save
4. See that the file has not been saved correctly

**Screenshots**
Option to "Save as" shared file:  
<img src="https://github.com/user-attachments/assets/bae82c99-c9cc-4eff-b4b0-c0d2b45c554d" width=50% height=50%>

After saving, the only file resulting is a *.txt:
 <img src="https://github.com/user-attachments/assets/1617b97f-370b-4748-9054-8dbe88289dcc" width=50% height=50%>

This *.txt contains a description of the data:
 <img src="https://github.com/user-attachments/assets/bc89bc25-440f-4898-8924-b334248b1ea0" width=50% height=50%>

Sometimes it just fails with `Invalid, unsupported, or no URI was provided` message:
 <img src="https://github.com/user-attachments/assets/713ecfe8-dce3-45c7-9a9b-1099c1bcf073" width=50% height=50%>

**Smartphone**
 - Device: Google Pixel Pro 7
 - OS: Graphene OS 
 - Version: 14

**Comment by VishnuSanal** [comment]
hi, thanks for the descriptive bug report! this is indeed a bug & needs to be investigated. this issue seems to be same as #4223 in the first look, we'll track it in that thread -- closing this issue for now.
