### ISSUE TITLE
Issue loading video file from SMB

### ISSUE THREAD

**Issue by tbridges42** [arpitkh96/AmazeFileManager#429]
When attempting to open video files from SMB share, the video does not load.

Looking at my debug logs, I see
`E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: smb:/username%3Apassword@ip/path/to/file`

It looks like there's a URI encoding issue there, where // is being interpreted as an escaped /, and %3A is not being interpreted as a colon.

**Comment by vishal0071** [comment]
What version of Amaze are you using?

**Comment by tbridges42** [comment]
I first noticed the issue using 3.1.1 from the Google Play store. That debug log is from my fork of the master branch about an hour ago.

**Comment by vishal0071** [comment]
But I fixed it a few days before. I request you to once opt-in to beta testing and try beta version.

**Comment by tbridges42** [comment]
What video player do you test with? I switched to the beta version, and tried a few different video players. My results:

VLC does not load any videos.
BS Player Free loads videos, but all videos show "0.0 bytes" and do not allow seeking. Some videos stop after 10-12 seconds.
ES Media Player seems to work correctly, but I want to replace ES File Explorer with Amaze.

**Comment by vishal0071** [comment]
I tested with mx player, every format was working fine.

**Comment by tbridges42** [comment]
Tested. Yes, MX Player is working fine. I wonder what the difference is with the other players I tested.

**Comment by vishal0071** [comment]
Well, perhaps their way of dealing with things you just mentioned above...

**Comment by tbridges42** [comment]
Yeah, I'm going to do some digging into how VLC handles the intents, because I really want to go as broadly open source as I can.

**Comment by vishal0071** [comment]
Ok. BTW the error you got above (FileNotFound exception) is related to icon of video in Amaze and not the streamer. You gotta check respective apps' logs to see what's going on with them.

**Comment by tbridges42** [comment]
In my testing, by URL encoding the username and password separately (and therefore not encoding the semicolon) it fixed the interactions with the other video players without breaking MX Player, and also fixed the thumbnails on remote files.

I created a pull request.

**Comment by vishal0071** [comment]
Thank you for the contribution!
