### ISSUE TITLE
Cannt use Cloud

### ISSUE THREAD

**Issue by Feadim** [arpitkh96/AmazeFileManager#4295]
I use Amaze long ago and today I bought the Amaze Cloud, but in the menu when trying to add OneDrive, Dropbox or Google Drive it shows the "please wait" and then nothing happens.  I tried reinstalling Amaze, Amaze Cloud, open the Onedrive/dropbox/google drive app manually, but nothing.

**Smartphone (please complete the following information):**
 - Device: Oppo A54
 -  OS: Android 11
 - Rooted: No
 - Version: latest

**Additional context**
My phone (and Amaze) is in spanish, I have the read/write file permissions to Amaze set on.

**Comment by VishnuSanal** [comment]
hi, thanks for reaching out. we are sorry that you run into problems. amaze cloud is actually temporarily taken down from the play store due to some issues, and it not working as expected. where did you purchase the plugin from?

**Comment by Feadim** [comment]
I bought it yesterday from google play store

**Comment by VishnuSanal** [comment]
oh, weird. we'll take a look. meanwhile, please contact us in private for the refund. apologies for the inconvenience!
