### ISSUE TITLE
Anuwat

### ISSUE THREAD

**Issue by newza0012** [arpitkh96/AmazeFileManager#4303]
[/**Describe](url
[bugreport-pond_global-UP1A.231005.007-2024-12-11-13-16-42-dumpstate_log-2328.txt](https://github.com/user-attachments/files/18191160/bugreport-pond_global-UP1A.231005.007-2024-12-11-13-16-42-dumpstate_log-2328.txt)
) the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 2]
 - OS: [e.g. Android 9]
 - Rooted: [e.g. No]
 - Version: [e.g. 3.3.4]

**Additional context**

**Comment by VishnuSanal** [comment]
this is an issue completely unrelated to the scope of this project, fromwhat I can decipher. hecne, closing. please CMIIW.
