### ISSUE TITLE
Amaze crash v3.1.2 beta 8 

### ISSUE THREAD

**Issue by OgreTheHorrible** [arpitkh96/AmazeFileManager#431]
Google Play Store update of Amaze to v3.1.2 beta 8, still crashes when trying to add an SMB share. Though at least I can change themes now. Crash reported to Google via crash reporter option. I mistakenly input the version as "3.2 beta 8" on the report though (you know just to confuse things, my bad).

Tried clearing the cache, crashes when adding SMB.
Tried clearing the cache & data, still crashes when adding SMB.

**Comment by vishal0071** [comment]
Fix coming with another beta

**Comment by vishal0071** [comment]
Test on v3.1.2 beta 9
