### ISSUE TITLE
Inconsistent date formatting in folder/file timestamps

### ISSUE THREAD

**Issue by ScenarioKG** [arpitkh96/AmazeFileManager#4312]
**Describe the bug**
The date format is inconsistent, e.g., '17 July' vs '8 Aug'.

**To Reproduce**
1. Open the file manager app
2. Observe the date formats under each folder/file name

**Expected behavior**
All folder timestamps should have consistent date formatting, e.g., month abbreviation should be of the same length.

**Screenshots**
![SCREENSHOT](https://github.com/user-attachments/assets/5e1f317b-4de0-4eed-b409-dd5a9a2db35c)

**Smartphone (please complete the following information):**
 - Device: [Google Pixel 5]
 - OS: [Android 14]
 - Rooted: [No]
 - Version: [3.10]

**Comment by VishnuSanal** [comment]
this is not a bug, IMO. please see: https://wmich.edu/writing/rules/dates
