### ISSUE TITLE
Idea: Back-button location and name

### ISSUE THREAD

**Issue by maverick74** [arpitkh96/AmazeFileManager#437]
This is just an idea: I think it would make sense to place the back button before the current location path.

Also, the back-button is in fact - it seems - an UP button (it doesn't go back in history, just to the parent directory), so renaming and rotating it would also make sense.

![header](https://cloud.githubusercontent.com/assets/14912461/22618849/51ef4daa-eadf-11e6-9d42-a3554464ab0f.jpg)

**Comment by vishal0071** [comment]
I don't agree to it. I'm sorry.
All I wanna say is, you don't put anything anywhere just because there is space available.

**Comment by maverick74** [comment]
Hi. Thank you for your reply and honesty!!!

It was just an idea. No harm/critic meant.
I have no idea or knowledge about rules of design. I know white spaces are important but I don't know any rules about it or how to use them.

So i just mentioned it from my point of view.

Still, what is your opinion about the "up button" instead of "back"? I understand android or some phones do have a "back" button that does the same thing. I would like to know your opinion on that - again, I don't know much about it...
