### ISSUE TITLE
Update german translation

### ISSUE THREAD

**Issue by OffifialMITX** [arpitkh96/AmazeFileManager#441]
I [translated missing strings](https://gist.github.com/beed8fee3759080ecb00ce3c95d595d4) up to the tutorial window since it's too large to translate via [Stringlate](https://github.com/LonamiWebs/Stringlate) (not for the app but there's too much text to work with on a phone).

**Comment by vishal0071** [comment]
I'm sorry but current version for German is [up-to-date](https://github.com/arpitkh96/AmazeFileManager/blob/master/src/main/res/values-de/strings.xml)
But you can check if you can improve any of the already translated ones and create a pull request.
