### ISSUE TITLE
[Feature request] Folder shortcuts

### ISSUE THREAD

**Issue by pchampin** [arpitkh96/AmazeFileManager#449]
It would be nice to be able to create home-screen shortcuts to open a specific folder with Amaze.

**Comment by vishal0071** [comment]
You can already do that. Select the directory you want to make shortcut of, then open the action mode menu (3dot menu) from top right.

**Comment by pchampin** [comment]
Either you misunderstood my request, or I am missing something. I see the following options in the top-right 3dot menu : Sort, History, Grid View, Set As Home, Exit (I'm using Amaze 3.1.1 from F-Droid, seems to be the last stable release).

May be you are suggesting "Set As Home", but this is not the feature that I tried to describe.

What I would like is a shortcut outside the application, on the *phone*'s home-screen, the one containing application icons, widgets and... shortcuts ;-)

**Comment by pchampin** [comment]
Ok, I think I got it; the version on the Play Store is 3.1.2 Beta9 is ahead of the version on F-Droid. Sorry about the noise.

**Comment by vishal0071** [comment]
You can try this one until fdroid guys put out a new version
https://www.androidfilehost.com/?w=files&flid=73985
