### ISSUE TITLE
Warn that MD5 is practically broken!

### ISSUE THREAD

**Issue by JRHaigh** [arpitkh96/AmazeFileManager#459]
Example MD5 collisions were first published in 1996, and many practical attacks have since been published. It's now possible to find MD5 collisions within seconds on a single, widely-available CPU. Given that Amaze doesn't support Android prior to 4.0, devices that can find MD5 collisions within seconds are far more abundant than devices that can run Amaze.
&nbsp;&nbsp;&nbsp;&nbsp;Even though it is well-known that MD5 offers negligible security, **Amaze should warn the user about the risk of MD5 collisions whenever they copy the MD5 checksum**. If they is using the MD5 function then perhaps they didn't know that MD5 is insecure, hence they should be warned!

**Comment by rpiotaix** [comment]
I completely agree with you on that.

Maybe the question that has to be asked is: Why provide a hash (even if broken) in the properties window?
I see two options:
- First is signing. by using this (and if you trust amaze to do the correct computation of the hash) you can use it to verify that you downloaded the correct file.
- Second is file integrity. If you copy a file, you can say that the copy is successful if the hash is the same. In that case, strong signature is not needed as you exclude the idea of a malicious intermediary trying to tamper with our data. Though, CRC32 could also have worked.

In any case, these two points can be solved by using SHA-256 or any other strong hash functions in a better way than using MD5 and it should be implemented.

**Comment by vishal0071** [comment]
I think this is beyond the scope of file manager. But we're sure to implement sha256 in near future.
