### ISSUE TITLE
Support SHA-256

### ISSUE THREAD

**Issue by JRHaigh** [arpitkh96/AmazeFileManager#460]
The only hash function that Amaze currently supports can be forged in less than a minute on a single CPU, including pretty much any device capable of running Amaze (see #459). It's about time that Amaze provides at least SHA-256. (Well, it's about time that was the case since before Amaze came into existence – why such an application was born with an archaic and insecure hash function is beyond me!)
&nbsp;&nbsp;&nbsp;&nbsp;**Please display the SHA-256 checksum in file properties**, as is currently the case for MD5.

**Comment by vishal0071** [comment]
SHA-256 checksum is very much planned, and in the priority list. So rest assured, new beta versions will have it sooner than later.
