### ISSUE TITLE
Support countercryptanalysis

### ISSUE THREAD

**Issue by JRHaigh** [arpitkh96/AmazeFileManager#461]
Cryptanalytically-forged collisions can be detected even if only 1 of the collided messages/files is known. Cryptanalytic collision forgeries unavoidably leave cryptanalytic evidence of the forgery in the forged file, and this can be detected. This detection, or, more generally, ‘[countercryptanalysis](https://marc-stevens.nl/research/papers/C13-S.pdf)’, is essential for broken cryptographic primatives such as MD5 and SHA-1. The countercryptanalytic algorithms can be implemented as a drop-in replacement utility/library to replace the naïve algorithms utility/library.
&nbsp;&nbsp;&nbsp;&nbsp;**Please include countercryptanalysis in Amaze's MD5 function, and alert the user if a forgery is detected.** Otherwise, it'd be better-off removed entirely, but I'd rather it be secured without removal.

**Comment by JRHaigh** [comment]
The only countercryptanalytic checksum utility/library that I can find is the one for SHA-1, designed as a replacement “for common SHA-1 libraries and `sha1sum`”:
https://github.com/cr-marcstevens/sha1collisiondetection
&nbsp;&nbsp;&nbsp;&nbsp;Unfortunately, it is released under the MIT/Expat licence, a free software licence as far as copyright is concerned, though not a modern licence that is patent-aware too like the GPLv3, which Amaze has. MIT-like licences don't give any reässurances against submarine patents.
&nbsp;&nbsp;&nbsp;&nbsp;Anyway, if you wanted to add SHA-1 support then that's the library that you'd use.

**Comment by JRHaigh** [comment]
For explanation of the extent to which MD5 and SHA-1 are broken, see #459 and [Hashr issue #8](https://github.com/kodejak/Hashr/issues/8), respectively.

**Comment by vishal0071** [comment]
This functionality is beyond a file manager's scope according to me.
