### ISSUE TITLE
Consistent code formatting

### ISSUE THREAD

**Issue by EmmanuelMess** [arpitkh96/AmazeFileManager#463]
Sometimes there are blank spaces after if's and method signatures, sometimes not; sometimes there are spaces after if's ("if (x == y)"), other times not ("if(x == y)"); sometimes there are spaces before and after conditional operators, other times not. The code should be formatted always the same, so that it's more readable...

**Comment by vishal0071** [comment]
Most of the new code is readable, each method has proper usage javadoc, variables have proper names, and spaces are consistent too. Old code is also being formatted each day to follow the same, so it's likely some of the old code be non formatted, but most part of it is readable.
