### ISSUE TITLE
Refresh from scrolling down at bottom

### ISSUE THREAD

**Issue by PanderMusubi** [arpitkh96/AmazeFileManager#465]
Some directories have hundreds of files. in Order to refresh, one has to scroll tot the top and scroll further up to trigger a refresh. Could this refesh be also triggered at the bottom of a list of files by scrolling further down? This saves a lot of unneeded scrolling in directories with hundreds of files.

**Comment by vishal0071** [comment]
We tried this earlier, didn't work out quite well.

**Comment by PanderMusubi** [comment]
If I may ask, what was the specific problem with it?
