### ISSUE TITLE
Categorize files and folders in Delete dialog

### ISSUE THREAD

**Issue by rupak0577** [arpitkh96/AmazeFileManager#466]
Currently, the delete dialog lumps together all selected files and folders.

I have pushed a fix and would like to have some feedback.

![screenshot_1488437754](https://cloud.githubusercontent.com/assets/10296115/23497522/731a7f6c-ff49-11e6-8d26-bc8eeca3c008.png)
![screenshot_1488437780](https://cloud.githubusercontent.com/assets/10296115/23497523/7345403a-ff49-11e6-8ee6-b629a76406ef.png)

**Comment by vishal0071** [comment]
That'd be nice.
Now that we're at it, it would be nice to like improve the formatting as plain text is kinda boring. Like make Files/folders bold or something like that.
Ps. I took a quick look at your commit, and noticed you didn't localize the files/folders title to strings.xml.

**Comment by rupak0577** [comment]
Yeah, I was thinking about that but wasn't sure how to do it. I will add the title to `strings.xml`

**Comment by vishal0071** [comment]
````Html#fromHtml(string)````  for formatting

**Comment by rupak0577** [comment]
It is deprecated in API 24. Looks like `SpannableStringBuilder` is the way to go.

**Comment by vishal0071** [comment]
Alright 👍

**Comment by rupak0577** [comment]
Unfortunately, it looks like the `content` cannot be formatted in any way. So I added dashes instead.

![screenshot_20170302-211515](https://cloud.githubusercontent.com/assets/10296115/23514554/b140b43e-ff8d-11e6-8105-e3a687fc23ea.png)

The delete message string also needs to be modified for all languages.

**Comment by vishal0071** [comment]
No problem. I'll give a try formatting it. One last thing, wouldn't you think showing size of each item will help figure out to user that he's deleting the right file, before deleting it?
Eg. 1. text (14 bytes)

**Comment by rupak0577** [comment]
That's a good idea. I will add it.

**Comment by vishal0071** [comment]
Waiting for a PR
