### ISSUE TITLE
Change FTP root directory

### ISSUE THREAD

**Issue by malessandrini** [arpitkh96/AmazeFileManager#472]
Hi, when using FTP server you can only access the internal flash, and not SD card. This, added to the fact that I cannot cut/paste files to SD in android 6.0.1 (app crashes, maybe related to the warning you state in the readme), makes impossible to transfer files to SD.
Even without adding an extra setting, a more sensible default path could be the directory set by the user as "home".
Thanks
Michele

**Comment by vishal0071** [comment]
Be sure to test this on upcoming beta.

**Comment by malessandrini** [comment]
Thanks a lot!!!

**Comment by vishal0071** [comment]
BTW you should be able to access SD card. The warning is for KitKat devices.
It'd be better if you press on report / send feedback button from crash dialog so that I can look into the issue.

**Comment by malessandrini** [comment]
I just did it. BTW it seems related to the file's size, and not to SD, because I first tried with a random file and it worked, then when copying (not moving) a file from SD to internal memory (so the other way around) it crashed again.

**Comment by vishal0071** [comment]
This one's been fixed too. Expect another beta today with both the fixes.
