### ISSUE TITLE
If a password for samba share contains non-alphanumeric characters authentication fails

### ISSUE THREAD

**Issue by KOLANICH** [arpitkh96/AmazeFileManager#482]

**Comment by vishal0071** [comment]
Should've been fixed. If you use URLEncoder specific reserved chars in password (like @ or / or : ) the network parser will probably not be able to distinguish it from other parts like port no. So I don't see any workaround to this.

**Comment by KOLANICH** [comment]
In XPlore the same password for the same account at the same PC works.

**Comment by vishal0071** [comment]
I'll post new update. Try it and see if fixes the issue.

**Comment by KOLANICH** [comment]
10 апреля 2017 г. 15:56:28 GMT+03:00, Vishal Nehra <notifications@github.com> пишет:
>I'll post new update. Try it and see if fixes the issue.

Remember: I have no Google Play on my phone.
