### ISSUE TITLE
Allow to disable autohiding of toolbar

### ISSUE THREAD

**Issue by gsantner** [arpitkh96/AmazeFileManager#486]
Please add an option (e.g. to appearance category) to disable autohiding of the toolbar in Main-Fragment/Activity. Many people may like it to have more space for contents of a folder, but e.g. myself would prefer to always have the toolbar options available - without having to scroll up again.

Heres a snippet used in an other project of mine, which does the job: <https://github.com/Diaspora-for-Android/dandelion/blob/master/app/src/main/java/com/github/dfa/diaspora_android/activity/MainActivity.java#L1172>.

I could also have sent a PR, but I wanted to discuss this first. Would really be great if Amaze could have this option (opt-in of course, so autohiding is default enabled like currently), scrolling toolbars are a nightmare for me :D.

EDIT:  
Does the job for me:  
Main.java :: onCreateView,  below `mToolbarContainer = `
```
AppBarLayout.LayoutParams params = (AppBarLayout.LayoutParams) getActivity().findViewById(R.id.action_bar).getLayoutParams();
params.setScrollFlags(0);  // clear all scroll flags
mToolbarContainer.setExpanded(true, true);
```
But don't know about the F-Droid build's version of the Activity. Cannot build the flavor which is currently on HEAD.

**Comment by gsantner** [comment]
Can you tell me which fragment/activity really does get opened?
E.g. theres a "MainActivity" in fdroid folder. Is this even used anymore?

**Comment by vishal0071** [comment]
Make all changes to play/MainActivity
Any changes you make to fdroid one will be overwritten.
