### ISSUE TITLE
Allow to disable NavHeader in NavDrawer

### ISSUE THREAD

**Issue by gsantner** [arpitkh96/AmazeFileManager#487]
Allow to disable/hide the NavHeader at the NavDrawer - (Appearance setting?). This gives a lot of more space for folders and paths. At  e.g. smaller devices at opening drawer the list contains ~3 items, the rest is consumed by navheader, the bottom 3 fixed options, and the root/sdcard option.

<table><tr>
<td><img src="https://cloud.githubusercontent.com/assets/6735650/24276155/ecdce88e-1034-11e7-9f63-7e3025d96c21.png"/></td>
<td><img src="https://cloud.githubusercontent.com/assets/6735650/24276154/ecdc6224-1034-11e7-80f4-e5319145ff7d.png"/></td>
</tr>
</table>
For me the right one is better useable. The header is quite useless, I know it's Amaze anyway :).

**Comment by vishal0071** [comment]
No, header is an integral part. How can you do this!!!  ):

**Comment by gsantner** [comment]
If anybody wants to minimize the space, heres a patch:
[0001-navheader-minimum-space.patch.txt](https://github.com/arpitkh96/AmazeFileManager/files/873949/0001-navheader-minimum-space.patch.txt) (`git apply 0001-navheader-minimum-space.patch`)

@vishal0071 I cannot see any benefit of it, if you don't use g+ login. If the image would get read from the Me-Contact, maybe it would make sense. Maybe thats an personal preference, if there are some (0-5) options navheader makes totally sense, as all options are visible anyway  - but if there are so many options and there is a pretty much 100% chance for me is to scroll down immediately, I cannot see any benefit of it - just needing additional touches&time ;).
