### ISSUE TITLE
res/raw/key is missing

### ISSUE THREAD

**Issue by martincz** [arpitkh96/AmazeFileManager#491]
AmazeFileManager/src/main/java/com/amaze/filemanager/services/ftpservice/FTPService.java:157: key cannot be resolved or is not a field
AmazeFileManager/src/main/java/com/amaze/filemanager/fragments/FTPServerFragment.java:482: key cannot be resolved or is not a field

**Comment by vishal0071** [comment]
It's the keystore for ssl certificate. I don't think exposing it is a good idea. This is actually what took me so long to push these changes. I can't figure a way to encrypt the password for keystore. Keystore itself can easily be extracted from apk even when it is not included in git. 
Any ideas are welcome.

**Comment by martincz** [comment]
Hmm, I think it is bad for developer, this way will become very complicated.
You can upload a debug keystore for developer, different with release version.
It's just for compile successful.

**Comment by vishal0071** [comment]
I've put on the certificate in raw
