### ISSUE TITLE
No Write Permissions - Operation Fails

### ISSUE THREAD

**Issue by ev3y2** [arpitkh96/AmazeFileManager#493]
When attempting to copy or create a file to a subfolder of root the operation fails. The Root Explorer option in settings is toggled, and the app has been granted root permissions.

**Comment by vishal0071** [comment]
Check if the file name has any of the system reserved characters

**Comment by ev3y2** [comment]
It doesn't; for example, the operation of creating a file named "test" fails in / and /system/etc/init.d/ but succeeds in Storage (/storage/emulated/0/). 
The permissions of folders in /storage/emulated/0/ are **rwx** but the permissions of /system/etc/init.d are **drwxr-xr-x**. Attempting to change the permissions of /system/etc/init.d folder through the properties sub-menu does nothing.

**Comment by vishal0071** [comment]
Hmmm, strange. Can you give me the output of mount command from terminal?

**Comment by ev3y2** [comment]
> adb shell
su
mount -o rw,remount,rw /system

returns 
> mount: '/dev/block/bootdevice/by-name/system'->'/system': Device or resource busy

**Comment by vishal0071** [comment]
Well then, this answers why it's not working. Probably a device restart will help

**Comment by ev3y2** [comment]
> Probably a device restart will help

it does not

**Comment by ev3y2** [comment]
> mount

returns, among other things,
> /dev/block/sde20 on /system type ext4 (ro,seclabel,noatime,discard,data=ordered)

which if I had to guess means that /system is busy because it's already mounted on /dev/block/sde20? Either way, why does any of this prevent me from writing to /system/etc/init.d/? You say

> this answers why it's not working

but I still don't understand why it's not working.

**Comment by Alexander--** [comment]
Of course it fails,—the filesystem is readonly.

**Comment by vishal0071** [comment]
That too, but it's busy so we can't also remount it. 
And it's not working because you need to have mount point as rw before modifying any children in it that's why it fails. 
A solution would be to ask rom developer about this.

**Comment by Alexander--** [comment]
Builtin `mount` utility often fails for no reason. It is worth it to `mount` command of busybox. Also make sure, that you are not currently within the corresponding directory (`/system` or `/`) within an adb shell. An existence of running process, whose current directory is within the mountpoint, is the most common reason, why partitions might be unmountable. Also make sure, that other programs don't run shells within the mountpoint. Stop every file manager and root application before trying to remount.

**Comment by ev3y2** [comment]
As I only really need this to disable IPv6 with an init.d script and I intend to change my VPN service to one that supports IPv6, I'll give up and close the issue for now. Anyway, granted that other users don't seem to be having this issue there is a good chance it's an issue with my rom (omni7.1.1 for Oneplus 3). I'll reopen the issue if need be.
