### ISSUE TITLE
Long folders refresh list issue

### ISSUE THREAD

**Issue by axet** [arpitkh96/AmazeFileManager#506]
Long folder has no option to refresh if you scroll bottom, willing and to refresh folder here will be no option to do so: you have to scroll up again. Please add refresh command to top tree dot menu (without loosing current file selection or view position).

Would be nice to have three dots menu never goes off the screen (always present on ever sliding top menu, very bad feature).

**Comment by vishal0071** [comment]
The last part, where toolbar does't hide has been implemented. But refreshing behavior is fine, and that's how it's supposed to be. It's a little annoying that selection doesn't cancel even after a refresh. And finally, the bottom pull to refresh didn't work out very well, we did implement it in the past. Adding a refresh button is also not an option in three-dot menu as it will just clutter up the list uselessly.

**Comment by axet** [comment]
@vishal0071  Right way to make actions clear: refresh - refresh files, cancel selection - cancel selection. Combining those together - that what is unexpected and annoying!
