### ISSUE TITLE
[Feature Request] Edit permissions

### ISSUE THREAD

**Issue by anonimou0** [arpitkh96/AmazeFileManager#511]
Hi,
No bug here, but a feature request. 

I saw recently that Amaze can show the permissions. But I can't edit them. That's useful when installing some apk on /system/ folder (like for microG) and others.

I'm using cyanogenmod. Not complaining neither comparing, just saying how it is done there: The default file manager allow me to edit the permissions (R,W,X) on the "properties" tab. That's the only moment I use it. Whenever I need, I'm on Amaze.

Thanks!

**Comment by vishal0071** [comment]
There is an interface to edit permissions. It's in properties dialog and is visible once you are in root directories. Please consult #473 for more.
