### ISSUE TITLE
SMB file transfers result in files appended with null bytes.

### ISSUE THREAD

**Issue by KOLANICH** [arpitkh96/AmazeFileManager#512]
So if I want to transfer a file I have to truncate it manually after a transfer. This bug occurs more frequently (almost always) when I transfer a file from a PC to my phone. Sometimes it occurs if I transfer a file from my phone to a PC.

**Comment by vishal0071** [comment]
````truncate it manually after transfer```` what do you mean by this And ````files appended with null bytes```` this?

**Comment by vishal0071** [comment]
The problem has been long fixed. What version of Amaze do you use?

**Comment by KOLANICH** [comment]
3.1.1
