### ISSUE TITLE
About Amaze File Manager title in Spanish

### ISSUE THREAD

**Issue by EmmanuelMess** [arpitkh96/AmazeFileManager#527]
About Amaze File Manager title in Spanish is "Asombro", it should be "Administrador de Archivos Amaze" or something similar. "Asombro" more or less means "amazement".

**Comment by vishal0071** [comment]
You can create a PR.

**Comment by EmmanuelMess** [comment]
Yeah, but translations are managed from transifex, isn't this an issue from there?

**Comment by vishal0071** [comment]
Transifex is not up to date so you can change it directly. I'm actually looking for someone who can manage translations and keep them updated on Transifex.
