### ISSUE TITLE
Sort Options dialog confusing.

### ISSUE THREAD

**Issue by jimbo1qaz** [arpitkh96/AmazeFileManager#529]
The sort options dialog's Ascending/Descending options have always confused me.

Maybe if it indicated the currently selected option (ascending/descending) using radio buttons, or if you swapped the two button locations?

Rename the options? Not quite sure.

**Comment by vishal0071** [comment]
You're right, I'll swap them.

**Comment by jimbo1qaz** [comment]
Do you think swapping them improves the interface?

**Comment by vishal0071** [comment]
No. It won't improve the interface. You have any other recommendations for it? I can't find any other myself.
