### ISSUE TITLE
No app bar in Advanced Search Preference Fragment

### ISSUE THREAD

**Issue by EmmanuelMess** [arpitkh96/AmazeFileManager#530]
Go to Settings/Advanced Search (under Others subcategory), it has no app bar. Moto E2 Android 6

**Comment by EmmanuelMess** [comment]
BTW, check [this](https://github.com/EmmanuelMess/AmazeFileManager/commit/aa06ce3977fa8370d939ab33eca6e6174536114c) for generalized solution (only the Preferences and Preffrag files, the rest is unfinished code).

**Comment by vishal0071** [comment]
@EmmanuelMess when creating a class, write in few lines what the class is for. And for every method you create write it's documentation too, be it just a line or two. It really is important for long term point of view.

**Comment by EmmanuelMess** [comment]
I'll try, although I think some things are obvious (AdvancedSearchPref extends PreferenceFragment).
