### ISSUE TITLE
Writing to SD card causes crash if app imported after factory reset

### ISSUE THREAD

**Issue by LeapingDragon** [arpitkh96/AmazeFileManager#536]
App+data imported via Titanium Backup, DocumentProvider isn't triggered when writing to SD card and instead causes Amaze to crash.

**Comment by vishal0071** [comment]
Does clear data from system settings fix this issue?

**Comment by LeapingDragon** [comment]
Yes, just figured it makes sense to note down that this should produce a prompt (this is the only app I have that has this issue)

**Comment by vishal0071** [comment]
The fix would result in asking for SD Card permissions everytime when the app starts, that would be more inconvenient than performing a data wipe of Amaze or not backing up the data. 
This bug can also be reproduced if you remove your SD Card and insert a new one. In which case I'll work on it's fix. Can you confirm if removing SD Card and inserting a new one actually has this same bug or not?

**Comment by LeapingDragon** [comment]
I haven't got another SD card but I'll let you know if I do get another 
one soon to test with.

**Comment by vishal0071** [comment]
You can try another thing. Pull out SD Card (only after you've opened it atleast once in amaze and given permission). Then reboot device and put in SD Card again. Open Amaze now and test if it works (it's essentially the same as changing SD Card from system perspective).
