### ISSUE TITLE
Open source projects incomplete，can you check code has push completed

### ISSUE THREAD

**Issue by debughao** [arpitkh96/AmazeFileManager#537]
After I downloaded the code, in the Android studio to build the project, there are some errors, can check whether the code is completed

**Comment by EmmanuelMess** [comment]
What errors?

**Comment by rupak0577** [comment]
Can confirm. I am unable to build the project.
![screenshot from 2017-04-28 11-11-48](https://cloud.githubusercontent.com/assets/10296115/25515642/95b8341a-2c03-11e7-8467-69aa0c32929a.png)

**Comment by vishal0071** [comment]
Change build variants to playDebug
