### ISSUE TITLE
Multifolder copies reload folders list even if unnecessary

### ISSUE THREAD

**Issue by EmmanuelMess** [arpitkh96/AmazeFileManager#541]
To replicate cut 3 or 4 folders with big files, then navigate to any (other) folder, each time a folder is copied an annoying toast will show and the folders will get reloaded, even if you are neither in the destiny nor in the source of the copy.
I know I should solve this, but it is still an issue, and I can't solve it right now.

**Comment by vishal0071** [comment]
I'm look into it.

**Comment by vishal0071** [comment]
Possibly been fixed, atleast for local filesystem
