### ISSUE TITLE
some suggetions compair to the CMFilemanager

### ISSUE THREAD

**Issue by sbw983** [arpitkh96/AmazeFileManager#544]
Hello
I'm very glade to find a such excellent opensource file manager for my android phone. before i use amaze FM, i use CMFilemanager as my default FM. and when Lineage OS drop the CMFilemanager, i have take a long time to find a new opensource filemanager until i find amaze and i immediately set it as my default FM. after few day's usage there is some suggestion for amaze FM
1.if amaze FM can add multi-sellection function like CMfilemanager,  multi-sellection and operation is common for desktop operation and only CMfilemanager can make it operated on android. so i hope amaze can support.
2.If amaze can support safe mode and advanced mode like CMfilemanager. I find root access switch in the amaze's setting tab, but there is no deference to show if i get root access in amaze filemanaget and always get root access is danger for the whole system, sometime one wrong operation may destroy the whole system.  for common users, 99% operate is  base on default internal storage and extend sdcard, so safe mode is enough for daily use and it's clean and easy to master.  Then advanced mode can get root access, show and operate for the whole filesystem.

to me, amaze FM is an almost perfect FM, thank you for your hard work.

**Comment by EmmanuelMess** [comment]
"if amaze FM can add multi-sellection function like CMfilemanager" this currently exists, you can select more than one them by long tapping.

**Comment by vishal0071** [comment]
Exactly, please clearly state what the option does.
