### ISSUE TITLE
Amaze Cloud Plugin Isn't Registering

### ISSUE THREAD

**Issue by Yowlen** [arpitkh96/AmazeFileManager#551]
I purchased the cloud plugin, but Amaze won't recognize it. I already opened it up & got the 'thank you' message (you're welcome, btw 😉), but when I open Amaze, I get a toast notification saying `Failed to load the connection. Please open Amaze Cloud once.`

Running Android 5.1.1 custom ROM (XenonHD, based on SlimROM).

**Comment by vishal0071** [comment]
Try wiping Cloud plug-in's app data from system settings and open it again.

**Comment by Yowlen** [comment]
As stated, I opened the cloud plugin fresh after installing before I even opened Amaze. The cloud plugin's `Clear Data` button shouldn't have any effect because the result from opening it again should be the same.

Anyway, I tested just to be sure, and I was right. I still get this toast notification in Amaze after clearing the cloud plugin's data.

**Comment by vishal0071** [comment]
I was asking just to be sure. Actually the problem is with the encryption of keys. Long story short, I couldn't get a confirmation of encryption working on Lollipop, Kitkat and Jelly Bean devices. I'm encrypting the keys required by the cloud plugin before using them in Amaze.
You can confirm the same by trying to encrypt any file in Amaze and it would fail on these Android versions.
As for a fix, since I don't have a device with either these android versions, I'm gonna ask you to test it. 
Are you enrolled in Amaze's beta program?

**Comment by Yowlen** [comment]
Yes. Already enrolled in the beta. I also have a Kit Kat tablet I can use to test. Nothing with Jellybean, though.

**Comment by vishal0071** [comment]
I just want either one of those three, if it starts working on one, it should work on all. I'll post another update for plug-in then, and if plug-in starts working, then a beta update for Amaze on which you shall test encryption to confirm.

**Comment by vishal0071** [comment]
@Yowlen I've published an update for cloud plug-in. Make sure to wipe data after updating to new version and opening the plug-in after it, before testing this on Amaze.

**Comment by Yowlen** [comment]
Just tested. Still giving the toast notification.

**Comment by vishal0071** [comment]
Can you happen to provide a logcat while starting cloud plugin. 
Meanwhile I'm trying my best to find a device to speed up this process.

**Comment by Yowlen** [comment]
Here ya go. I filtered by package name to make it easier, but if there's a piece missing, I can provide the full catlog.
[2017-05-05-16-55-31.amaze.txt](https://github.com/arpitkh96/AmazeFileManager/files/980314/2017-05-05-16-55-31.amaze.txt)

**Comment by vishal0071** [comment]
Just here to report that Cloud plugin is fully working now, a new update is on it's way.

**Comment by Yowlen** [comment]
So, I'm guessing that also means encryption within the main app is also gonna be working for 5.x & below. Awesome.

**Comment by vishal0071** [comment]
Yes.. for 5.x, 4.3, and 4.4

**Comment by Yowlen** [comment]
I can confirm the new update does register the cloud plugin properly.

**Comment by vishal0071** [comment]
And with the new cloud plugin update, Google Drive will also start working, and uploading to cloud will work too. Update is ready, will push it only after Amaze is released on stable version (in a few days),.

**Comment by vishal0071** [comment]
Also note that without new cloud plugin update, you might not be able to use the plugin in Amaze at all. As there was a change in schema, you need to be on latest version on both.
