### ISSUE TITLE
Bulid Failed

### ISSUE THREAD

**Issue by RamolaWeb** [arpitkh96/AmazeFileManager#552]
While recently building the project , the build failed as the LIST_ELEMENT has an private access in Main Fragment.Java and is been accessed in Main Activity.Java.

**Comment by RamolaWeb** [comment]
@vishal0071 Should we change the scope of the variable to fix this problem?

**Comment by vishal0071** [comment]
Please build the playDebug variant as fdroidDebug is generally outdated at only gets updated before final release.
