### ISSUE TITLE
Quick Accesses have a number as directory

### ISSUE THREAD

**Issue by EmmanuelMess** [arpitkh96/AmazeFileManager#553]
To replicate: open a quick access (sidebar, starts in "Quick Access"), check the directory in the upper bar.
Please don't try to solve this yet, as it will generate conflicts with my code.

**Comment by vishal0071** [comment]
As a matter of fact, Quick Access is crashing for me :P
So I'm not supposed to fix it? Alright. I'll wait.

**Comment by EmmanuelMess** [comment]
Android version?

**Comment by vishal0071** [comment]
7.1.2

**Comment by MaanooAk** [comment]
I fixed the name in #549, I don't know about the crash...

**Comment by vishal0071** [comment]
Yes, name was fixed for others but Quick Acess is crashing :/

**Comment by EmmanuelMess** [comment]
Original problem was solved, I think this issue should be closed.
