### ISSUE TITLE
Update Play Store device exclusion list to allow emulators

### ISSUE THREAD

**Issue by SUPERCILEX** [arpitkh96/AmazeFileManager#557]
Google recently added the Google Play Store to their emulators which makes it super easy to get apps, but unfortunately Amaze File Manager says the emulator isn't supported. Of course I could get the apk from ApkMirror, but it nice to have auto updating and the Play Store environment.

**Comment by vishal0071** [comment]
It's not well documented on how to add it's support yet. Hell even their changelog doesn't clearly state this change and it's just in Preview state.
We add the latest (stable) API 25 as targetSDKVersion. So it should support emulators too. There are no devices excluded (other than those which falls below minSdkVersion) from Play Console.
So for now, we'll have to wait.
