### ISSUE TITLE
Option to set Number of Column in List View

### ISSUE THREAD

**Issue by jerryn70** [arpitkh96/AmazeFileManager#582]
Title says the description

**Comment by vishal0071** [comment]
Number of rows in list view = number of files at the path =_=

**Comment by jerryn70** [comment]
You mean there an option called number of files at the path ? 

I didn't see any option like that 🙁

**Comment by vishal0071** [comment]
There is no option like that. I'm not able to understand you. Number of rows in list will be equal to number of files at a path.

**Comment by jerryn70** [comment]
See the screenshot . 1 is from amaze and 2 is from mixplorer . 
Mixplorer has more column than amaze . I mean an option to increase an decrease column in list view. 


![screenshot_20170517-152402](https://cloud.githubusercontent.com/assets/23030460/26148625/fa380986-3b14-11e7-9309-091c977ea129.png)
![screenshot_20170517-152420](https://cloud.githubusercontent.com/assets/23030460/26148637/033ae904-3b15-11e7-8d7f-7f2e8fae8ee6.png)

**Comment by vishal0071** [comment]
I'm sorry but that won't be done. All the metrics are set according to material design guidelines. You could change your screen density from System settings > Display > Display Size (on Nougat+) or if you're rooted then you can manually change the dpi of device from build.prop
