### ISSUE TITLE
Application Manager doesn't remove system apps

### ISSUE THREAD

**Issue by ildar** [arpitkh96/AmazeFileManager#585]
Though making a warning, still doing nothing

**Comment by vishal0071** [comment]
What version of Amaze do you use?

**Comment by ildar** [comment]
Latest from F-Droid. If it should then I'll try getting the logs to see
what gone wrong

**Comment by vishal0071** [comment]
What's the version number of latest one in fdroid?

**Comment by ildar** [comment]
[3.1.2 RC3](
https://f-droid.org/repository/browse/?fdid=com.amaze.filemanager)

**Comment by vishal0071** [comment]
Works fine for me, I will need a logcat to pin point the problem for you.
Also, try deleting any file in any root directories, and see if the operation is successful or not (you can optionally create a new temporary file at root and try to delete it).
