### ISSUE TITLE
Cut/Paste Leaves Broken File in Original Directory

### ISSUE THREAD

**Issue by Xephorium** [arpitkh96/AmazeFileManager#589]
Nougat, Pixel

From "Storage", when I cut and paste a file from directory A to directory B, everything appears to work fine. There's an identical new file in dir B and A appears empty. However, switching to "Images" reveals a leftover file of the same name/type that cannot be opened. These broken files are also detected by external gallery apps (in my case, Google Photos).

**Comment by vishal0071** [comment]
Does restarting the device fixes it?
