### ISSUE TITLE
Enhancement request: In the FTP Server page, include IP address/mDNS

### ISSUE THREAD

**Issue by PrawnMan** [arpitkh96/AmazeFileManager#590]
Currently, the easiest way to quickly glance at your IP address after starting the amaze FTP server is to swipe the notification shade down and see the IP address there. Wouldnt it be substantially more convenient to state the IP address in the FTP Server Status box? Above/below the port number?

**Comment by vishal0071** [comment]
Done with v3.1.2 RC4

**Comment by PrawnMan** [comment]
Thanks !
