### ISSUE TITLE
New SMB connection won't save if special characters on password start and end

### ISSUE THREAD

**Issue by anonimou0** [arpitkh96/AmazeFileManager#591]
On the new amaze app, after inserting all the data and password, if the password end in the special character "!" and start with "@" the new connection dialog won't close and save. It seems that it should have some numbers on the middle of it.
If I change the input password for a wrong password without these character s the connection will save but when trying to connect it won't, because, well, it is the wrong password.
Example of password that will nor work: @a1bc2d3!

**Comment by anonimou0** [comment]
Not sure why that was happening. 
Cleared the app data and it worked.

**Comment by vishal0071** [comment]
Actually this is a flaw when you updated to new version and was only fixed by wiping data.
