### ISSUE TITLE
Only request root when necessary

### ISSUE THREAD

**Issue by Kriskras99** [arpitkh96/AmazeFileManager#592]
Currently when you enable 'Root Explorer' Amaze immediately asks for root permissions, and will be root until you exit the application. This seems rather unnecessary to me, should it not only request root permission when it actually needs it?

**Comment by EmmanuelMess** [comment]
AmazeFileManager will try to show the / directory (aka root), so it needs root as soon as you exit settings. 
> will be root until you exit the application

Only until you exit? I don't think that's working as intended. Could you provide Android version and phone model?

**Comment by Kriskras99** [comment]
It is working, if I restart the application it has to rerequest permissions.
But I understand now, thank you!

**Comment by ildar** [comment]
I mean when I open the app it shows /sdcard/Download/. But the app asks SU even though it doesn't need it at the time.
Please reopen.
