### ISSUE TITLE
question regarding root and file permissions ...

### ISSUE THREAD

**Issue by atomGit** [arpitkh96/AmazeFileManager#596]
for working with system files we need RW permission - Amaze obviously does this, but i'm wondering if it un-does (restores RO) it and when, or whether it leaves / in a RW state (it doesn't seem to)?

**Comment by vishal0071** [comment]
Don't worry, after every option performed,  the mount point is restored to it's last state whether it was in rw or ro. You can confirm the same by running mount command before and after performing any operation.
