### ISSUE TITLE
Copying can alter files

### ISSUE THREAD

**Issue by utack** [arpitkh96/AmazeFileManager#598]
Amaze: Version 3.1.1 from F-Droid

What is happening:
I have a plain text file (not txt extension, fwiw) on my external microSD card, it is ~14kb
I copy it to any folder, internal or external SD, and it is suddently 60kb and padded with "00" at the end
What is expected:
The file is the same after being copied

Can someone else reproduce this bug?
Thanks

**Comment by vishal0071** [comment]
Check the current recommended version (here)[https://f-droid.org/wiki/page/com.amaze.filemanager]

**Comment by utack** [comment]
Oh yeah that works, thanks  
I thought it was a mistake that "RC" is recommended before
