### ISSUE TITLE
New SMB Connection Won't Allow Anonymous Credentials

### ISSUE THREAD

**Issue by alanjames1987** [arpitkh96/AmazeFileManager#602]
When checking off the `Anonymous` option when setting up a new SMB Connection Amaze error with a toast notification stating "Logon failure: unknown user name or bad password.".

![screenshot_20170524-072046](https://cloud.githubusercontent.com/assets/765326/26401216/dc2708b4-4052-11e7-9c19-56b754078474.png)

![screenshot_20170524-072016](https://cloud.githubusercontent.com/assets/765326/26401217/deda6d12-4052-11e7-9c63-ce35e850db7d.png)

I'm using Amaze v3.1.2 RC3 and Android 7.1.1 on a Nexus 9. The same issue happens on Nexus 5 running Android 7.1.2 and same version of Amaze.

To eliminate as many variables as possible I've cleared the app cache and reinstalled the application and error persists.

My SMB server IS anonymous so I know this isn't an error caused by me using the incorrect username or password. Additonally, the same configuration worked in an older version of Amaze, however I don't remember the version I last used.

**Comment by vishal0071** [comment]
I'll be looking into the issue

**Comment by vishal0071** [comment]
Fix coming in v3.1.2 Beta 11
