### ISSUE TITLE
V3.1.2 RC3 cannot access samba drives, RC1 can.

### ISSUE THREAD

**Issue by aguaviva** [arpitkh96/AmazeFileManager#606]
It doesnt show any errors, it just switches back to show my phone files.

**Comment by ka223** [comment]
I can not add a new cloud share on android 6, nothing happens on the create button.

**Comment by Generator** [comment]
Same here, previous settings worked with previous releases, now can't no longer connect to smb server.

Already try to re-enter smb settings, but no luck.

**Comment by aguaviva** [comment]
I tried debugging the issue but it is harder than what I thought. Any hints are welcome.

**Comment by Generator** [comment]
That's something realted with the new cloud services (>=RC2).
I didn't try to debug, only downgrade to rc1, maybe I'll see if can find anything later.

**Comment by vishal0071** [comment]
What Android version you guys use? I introduced encryption of passwords before saving to database for a new SMB Connection in RC3. Try encrypting any file, if that doesn't work means encryption is broken (which in fact is broken on KitKat and Lollipop devices, I'm trying to find a fix for it but no luck so far).
Ps. The SMB database had been poorly designed, I'll need to spare time rewrite it later, but for now try clearing Amaze's apk data from system settings and see if that makes SMB work.

**Comment by vishal0071** [comment]
@ka223 you mean, you can't add new cloud connection from the cloud plugin?

**Comment by ka223** [comment]
@vishal0071 Android 6.0.1
Deleting App Data is not fixing this.

I can not add a smb Server via:
+ > Cloud Connection > smb connection

After entering IP, username and password, on create it is not saving/closing the window.

**Comment by vishal0071** [comment]
That is strange, it should be working on Marshmallow. Do you get some toast notification?

**Comment by ka223** [comment]
@vishal0071 No, nothing. :(

**Comment by Generator** [comment]
Tested on Android 7.1.2
Encryption doesn't seems to work, made a logcat with `adb logcat | grep -e com.amaze.filemanager -e Amaze`

Also another logcat with smb settings

[amazeFM_encrypt.log.gz](https://github.com/arpitkh96/AmazeFileManager/files/1033851/amazeFM_encrypt.log.gz)
[amazeFM_smb.log.gz](https://github.com/arpitkh96/AmazeFileManager/files/1033852/amazeFM_smb.log.gz)

**Comment by vishal0071** [comment]
Fix coming in v3.1.2 Beta 11

**Comment by Generator** [comment]
Tested with v3.1.2-RC4, now Samba works again.
