### ISSUE TITLE
V3.1.2 RC1, the smb connection doest seem to accept custom ports

### ISSUE THREAD

**Issue by aguaviva** [arpitkh96/AmazeFileManager#608]
This is crucial to access smb shares over ssh tunnels.

Thanks for this fantastic app!

**Comment by vishal0071** [comment]
Possible fix coming in v3.1.2 Beta 11

**Comment by aguaviva** [comment]
fantastic! Now I'll be able to access my samba shares over SSH :D 👍

**Comment by aguaviva** [comment]
It works with RC4, I can punch in the port but when I edit the conenction the port doesn't show up.
