### ISSUE TITLE
Native crash if you pull out SD  when scanning apk files in SD card 

### ISSUE THREAD

**Issue by snailGoing** [arpitkh96/AmazeFileManager#611]
Highly reproduce

**Comment by snailGoing** [comment]
Loading apk Icon from file, so if you pull out SD card .there is a invalid philosophy address to being visited, native Will send signal to cause app native crash

**Comment by EmmanuelMess** [comment]
Google translate isn't this bad.

**Comment by vishal0071** [comment]
Well then, just don't pull it out while scanning! Easy fix.
You should eject it instead of force pulling it out in the first place.
