### ISSUE TITLE
Missing strings to translate

### ISSUE THREAD

**Issue by Generator** [arpitkh96/AmazeFileManager#614]
Notice there's a lot of missing string on Transifex, translator can't translate the new strings on Transifex.
Strings related to ftp (e.g. ftp_path, unknown_error) and some new features are missing.

New translated strings should be added be before new release.

**Comment by vishal0071** [comment]
I know, I need someone to manage our project on transifex. I posted about this on social media (XDA, G+ community), but got no volunteers.
