### ISSUE TITLE
The master branch is running unsuccessfully.

### ISSUE THREAD

**Issue by FightingLarry** [arpitkh96/AmazeFileManager#628]
The master branch is running unsuccessfully.
Gradle build finished with 101 error(s) and 6 warning(s) in 3m 2s 453ms
com.amaze.filemanager.activities.MainActivity.dataUtils is misssing. ManActivityno dataUtils.

**Comment by vishal0071** [comment]
https://github.com/arpitkh96/AmazeFileManager#contributors
Please read the README file, it clearly states that you should compile play flavour not the fdroid one
