### ISSUE TITLE
File copy speed is slow : Internal Storage to microSD card

### ISSUE THREAD

**Issue by Jo2joe** [arpitkh96/AmazeFileManager#632]
Good day developer! 

Here is our team's file copy test result of 50mb file copying between internal storage and microSD card. 
We test two other file manager app as well 

App version : Amaze (ver. 3.1.2 RC1) / ES File explorer (ver. 4.1.6.5.3) / Astro File manager (ver 4.9.1)
![copytest](https://user-images.githubusercontent.com/29136641/26928422-06b5f8b6-4c91-11e7-8da4-64b373b7c452.png)

File copy from microSD card to Internal Storage is no big differecne but Internel Storage to microSD card is quite slow. 
Could you please check this issue?

**Comment by vishal0071** [comment]
Do you get some sort of toast notification while performing copy from Internal Storage to SD Card stating that System is running low on memory?

**Comment by Jo2joe** [comment]
Here is update 

microSD to Internal Storage : very fast as above table 
![sd2internal](https://user-images.githubusercontent.com/29136641/27129289-a13cab5a-513c-11e7-8745-01f542f0fc42.png)

Internal Storage to microSD
![internal2sd-1](https://user-images.githubusercontent.com/29136641/27129310-b6a7ef72-513c-11e7-859e-410a67f91f61.png)  
![internal2sd-2](https://user-images.githubusercontent.com/29136641/27129311-b8a65d5e-513c-11e7-92d5-89f8ebeddfb6.png)

File transfer speed is slow... 
Our team is checking but other two file manager's transfer speed is much faster than Amaze. So this issue might be Amaze File Manager's policy. Could you kindly check this one?

**Comment by vishal0071** [comment]
I'll look into it and get back to you.

**Comment by vishal0071** [comment]
Fixed with the above mentioned commit.
