### ISSUE TITLE
App down, when remain storage + copied data is over the designed capacity 

### ISSUE THREAD

**Issue by Jo2joe** [arpitkh96/AmazeFileManager#641]
Good day developer!

During our Software QA team's testing, I got reported below issue. 
1. I make 17.9mb remained SD card
![sdmemory1](https://user-images.githubusercontent.com/29136641/27386876-0f89c01c-56d2-11e7-8039-e9b9613470c9.png)
2. I copy 50mb file to SD card from mobile phone's internal storage
![sdmermory2](https://user-images.githubusercontent.com/29136641/27386894-21300bb4-56d2-11e7-9312-eae4c74883ef.png)  
![sdmemory3](https://user-images.githubusercontent.com/29136641/27386898-279c0f98-56d2-11e7-9e13-cd607ecfad46.png)

Expected result or behavior : Warning message
Actual result or behavior : App down 

Could you kindly review this issue? I reproduce this issue with Google play version v3.1.2 RC3

**Comment by vishal0071** [comment]
I'll be working on it's fix.

**Comment by vishal0071** [comment]
Fixed with the commit mentioned above

**Comment by Jo2joe** [comment]
Thank you very much Sir!
