### ISSUE TITLE
Error when build apk file!

### ISSUE THREAD

**Issue by hanchan112** [arpitkh96/AmazeFileManager#645]
I try to import source into Android studio to build file apk but error. I dont understand file MainActivity.java will put where?
Beside error with com.amaze.filemanager.MainActivity.dataUtils .... and public class MainActivity extends BaseActivity.... to end before { ...

Some one can show me how to fix this bugs!
I dont study Android so it is so difficult to me! Thanks.

**Comment by vishal0071** [comment]
Change build flavour to playDebug from lower left 'Build Variants' button in Android Studio

**Comment by hanchan112** [comment]
Thanks for your helping!
It saves me!....
(+_+)

**Comment by hanchan112** [comment]
I so sorry! But....

When I try to change UI of Main layout I encounted some of problem. These error, I searched gg but not solved those problem.
![error2_2](https://user-images.githubusercontent.com/28885137/27981960-d2143d60-63c0-11e7-85b1-f2e30211b0f5.png)
![error1](https://user-images.githubusercontent.com/28885137/27981961-d215c964-63c0-11e7-9c50-e8bb725ec5c7.png)
![error2_1](https://user-images.githubusercontent.com/28885137/27981959-d213a1ac-63c0-11e7-8d15-03d1f9cce6c8.png)
![error3](https://user-images.githubusercontent.com/28885137/27981963-d2261f80-63c0-11e7-8cda-772030465110.png)
![error4](https://user-images.githubusercontent.com/28885137/27981962-d2187e66-63c0-11e7-864e-cd60aa9581b5.png)

**Comment by EmmanuelMess** [comment]
Ignore that, just work with the xml and test with live device or emulator.

**Comment by hanchan112** [comment]
Thanks for your helping. I tried but really difficult to edit because I'm newbiews in android and not have experiment more....

(>+<)......

**Comment by EmmanuelMess** [comment]
Start by doing something of your own that's smaller and simpler, until you get the hang of it.
