### ISSUE TITLE
Handle more archive-types (.7z .tar .rar etc.) and maybe add an SQL Editor

### ISSUE THREAD

**Issue by jensMF** [arpitkh96/AmazeFileManager#66]
I would love it, if amaze filemanager could manage mor archives. For instance .7z .tar .rar etc. The most amazing thing for me would be, if it would support all archives 7zip or peazip supports.

**Comment by jensMF** [comment]
Ok, sorry for that, I tried to extract .tar and I got only the folders, no files, but I use the f-droid build and thats not up to date. I would really appreciate if amaze filemanager could even show these archives as preview like the zips. But of course take your time, I just wanted to suggest it and I'm not even able to help, because I didn't lern coding.
I have another suggestion, an sql-viewer and -editor. Should I start a new issue?

**Comment by arpitkh96** [comment]
No need to start a new issue. I will do it as i get time. Text editor is already there

**Comment by arpitkh96** [comment]
Never thought of sql editor.. I will see it later

**Comment by vishal0071** [comment]
SQL reader have been added. Editor is not a good idea...

**Comment by jensMF** [comment]
Thanks, greate :-)
