### ISSUE TITLE
While running app in grid view when we change orientation from portrait to landscape,the app automatically changes to list view.

### ISSUE THREAD

**Issue by NamanRawat1** [arpitkh96/AmazeFileManager#660]
The app requires to saved state while working on grid view

**Comment by EmmanuelMess** [comment]
Back to the mines it is(?). I'll solve this.

**Comment by NamanRawat1** [comment]
Great looking forward to a solution to this problem.

**Comment by vishal0071** [comment]
Partially fixed, please try new update (v3.1.2 Beta 13) and report
