### ISSUE TITLE
Latest beta crashing on startup

### ISSUE THREAD

**Issue by Yowlen** [arpitkh96/AmazeFileManager#661]
Amaze Version 3.1.2 Beta 11
Android 5.1.1
I sent a report via Google with the text "Amaze crashing on startup."
Weird part is that I have two of the same phone, same custom ROM, but this only happens on one of them. I've left out most Google apps on the device Amaze is crashing on since I use it for gaming, so idk if Amaze requires something from a Google app I don't have, but since they're otherwise identical in configuration, it's the only possible reason I can think of.

**Comment by germanfr** [comment]
Same on Android 7.0.

**Comment by vishal0071** [comment]
Another beta update pushed which should fix the issues

**Comment by Yowlen** [comment]
It works now. Thanks.
And @germanfr, if it's still force closing for you, it crashed for me, too, until I cleared Amaze's data in Android's settings.
