### ISSUE TITLE
Toast is glitched

### ISSUE THREAD

**Issue by EmmanuelMess** [arpitkh96/AmazeFileManager#663]
To replicate go to settings, the "about AmazeFileManager", select donate under Arpit Khurana.
<img src="https://user-images.githubusercontent.com/10991116/28142960-9c2b5ac2-6739-11e7-8d88-699f74cf997e.png" height="300px"/>

**Comment by vishal0071** [comment]
I can't replicate. This is more of a system framework issue I think.
