### ISSUE TITLE
Can't create or change Samba connection

### ISSUE THREAD

**Issue by nazar-pc** [arpitkh96/AmazeFileManager#664]
In last 2 beta versions at least I can't create a new Samba connection (pressing "Create" doesn't do anything) and even change existing connection (though, I was able to remove all existing connections).
I'm on Lineage OS (Android 7.1.2).

**Comment by vishal0071** [comment]
Are you putting in the right credentials?

**Comment by nazar-pc** [comment]
Definitely. Trying to save changes on existing connection without actually making any changes in it does nothing. It feels like there is no callback on create/save buttons.

**Comment by vishal0071** [comment]
I;ll look into the issue.

**Comment by vishal0071** [comment]
Fixed, please try new update (v3.1.2 Beta 13) and report

**Comment by nazar-pc** [comment]
It works now, thanks!
