### ISSUE TITLE
Crashed trying to start a secure FTP server.

### ISSUE THREAD

**Issue by Yowlen** [arpitkh96/AmazeFileManager#667]
I sent 2 reports via Google's report system using the same feedback text as the title of this issue, one from my 4.4.2 tablet & one from my 5.1.1 phone.

I think it's worth noting that I've also had problems with the non-secure mode since you implemented the encryption fix. I get a `530 Authentication Failed` error when trying to connect. Anonymous mode connects just fine.

**Comment by vishal0071** [comment]
I think the certificate got modified after I deleted it by mistake and then restored it. However, it's fixed now.
Also note that the problem with non-secure mode seems to be that you are actually filling up the password wrong.

**Comment by Yowlen** [comment]
No, I made sure the password matched, otherwise I wouldn't be reporting it.

**Comment by vishal0071** [comment]
Try wiping app data?

**Comment by Yowlen** [comment]
The app data was already wiped when I performed the update to fix #661. Since it occurred during that beta, too, wiping again won't help.

**Comment by vishal0071** [comment]
What is the android version of device in which you're facing this issue?

**Comment by Yowlen** [comment]
It occurs on both of the above devices. My 4.4.2 tablet & my 5.1.1 phone.

**Comment by vishal0071** [comment]
Fix coming with new update.
