### ISSUE TITLE
Can't remove bookmarks

### ISSUE THREAD

**Issue by KopfKrieg** [arpitkh96/AmazeFileManager#671]
In Amaze version 3.1.2 RC3 (installed through f-droid) I'm not able to remove existing bookmarks. I can't find a way to do so, and a long press crashes the app.

Does anyone know how existing bookmarks can be removed?

**Comment by EmmanuelMess** [comment]
Have you tried Settings>Shortcuts (Under SideBar)>Delete?

**Comment by KopfKrieg** [comment]
Hm, I can't find that option. Could you maybe provide a screenshot so that I can verify that it really looks different on my phone? (Maybe the option is not shown on my device?!)

And it doesn't say bookmarks. You need to know I'm using the app in german, and these "links" are called "Lesezeichen" here. The common translation for this is "bookmarks". Please forgive me if I'm using the wrong terminology :)

**Comment by EmmanuelMess** [comment]
My phone is in Spanish, but I think you'll understand:
<img src="https://user-images.githubusercontent.com/10991116/28349697-bcbf8d22-6c1a-11e7-9f2e-09a7bcf164b3.png" width="300px"/> <img src="https://user-images.githubusercontent.com/10991116/28349699-bd6219e8-6c1a-11e7-99eb-872ab06fc2ec.png" width="300px"/>

**Comment by KopfKrieg** [comment]
Hm, on my phone the four entries regarding the SideBar aren't even there. That's odd.

**Comment by vishal0071** [comment]
You're using an old version. Latest version is RC4 which has this issue fixed.
https://www.androidfilehost.com/?w=files&flid=73985
