### ISSUE TITLE
Crashes when opening the FTP view

### ISSUE THREAD

**Issue by JSn1nj4** [arpitkh96/AmazeFileManager#682]
Most times I can't get to the FTP view before it crashes. Sometimes it lets me open the FTP view, but it'll then crash if I try to start it.

Details:
- OS: Android 7.0
- Device: Motorola Nexus 6
- Amaze version: v3.1.2 RC4

This has been happening at least since I updated to RC4. I don't remember if I tried FTP before.

Also, I happened to see issues #667, but I'm posting my own because I'm not sure if it's a duplicate issue.

Since I'm not an Android app dev, do you get the information submitted after crashes, and would you prefer I send it?

Thanks for your time and effort. I'm definitely enjoying that it's focused on file management. Keep up the good work.

**Comment by vishal0071** [comment]
This has already been fixed, please wait for new update.

**Comment by JSn1nj4** [comment]
Alright then, I'll look for the next version. Thanks.
