### ISSUE TITLE
F-droid version won't run

### ISSUE THREAD

**Issue by firecat53** [arpitkh96/AmazeFileManager#694]
When installed via F-droid, Amaze immediately closes on start. The settings menu will function when opened from the Android app info window. Installing via Play Store works fine. Installing an older version from F-droid still crashes.

Deleted the settings directory in ~/Android/data/com.amaze.filemanager but that has no effect.

Android 7.0 on stock Verizon Motorola Droid Turbo 2.

**Comment by vishal0071** [comment]
What version of fdroid build you tried? Also try clearing app data from system settings and see if it helps.

**Comment by firecat53** [comment]
Sorry for the noise... Clearing data from app info fixed it. For some reason I thought deleting the folder I mentioned would have the same effect. Closing!

**Comment by vishal0071** [comment]
It's fine! Just a FYI, clearing app data also deletes data from /data/data/package hence deleting all the databases. The problem was probably caused by change in database schema, hence clearing data fixes the problem.
