### ISSUE TITLE
Long time to build this project

### ISSUE THREAD

**Issue by Lwenkun** [arpitkh96/AmazeFileManager#712]
I use Android Sutdio of version 2.3.3 to build this project. But It's "building AmazeFileManager for gradle project info" for a long time and haven't finished up till now. Is there any suggestion ?

**Comment by EmmanuelMess** [comment]
Get a better pc?

**Comment by Lwenkun** [comment]
I use macbookpro to build. So I don't think it's caused by pc's performance. Today I used my company's computer to open it. It took at least 25 minutes before this project could be viewed. In the end, this problem was solved by my patience.

**Comment by vishal0071** [comment]
Actually the first build always takes time. Factors accelerating this are good processor, SSD, good connection. Once I had these it took hardly a min or two to built on a fresh install. Earlier I had bad combination and it used to take 5-10 mins.
