### ISSUE TITLE
Calculate MD5 sum on request or in an indipendent thread

### ISSUE THREAD

**Issue by utack** [arpitkh96/AmazeFileManager#83]
When opening the file properties Amaze is frozen until the MD5 sum of the file is calculated.
Even on relatively modern phones this easily results in a extremely long period that the whole file manager is not responding, when showing the properties of large files.
One solution would be to caluclate the MD5 in a separate thread and display it when ready.
Maybe better: insert a button to trigger the MD5 caluclation, as it is rarely needed.

**Comment by vishal0071** [comment]
fixed

**Comment by utack** [comment]
Would be cool if you could make a tag at some point, so the feature lands in the F-Droid binary :)

**Comment by vishal0071** [comment]
Will make a new release as some major bugs are fixed.
