### ISSUE TITLE
Open with does not force app chooser

### ISSUE THREAD

**Issue by lbdroid** [arpitkh96/AmazeFileManager#98]
When selecting "open with", the user will expect to be presented with a choice among ALL applications with intent filters to handle the file. AmazeFileManager currently only uses the "set" handler, i.e. "open with" --> "From now on".

When choosing "open with", the user should *always* be presented with a choice among all handlers.

Please see;
http://developer.android.com/guide/components/intents-filters.html#ForceChooser

**Comment by vishal0071** [comment]
Force Chooser dialog comes once you choose "Other" from the Open with dialog. 
The open with dialog just makes it easy for you by not going through the long list of all apps. Otherwise you can always choose to open according to your own using other option

**Comment by lbdroid** [comment]
You aren't understanding.
The issue is that the open with dialog *does not show* once you have selected an item and flagged it to always use that handler.

**Comment by arpitkh96** [comment]
Your issue is expected to be solved with latest commit. At least for text files. Zip files will still be preferred to be opened directly in app only. Still you can use "open with " for them

**Comment by lbdroid** [comment]
Ok.

I see the switch to openunknown. I don't see a change to long-press-->open-with using force-chooser.

What is the rationale for keeping zip files handled internally? Presumably, if the user has installed an alternative zip file handler, they would have installed it because they prefer to use it.

**Comment by lbdroid** [comment]
Here, I *think* this should do it; https://github.com/lbdroid/AmazeFileManager/commit/2bb97fac8e091818d3c5cfebbce7bffc26008869

Note: I have NOT created a pull request, because I am not in a position right now to compile/test it.

**Comment by arpitkh96** [comment]
Zip viewing was preserved so the animations work fine. I don't know why but fragment transitions don't animate in new activity. I will look into that commit

**Comment by lbdroid** [comment]
You should be able to use Intent.resolveActivity(PackageManager) or PackageManager.resolveActivity(Intent, MATCH_DEFAULT_ONLY) to detect if we are the default handler, and then transition the fragment directly.

**Comment by lbdroid** [comment]
I've been able to test that commit now, and it works exactly as expected. When you click on a file, it will launch the default handler, or show chooser if there is no set default. When you long-click --> menu --> open with, it ALWAYS forces the chooser.
